aws/aws-dotnet-deploy

src/AWS.Deploy.CLI/AWS.Deploy.CLI.csproj, src/AWS.Deploy.Recipes.CDK.Common/AWS.Deploy.Recipes.CDK.Common.csproj
Add PackageProjectUrl to NuGet packages
=> Add PackageProjectUrl to NuGet packages

src/AWS.Deploy.CLI/AWS.Deploy.CLI.csproj, src/AWS.Deploy.Orchestrator/CDK/CDKConstants.cs, src/AWS.Deploy.Recipes.CDK.Common/AWS.Deploy.Recipes.CDK.Common.csproj, src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppEcsFargate/AspNetAppEcsFargate.csproj, src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/AspNetAppElasticBeanstalkLinux.csproj, src/AWS.Deploy.Recipes/CdkTemplates/BlazorWasm/BlazorWasm.csproj, src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateScheduleTask/ConsoleAppECSFargateScheduleTask.csproj, src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateService/ConsoleAppECSFargateService.csproj
Fix for https://github.com/advisories/GHSA-pch5-whg9-qr2r
Release info: https://github.com/aws/aws-cdk/releases/tag/v1.95.2
=> fix: update minimum CDK version to 1.95.2

test/AWS.Deploy.CLI.UnitTests/DeploymentBundleHandlerTests.cs
Fixed directory seperation for tests to support linux dotnet test
=> Fixed directory seperation for tests to support linux dotnet test

test/AWS.Deploy.Orchestration.UnitTests/TestFileManager.cs
Fix unit test compatibility on linux
=> Fix unit test compatibility on linux

.github/workflows/BuildandTest.yml
Added a GitHub Workflow to Build and Test
=> Added a GitHub Workflow to Build and Test

.chglog/CHANGELOG.tpl.md, .chglog/config.yml, Directory.Build.props, version.json
DOTNET-5019
Added NerdBank.GitVersioning and git-chglog config files
=> Added NerdBank.GitVersioning and git-chglog config files

.github/workflows/BuildandTest.yml
Updated fetch depth for github workflow
=> chore: Updated fetch depth for github workflow

.github/workflows/BuildandTest.yml
Until we find a way to run integration tests. Disable them.
=> fix: add UnitTests filter for PR to only allow running UnitTests

AWS.Deploy.sln, test/AWS.Deploy.CLI.IntegrationTests/AWS.Deploy.CLI.IntegrationTests.csproj, test/AWS.Deploy.CLI.IntegrationTests/BlazorWasmTests.cs, test/AWS.Deploy.CLI.IntegrationTests/ConsoleAppTests.cs, test/AWS.Deploy.CLI.IntegrationTests/Extensions/ReadAllLinesStreamReaderExtension.cs, test/AWS.Deploy.CLI.IntegrationTests/Extensions/TestServiceCollectionExtension.cs, test/AWS.Deploy.CLI.IntegrationTests/Helpers/CloudFormationHelper.cs, test/AWS.Deploy.CLI.IntegrationTests/Helpers/CloudWatchLogsHelper.cs, test/AWS.Deploy.CLI.IntegrationTests/Helpers/ECSHelper.cs, test/AWS.Deploy.CLI.IntegrationTests/Helpers/HttpHelper.cs, test/AWS.Deploy.CLI.IntegrationTests/Helpers/WaitUntilHelper.cs, test/AWS.Deploy.CLI.IntegrationTests/Services/InMemoryInteractiveService.cs, test/AWS.Deploy.CLI.IntegrationTests/Services/InMemoryInteractiveServiceTests.cs, test/AWS.Deploy.CLI.IntegrationTests/WebAppNoDockerFileTests.cs, test/AWS.Deploy.CLI.IntegrationTests/WebAppWithDockerFileTests.cs, testapps/ConsoleAppService/Dockerfile, testapps/ConsoleAppTask/Dockerfile, testapps/WebAppWithDockerFile/Dockerfile
This is follow-up to https://github.com/aws/aws-dotnet-deploy/pull/195. I couldn't push the change after rebasing to origin/deb due to not having permission to modify workflow in my fork.
=> https://github.com/aws/aws-dotnet-deploy/pull/195

src/AWS.Deploy.CLI/AWSUtilities.cs, src/AWS.Deploy.CLI/Commands/CommandFactory.cs, src/AWS.Deploy.CLI/Commands/DeployCommand.cs, src/AWS.Deploy.CLI/Exceptions.cs, src/AWS.Deploy.CLI/Utilities/ProjectParserUtility.cs, src/AWS.Deploy.Common/Exceptions.cs, src/AWS.Deploy.Common/Recipes/OptionSettingItem.ValueOverride.cs, src/AWS.Deploy.DockerEngine/Exceptions.cs, src/AWS.Deploy.Orchestration/DeploymentBundleHandler.cs, src/AWS.Deploy.Orchestration/Exceptions.cs, src/AWS.Deploy.Orchestration/Orchestrator.cs, src/AWS.Deploy.Orchestration/TemplateEngine.cs
This PR introduces the following changes:
1. Adds the `AWSDeploymentExpectedException` decorator to all the expected exceptions - https://sim.amazon.com/issues/DOTNET-5026
2. Standardize all expected exception constructors by adding a message and an optional innerException with the default value as null - https://sim.amazon.com/issues/DOTNET-5025
3. Catch all non-expected exceptions in AWS.Deploy.DockerEngine and wrap them inside an expected Exception - https://sim.amazon.com/issues/DOTNET-5027
4. Catch all expected exceptions in the UI layer and present the end-user with a message in a single place - https://sim.amazon.com/issues/DOTNET-5028
5. Adds diagnostic capabilities to provide a granular view of errors. - https://sim.amazon.com/issues/DOTNET-5029
=> feat: Improved error handling

src/AWS.Deploy.CLI/AWS.Deploy.CLI.csproj, src/AWS.Deploy.Recipes.CDK.Common/AWS.Deploy.Recipes.CDK.Common.csproj
chore: Remove version prefix from projects
=> chore: Remove version prefix from projects

Directory.Build.props, src/Directory.Build.props
fix: NerdBank.GitVersioning was not being used
=> fix: NerdBank.GitVersioning was not being used

src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/AppStack.cs, src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Configurations/Configuration.cs, src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Configurations/ElasticBeanstalkManagedPlatformUpdatesConfiguration.cs, src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalk.recipe, test/AWS.Deploy.CLI.UnitTests/GetOptionSettingTests.cs
=> Added ability to Enable/Disable Managed Platform Updates

test/AWS.Deploy.CLI.IntegrationTests/BlazorWasmTests.cs, test/AWS.Deploy.CLI.IntegrationTests/ConsoleAppTests.cs, test/AWS.Deploy.CLI.IntegrationTests/WebAppNoDockerFileTests.cs, test/AWS.Deploy.CLI.IntegrationTests/WebAppWithDockerFileTests.cs
=> feat: add list-deployments command to integ tests

.chglog/CHANGELOG.tpl.md, .chglog/config.yml
=> fix: capitalize first letter of the changelog commit messages

version.json
=> build: Version bump to 0.6

version.json
=> build: Version bump to 0.7

.chglog/CHANGELOG.tpl.md
=> chore: remove date from changelog

src/AWS.Deploy.CLI/Commands/ServerModeCommand.cs
Since server mode is still being developed and will likely go through many iterations we need to warn any curious users who stumble across in our released tool that this is experimental 
=> feat: Add warning about using server mode

src/AWS.Deploy.CLI/Commands/ServerModeCommand.cs
DOTNET-5083
feat: monitor parent process and terminate if parent process is no longer running
=> feat: monitor parent process and terminate if parent process is no longer running

version.json
=> build: Version bump to 0.8

version.json
=> build: Version bump to 0.9

src/AWS.Deploy.CLI/Utilities/CommandLineWrapper.cs
fix: fix telemetry info not being reported
=> fix: fix telemetry info not being reported

version.json
=> build: Version bump to 0.10

version.json
=> build: Version bump to 0.11

src/AWS.Deploy.CLI/Commands/DeployCommand.cs, src/AWS.Deploy.CLI/Exceptions.cs
fixed typo in 'FailedToFindCompatibleRecipeException'.
=> chore: fixed typo in 'FailedToFindCompatibleRecipeException'

src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppEcsFargate/AspNetAppEcsFargate.csproj, src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/AspNetAppElasticBeanstalkLinux.csproj, src/AWS.Deploy.Recipes/CdkTemplates/BlazorWasm/BlazorWasm.csproj, src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateScheduleTask/ConsoleAppECSFargateScheduleTask.csproj, src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateService/ConsoleAppECSFargateService.csproj
=> build: CDK templates roll forward to run versions higher than netcoreapp3.1

version.json
=> build: Version bump to 0.12

src/AWS.Deploy.DockerEngine/Properties/DockerFileConfig.json, src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppECSFargate.recipe, src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateScheduleTask.recipe, src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateService.recipe
Update the ECS template and docker generation to support .NET 6
=> Update ECS templates and docker generation to support .NET 6

src/AWS.Deploy.CLI/Commands/ServerModeCommand.cs
IDE-4723
fix: server mode not shutting down when parent process exits
=> fix: server mode not shutting down when parent process exits

src/AWS.Deploy.CLI/ServerMode/Controllers/RecipeController.cs, src/AWS.Deploy.CLI/ServerMode/Models/RecipeSummary.cs, src/AWS.Deploy.Orchestration/Exceptions.cs, src/AWS.Deploy.Orchestration/RecipeHandler.cs, src/AWS.Deploy.ServerMode.Client/RestAPI.cs, test/AWS.Deploy.CLI.UnitTests/ServerModeTests.cs
feat: add GetRecipe API to describe Recipes returned by other APIs
=> feat: add GetRecipe API to describe Recipes returned by other APIs

version.json
=> build: Version bump to 0.13

src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppEcsFargate/AspNetAppEcsFargate.csproj, src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/AspNetAppElasticBeanstalkLinux.csproj, src/AWS.Deploy.Recipes/CdkTemplates/BlazorWasm/BlazorWasm.csproj, src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateScheduleTask/ConsoleAppECSFargateScheduleTask.csproj, src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateService/ConsoleAppECSFargateService.csproj
feat: enable nullability for CDK Templates
=> feat: enable nullability for CDK Templates

src/AWS.Deploy.ServerMode.Client/Exceptions.cs, src/AWS.Deploy.ServerMode.Client/ServerModeSession.cs
IDE-5339
feat: specify local deploy tool to use in server mode
=> feat: specify local deploy tool to use in server mode

src/AWS.Deploy.Common/Recipes/OptionSettingItem.ValueOverride.cs
IDE-5329
fix: validation messages are not user friendly
=> fix: validation messages are not user friendly

src/AWS.Deploy.CLI/Commands/DeployCommand.cs, src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs, src/AWS.Deploy.Common/Extensions/GenericExtensions.cs, src/AWS.Deploy.Common/Recommendation.cs, test/AWS.Deploy.CLI.UnitTests/ApplyPreviousSettingsTests.cs
fix: previous settings are applied to global SelectedRecommendation in state object
=> fix: previous settings are applied to global SelectedRecommendation in state object

.chglog/config.yml
* Changed ordering of commit types
* Changed ordering of commits to alphabetical order
=> build: Updated changelog title order

src/AWS.Deploy.Common/Recommendation.cs
fix: recommendation unit tests were failing after merge
=> fix: recommendation unit tests were failing after merge

src/AWS.Deploy.CLI/Commands/CommandFactory.cs, src/AWS.Deploy.CLI/Commands/GenerateDeploymentProjectCommand.cs, src/AWS.Deploy.CLI/Extensions/CustomServiceCollectionExtension.cs, src/AWS.Deploy.Common/DeploymentManifest/DeploymentManifestEngine.cs, src/AWS.Deploy.Common/DeploymentManifest/DeploymentManifestEntry.cs, src/AWS.Deploy.Common/DeploymentManifest/DeploymentManifestModel.cs, src/AWS.Deploy.Common/Exceptions.cs, src/AWS.Deploy.Common/IO/DirectoryManager.cs, test/AWS.Deploy.CLI.Common.UnitTests/AWS.Deploy.CLI.Common.UnitTests.csproj, test/AWS.Deploy.CLI.Common.UnitTests/DeploymentManifestFile/DeploymentManifestFileTests.cs, test/AWS.Deploy.CLI.Common.UnitTests/IO/TestDirectoryManager.cs, test/AWS.Deploy.CLI.IntegrationTests/SaveCdkDeploymentProject/SaveCdkDeploymentProjectTests.cs
DOTNET-5236
This PR creates a deployment-manifest file to keep track of the saved CDK deployment projects.
=> feat: Create a deployment-manifest file

version.json
=> build: Version bump to 0.14

src/AWS.Deploy.ServerMode.Client/ServerModeSession.cs
fix: passing a deploy tool to ServerModeSession fails
=> fix: passing a deploy tool to ServerModeSession fails

src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs, src/AWS.Deploy.CLI/ServerMode/Controllers/RecipeController.cs, src/AWS.Deploy.CLI/ServerMode/Models/RecipeSummary.cs, src/AWS.Deploy.Common/Recipes/RecipeDefinition.cs, src/AWS.Deploy.Common/Recommendation.cs, src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppECSFargate.recipe, src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalk.recipe, src/AWS.Deploy.Recipes/RecipeDefinitions/BlazorWasm.recipe, src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateScheduleTask.recipe, src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateService.recipe, src/AWS.Deploy.Recipes/RecipeDefinitions/aws-deploy-recipe-schema.json, src/AWS.Deploy.ServerMode.Client/RestAPI.cs, test/AWS.Deploy.CLI.Common.UnitTests/Recipes/Validation/ValidatorFactoryTests.cs, test/AWS.Deploy.CLI.UnitTests/DeploymentBundleHandlerTests.cs
feat: add short description to recipes
=> feat: add short description to recipes

src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
AWS Credentials are used by both the IAWSClientFactory and the ICommandWrapper. Before this fix the credentials tied to the server mode session were only being used by the IAWSClientFactory which allowed server mode to make SDK calls using the correct region. The server mode session credentials were not being passed into the ICommandWrapper which means when it shells out to the CDK it picks up instead the default environment credentials.
This fix ensures the server mode session AWS credentials are now passed into the ICommandWrapper.
=> fix: Make sure credentials tied to the current server mode session is used when invoking the CDK

test/AWS.Deploy.CLI.IntegrationTests/ConfigFileDeployment/ElasticBeanStalkDeploymentTest.cs, test/AWS.Deploy.CLI.IntegrationTests/WebAppNoDockerFileTests.cs
fix: integration tests failing
=> fix: integration tests failing

src/AWS.Deploy.CLI/Commands/CommandFactory.cs, src/AWS.Deploy.CLI/Commands/CommandHandlerInput/DeployCommandHandlerInput.cs, src/AWS.Deploy.CLI/Commands/CommandHandlerInput/GenerateDeploymentProjectCommandHandlerInput.cs, src/AWS.Deploy.CLI/Commands/DeployCommand.cs, src/AWS.Deploy.CLI/Commands/GenerateDeploymentProjectCommand.cs, src/AWS.Deploy.CLI/Extensions/CustomServiceCollectionExtension.cs, src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs, src/AWS.Deploy.Common/DeploymentManifest/DeploymentManifestEngine.cs, src/AWS.Deploy.Common/IO/DirectoryManager.cs, src/AWS.Deploy.Common/Recipes/OptionSettingItem.cs, src/AWS.Deploy.Common/Recipes/RecipeDefinition.cs, src/AWS.Deploy.Common/SerializeRecipeContractResolver.cs, src/AWS.Deploy.Orchestration/CdkProjectHandler.cs, src/AWS.Deploy.Orchestration/CustomRecipeLocator.cs, src/AWS.Deploy.Orchestration/Orchestrator.cs, src/AWS.Deploy.Orchestration/RecommendationEngine/RecommendationEngine.cs, src/AWS.Deploy.Orchestration/TemplateEngine.cs, test/AWS.Deploy.CLI.Common.UnitTests/DeploymentManifestFile/DeploymentManifestFileTests.cs, test/AWS.Deploy.CLI.Common.UnitTests/IO/TestDirectoryManager.cs, test/AWS.Deploy.CLI.IntegrationTests/SaveCdkDeploymentProject/CustomRecipeLocatorTests.cs, test/AWS.Deploy.CLI.IntegrationTests/SaveCdkDeploymentProject/RecommendationTests.cs, test/AWS.Deploy.CLI.IntegrationTests/SaveCdkDeploymentProject/SaveCdkDeploymentProjectTests.cs, test/AWS.Deploy.CLI.IntegrationTests/SaveCdkDeploymentProject/Utilities.cs, test/AWS.Deploy.CLI.IntegrationTests/Utilities/TestToolAWSResourceQueryer.cs, test/AWS.Deploy.CLI.UnitTests/Utilities/TestToolAWSResourceQueryer.cs
DOTNET-5238
This PR adds the functionality to list the saved CDK projects as deployment options.
=> feat: List saved CDK projects as deployment options

test/AWS.Deploy.CLI.IntegrationTests/SaveCdkDeploymentProject/CustomRecipeLocatorTests.cs, test/AWS.Deploy.CLI.IntegrationTests/SaveCdkDeploymentProject/SaveCdkDeploymentProjectTests.cs
This PR fixes the integration tests that were failing in CodePipeline
=> fix: Fix integration tests that are failing in CodePipeline

src/AWS.Deploy.CLI/Commands/CommandFactory.cs, src/AWS.Deploy.CLI/Commands/DeleteDeploymentCommand.cs, src/AWS.Deploy.CLI/Commands/DeployCommand.cs, src/AWS.Deploy.CLI/Commands/GenerateDeploymentProjectCommand.cs, src/AWS.Deploy.CLI/Extensions/CustomServiceCollectionExtension.cs, src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs, src/AWS.Deploy.CLI/ServerMode/Models/ExistingDeploymentSummary.cs, src/AWS.Deploy.Common/CloudApplication.cs, src/AWS.Deploy.Common/DeploymentManifest/DeploymentManifestEngine.cs, src/AWS.Deploy.Common/DeploymentManifest/DeploymentManifestModel.cs, src/AWS.Deploy.Common/ProjectDefinition.cs, src/AWS.Deploy.Common/SerializeModelContractResolver.cs, src/AWS.Deploy.Orchestration/Exceptions.cs, src/AWS.Deploy.Orchestration/LocalUserSettings/LastDeployedStack.cs, src/AWS.Deploy.Orchestration/LocalUserSettings/LocalUserSettings.cs, src/AWS.Deploy.Orchestration/LocalUserSettings/LocalUserSettingsEngine.cs, src/AWS.Deploy.Orchestration/Orchestrator.cs, src/AWS.Deploy.Orchestration/RecommendationEngine/RecommendationEngine.cs, src/AWS.Deploy.Orchestration/Utilities/DeployedApplicationQueryer.cs, src/AWS.Deploy.ServerMode.Client/RestAPI.cs, test/AWS.Deploy.CLI.Common.UnitTests/DeploymentManifestFile/DeploymentManifestFileTests.cs, test/AWS.Deploy.CLI.Common.UnitTests/IO/TestFileManager.cs, test/AWS.Deploy.CLI.Common.UnitTests/LocalUserSettings/LocalUserSettingsTests.cs, test/AWS.Deploy.CLI.IntegrationTests/SaveCdkDeploymentProject/RecommendationTests.cs, test/AWS.Deploy.Orchestration.UnitTests/DeployedApplicationQueryerTests.cs, test/AWS.Deploy.Orchestration.UnitTests/TestDirectoryManager.cs
feat: Save last used stack and order existing deployments by MRU stack
=> feat: Save last used stack and order existing deployments by MRU stack

src/AWS.Deploy.CLI/Commands/CommandFactory.cs, src/AWS.Deploy.CLI/Commands/DeployCommand.cs, src/AWS.Deploy.CLI/Exceptions.cs, src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs, src/AWS.Deploy.CLI/ServerMode/Models/GetCompatibilityOutput.cs, src/AWS.Deploy.CLI/ServerMode/Models/SystemCapabilitySummary.cs, src/AWS.Deploy.Common/Exceptions.cs, src/AWS.Deploy.Orchestration/Exceptions.cs, src/AWS.Deploy.Orchestration/OrchestratorSession.cs, src/AWS.Deploy.Orchestration/SystemCapabilities.cs, src/AWS.Deploy.Orchestration/SystemCapabilityEvaluator.cs, src/AWS.Deploy.ServerMode.Client/RestAPI.cs, test/AWS.Deploy.CLI.UnitTests/ApplyPreviousSettingsTests.cs, test/AWS.Deploy.CLI.UnitTests/DeploymentBundleHandlerTests.cs, test/AWS.Deploy.CLI.UnitTests/GetOptionSettingTests.cs, test/AWS.Deploy.CLI.UnitTests/RecommendationTests.cs, test/AWS.Deploy.CLI.UnitTests/SetOptionSettingTests.cs, test/AWS.Deploy.Orchestration.UnitTests/DisplayedResourcesHandlerTests.cs
feat: Add GetCapabilities API to check for NodeJS and Docker installations
=> feat: Add GetCapabilities API to check for NodeJS and Docker installations

src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
feat: check if system capabilities are missing before deployment in server mode
=> feat: check if system capabilities are missing before deployment in server mode

src/AWS.Deploy.CLI/ServerMode/Startup.cs
IDE-5671
Fix vulnerability found during pen test. Added a filter on the allowed hosts 127.0.0.1 / localhost.
=> feat: Add a filter on the allowed hosts in server mode

src/AWS.Deploy.Recipes.CDK.Common/CDKRecipeSetup.cs, src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppEcsFargate/Generated/Configurations/AutoScalingConfiguration.cs, test/AWS.Deploy.CLI.IntegrationTests/WebAppWithDockerFileTests.cs
Fixes the re-deployment experience using the ECS Fargate recipe
=> fix: Fixes the re-deployment experience using the ECS Fargate recipe

src/AWS.Deploy.CLI/ConsoleInteractiveServiceImpl.cs, src/AWS.Deploy.Constants/CLI.cs
Set the title of the console window when starting the CLI tool.
=> feat: Set console title

src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalk.recipe, test/AWS.Deploy.CLI.IntegrationTests/ConfigFileDeployment/ElasticBeanStalkDeploymentTest.cs, test/AWS.Deploy.Orchestration.UnitTests/DisplayedResourcesHandlerTests.cs
=> fix: integration tests failing due to invalid resource output

.github/workflows/codebuild-ci.yml, version.json
It allows PR validation using aws-dotnet-deploy-ci CodeBuild that runs the integration tests.
=> feat: add CodeBuild CI GitHub workflow

src/AWS.Deploy.CLI/Commands/GenerateDeploymentProjectCommand.cs, src/AWS.Deploy.Orchestration/CdkProjectHandler.cs, src/AWS.Deploy.Orchestration/Orchestrator.cs, test/AWS.Deploy.CLI.IntegrationTests/BlazorWasmTests.cs, test/AWS.Deploy.CLI.IntegrationTests/ConsoleAppTests.cs, test/AWS.Deploy.CLI.IntegrationTests/SaveCdkDeploymentProject/Utilities.cs, test/AWS.Deploy.CLI.IntegrationTests/WebAppNoDockerFileTests.cs, test/AWS.Deploy.CLI.IntegrationTests/WebAppWithDockerFileTests.cs
DOTNET-5411
fix: Reword console output text in the CLI.
=> Reword Console Output Text

src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs, src/AWS.Deploy.CLI/ServerMode/Models/OptionSettingItemSummary.cs, src/AWS.Deploy.ServerMode.Client/RestAPI.cs
IDE-5946
feat: add AllowedValues and ValueMapping to GetConfigSettings
=> feat: add AllowedValues and ValueMapping to GetConfigSettings

src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
IDE-5945
fix: update StartDeploymentSession to return default stack name
=> fix: update StartDeploymentSession to return default stack name

src/AWS.Deploy.Recipes/CdkTemplates/BlazorWasm/Generated/Recipe.cs
Fix issue that if the backend rest api was HTTP that CloudFront would fail to reach it because it was being configured to only connect on HTTPS. This fix sets the origin protocol to match the url passed set for `BackendApi.Uri`
=> fix: Set HTTP origin for backend rest api to the protocol of the url passed set for BackendApi.Uri

src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs, src/AWS.Deploy.CLI/ServerMode/Models/OptionSettingItemSummary.cs
Break up Updatable flag into ReadOnly and Visible flags
=> fix: option setting updatable flag causes issues in toolkit

README.md, src/AWS.Deploy.CLI/ConsoleUtilities.cs
Fix typo "Additional Deployments Options"
=> Fix typo "Additional Deployments Options"

src/AWS.Deploy.ServerMode.Client/ServerModeHttpClient.cs
The authorization header http handler can be called by multiple threads causing a threading issue with generating the IV. This change makes locks access to the aes object when doing the encryption.
=> fix: Lock access around the AES object for creating the IV and encryption.

src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Configurations/Configuration.cs, src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Recipe.cs, src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalk.recipe
DOTNET-4808
add health check url setting to beanstalk deployments
=> feat: add health check url setting to beanstalk deployments

src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppAppRunner.recipe, test/AWS.Deploy.CLI.Common.UnitTests/Recipes/Validation/AppRunnerOptionSettingItemValidationTests.cs
DOTNET-5572
This PR adds input validation to option setting items in the App Runner recipe.
=> feat: Add input validation to option settings in app runner recipe

README.md
* Update Readme.md to reflect latest changes about supporting existing beanstalk deployments. Since the tool is no longer specifically tied to the CDK, I changed the wording to reflect that.
* Added a link to the dev guide.
=> chore: Update Readme.md to reflect latest changes

src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppAppRunner/Generated/Configurations/Configuration.cs, src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppAppRunner/Generated/Recipe.cs, src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppEcsFargate/Generated/Configurations/Configuration.cs, src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppEcsFargate/Generated/Recipe.cs, src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateScheduleTask/Generated/Configurations/Configuration.cs, src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateScheduleTask/Generated/Recipe.cs, src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateService/Generated/Configurations/Configuration.cs, src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateService/Generated/Recipe.cs, src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppAppRunner.recipe, src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppECSFargate.recipe, src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateScheduleTask.recipe, src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateService.recipe
DOTNET-5733
* Add Environment Variable setting to all recipes that support it
=> feat: add Environment Variable setting to all recipes that support it

README.md
Add link to AWS Reinvent 2021 Deploy tool session
=> docs: add link to AWS Reinvent 2021 Deploy tool session

src/AWS.Deploy.Orchestration/Utilities/CloudApplicationNameGenerator.cs, test/AWS.Deploy.Orchestration.UnitTests/Utilities/CloudApplicationNameGeneratorTests.cs
Fixes #507 
* Fixed the issue where the suffix is being reversed
* Removed constraint of 100 iterations
=> fix: name generation reverses suffixed digits and fails over 100

src/AWS.Deploy.CLI/App.cs
Remove banner to notify of NuGet package name change
=> chore: remove banner to notify of NuGet package name change

src/AWS.Deploy.CLI/Commands/DeployCommand.cs, src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs, src/AWS.Deploy.CLI/ServerMode/Controllers/RecipeController.cs, src/AWS.Deploy.CLI/Utilities/AssumeRoleMfaTokenCodeCallback.cs, src/AWS.Deploy.Common/Exceptions.cs, src/AWS.Deploy.Orchestration/DeploymentBundleHandler.cs, src/AWS.Deploy.Orchestration/Orchestrator.cs, src/AWS.Deploy.Orchestration/Utilities/ZipFileManager.cs, src/AWS.Deploy.ServerMode.Client/RestAPI.cs, test/AWS.Deploy.CLI.IntegrationTests/ServerModeTests.cs
=> Fix broken release

src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs, src/AWS.Deploy.CLI/ServerMode/ExtensionMethods.cs, src/AWS.Deploy.CLI/ServerMode/Models/DeployToolExceptionSummary.cs, src/AWS.Deploy.Common/Exceptions.cs, src/AWS.Deploy.Orchestration/CdkProjectHandler.cs, src/AWS.Deploy.Orchestration/DeploymentBundleHandler.cs, src/AWS.Deploy.Orchestration/Exceptions.cs, src/AWS.Deploy.Orchestration/Orchestrator.cs, src/AWS.Deploy.Orchestration/Utilities/ZipFileManager.cs, src/AWS.Deploy.ServerMode.Client/RestAPI.cs
Add process exit code to improve telemetry of failed processes
=> chore: add process exit code to improve telemetry of failed processes

src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs, src/AWS.Deploy.CLI/ServerMode/Models/SystemCapabilitySummary.cs, src/AWS.Deploy.Orchestration/SystemCapabilities.cs, src/AWS.Deploy.Orchestration/SystemCapabilityEvaluator.cs, src/AWS.Deploy.ServerMode.Client/RestAPI.cs
DOTNET-5889
This PR makes the following changes:
* Improves the error message for missing NodeJS dependency by explicitly asking the user to restart their IDE/Shell after the installation process completes. This is done so that the dependencies can be recognized correctly.
* Be explicit on on how to add missing dependency if an `InstallationUrl` is available.
* Removes and refactors some redundant code.
---
=> chore: Improve error message for missing NodeJS dependency

src/AWS.Deploy.CLI/Commands/CommandFactory.cs, src/AWS.Deploy.CLI/Commands/GenerateDeploymentProjectCommand.cs, src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs, src/AWS.Deploy.CLI/ServerMode/Controllers/RecipeController.cs, src/AWS.Deploy.CLI/ServerMode/Models/OptionSettingItemSummary.cs, src/AWS.Deploy.Common/Recipes/IRecipeHandler.cs, src/AWS.Deploy.Common/Recipes/OptionSettingItem.ValueOverride.cs, src/AWS.Deploy.Common/Recipes/OptionSettingItem.cs, src/AWS.Deploy.Common/Recipes/OptionSettingValidation.cs, src/AWS.Deploy.Orchestration/OptionSettingHandler.cs, src/AWS.Deploy.Orchestration/Orchestrator.cs, src/AWS.Deploy.Orchestration/RecipeHandler.cs, src/AWS.Deploy.Orchestration/RecommendationEngine/RecommendationEngine.cs, src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalk.recipe, src/AWS.Deploy.ServerMode.Client/RestAPI.cs, test/AWS.Deploy.CLI.IntegrationTests/ServerMode/DependencyValidationOptionSettings.cs, test/AWS.Deploy.CLI.IntegrationTests/ServerMode/GetApplyOptionSettings.cs, test/AWS.Deploy.CLI.IntegrationTests/Utilities/ServerModeUtilities.cs, test/AWS.Deploy.CLI.UnitTests/ServerModeTests.cs
DOTNET-5920
Fix integration tests for validation feature. The SaveCDKDeploymentProject tests were failing due to the RecipeHandler changes in previous PRs. 
=> fix integration tests for validation feature

test/AWS.Deploy.CLI.IntegrationTests/AWS.Deploy.CLI.IntegrationTests.csproj
=> fix: add AWS.Deploy.Recipes.CDK.Common to force building the project and create nupkg

test/AWS.Deploy.CLI.IntegrationTests/AWS.Deploy.CLI.IntegrationTests.csproj
=> hotfix for AWS.Deploy.Recipes.CDK.Common to force building the project … 

README.md, src/AWS.Deploy.Orchestration/SystemCapabilityEvaluator.cs, test/AWS.Deploy.CLI.IntegrationTests/SaveCdkDeploymentProject/RecommendationTests.cs
Update the supported NodeJS version from 10 to 14
=> chore: update the supported NodeJS version from 10 to 14

src/AWS.Deploy.CLI/AWS.Deploy.CLI.csproj, src/AWS.Deploy.Recipes.CDK.Common/AWS.Deploy.Recipes.CDK.Common.csproj, src/AWS.Deploy.Recipes.CDK.Common/README.md
=> build: add readme to nuget packages

mkdocs.yml, site/content/troubleshooting-guide/index.md, src/AWS.Deploy.CLI/Commands/CommandFactory.cs
DOTNET-6008
add troubleshooting guide and cut a ticket links on exception
=> feat: add troubleshooting guide and cut a ticket links on exception

site/content/docs/support.md, site/content/faq.md
Change the support matrix and faq for Windows support in Elastic Beanstalk.
=> docs: Doc changes for Windows support with Elastic Beanstalk

src/AWS.Deploy.CLI/Commands/TypeHints/BeanstalkApplicationCommand.cs, src/AWS.Deploy.CLI/Commands/TypeHints/BeanstalkEnvironmentCommand.cs, src/AWS.Deploy.CLI/Commands/TypeHints/DockerBuildArgsCommand.cs, src/AWS.Deploy.CLI/Commands/TypeHints/DockerExecutionDirectoryCommand.cs, src/AWS.Deploy.CLI/Commands/TypeHints/DotnetPublishArgsCommand.cs, src/AWS.Deploy.CLI/Commands/TypeHints/DotnetPublishBuildConfigurationCommand.cs, src/AWS.Deploy.CLI/Commands/TypeHints/ECRRepositoryCommand.cs, src/AWS.Deploy.CLI/Commands/TypeHints/ECSClusterCommand.cs, src/AWS.Deploy.CLI/Commands/TypeHints/ExistingVpcConnectorCommand.cs, src/AWS.Deploy.CLI/Commands/TypeHints/FilePathCommand.cs, src/AWS.Deploy.CLI/Commands/TypeHints/IAMRoleCommand.cs, src/AWS.Deploy.Common/AWS.Deploy.Common.csproj, src/AWS.Deploy.Common/DeploymentManifest/DeploymentManifestEngine.cs, src/AWS.Deploy.Common/Exceptions.cs, src/AWS.Deploy.Common/Extensions/GenericExtensions.cs, src/AWS.Deploy.Common/Recipes/IOptionSettingHandler.cs, src/AWS.Deploy.Common/Recipes/OptionSettingItem.ValueOverride.cs, src/AWS.Deploy.Common/Recipes/OptionSettingItem.cs, src/AWS.Deploy.Common/Recipes/Validation/RecipeValidators/FargateTaskCpuMemorySizeValidator.cs, src/AWS.Deploy.Common/UserDeploymentSettings.cs, src/AWS.Deploy.Orchestration/Exceptions.cs, src/AWS.Deploy.Orchestration/OptionSettingHandler.cs, src/AWS.Deploy.Orchestration/Orchestrator.cs
=> chore: update Newtonsoft.Json version

README.md
*Description of changes:* Add the NuGet version and downloads badges to the readme.
I intentionally did not use a semantic commit message to leave this out of the changelog.
=> Add NuGet badges to the readme

site/content/troubleshooting-guide/index.md
This PR fixes broken link in the troubleshooting guide.
=> docs: Fix broken link in the troubleshooting guide

src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppAppRunner.recipe, src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppECSFargate.recipe, src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalkLinux.recipe, src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalkWindows.recipe, src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppExistingBeanstalkEnvironment.recipe, src/AWS.Deploy.Recipes/RecipeDefinitions/BlazorWasm.recipe, src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateScheduleTask.recipe, src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateService.recipe, src/AWS.Deploy.Recipes/RecipeDefinitions/PushContainerImageECR.recipe
Since we are getting closer to GA this PR updates all of the recipe version numbers to 1.0.0.
=> chore: Update all recipe versions to 1.0.0

.github/workflows/DetectCDKBootstrapVersionChanges.yml
Add GitHub Action to detect new CDK Bootstrap template versions
=> ci: Add GitHub Action to detect new CDK Bootstrap template versions

README.md, site/content/index.md
remove statement that says project is in developer preview status
=> docs: remove statement that says project is in developer preview status

site/content/docs/commands/project.md, site/content/docs/commands/server-mode.md, site/content/index.md, site/content/troubleshooting-guide/missing-dependencies.md
DOTNET-6087
Removed TODO from documentation, and updated Node Version.
There are 2 more TODOs for deployment projects and CI/CD. Norm's PR will tackle deployment projects, and Malhar's upcoming PR will tackle CI/CD.
=> docs: update documentation to remove TODO

version.json
=> chore: update to the GA version 1.0

site/content/docs/cicd.md, site/content/docs/project.md
*Description of changes:* Removing placeholders from docs until the following PRs are merged:
1. CI/CD - https://github.com/aws/aws-dotnet-deploy/pull/668
2. Deployment projects - https://github.com/aws/aws-dotnet-deploy/pull/662
=> docs: Remove placeholders for future content

src/AWS.Deploy.Orchestration/CDK/CDKBootstrapTemplate.yaml
Update CDK bootstrap template version to 14
=> chore: update CDK bootstrap template version to 14

test/AWS.Deploy.CLI.IntegrationTests/ServerModeTests.cs
Server mode has the app sec requirement to only be connected via `127.0.0.1` or `localhost`. This restriction has already been implemented in Server mode [here](https://github.com/aws/aws-dotnet-deploy/blob/main/src/AWS.Deploy.CLI/ServerMode/Startup.cs#L31). This PR just adds the integ test to make sure we keep the required behavior.
=> chore: Add integ test confirming server mode connect behavior

site/content/docs/cicd.md, site/content/docs/commands/deploy.md
This PR adds the documentation about how integrate the deploy tool in a CI/CD pipeline
**Note** - Should only be merged after https://github.com/aws/aws-dotnet-deploy/pull/645 is merged
=> docs: Integrating with CI/CD

THIRD_PARTY_LICENSES, src/AWS.Deploy.CLI/AWS.Deploy.CLI.csproj, src/AWS.Deploy.CLI/Commands/TypeHints/ECRRepositoryCommand.cs, src/AWS.Deploy.Common/AWS.Deploy.Common.csproj, src/AWS.Deploy.Orchestration/AWS.Deploy.Orchestration.csproj, src/AWS.Deploy.Orchestration/DeploymentBundleHandler.cs, src/AWS.Deploy.ServerMode.Client/AWS.Deploy.ServerMode.Client.csproj, test/AWS.Deploy.CLI.IntegrationTests/AWS.Deploy.CLI.IntegrationTests.csproj, testapps/MessageProcessingApp/MessageProcessingApp.csproj
DOTNET-6410
Update AWS .NET SDK package references
=> chore: update AWS .NET SDK package references

.github/workflows/doc-builder.yml
=> ci: doc generator step was failing to push if there are no changes

src/AWS.Deploy.Orchestration/CDK/CDKBootstrapTemplate.yaml
Update CDK bootstrap template to v15 to fix failing PR check
=> chore: update CDK bootstrap template to v15

.github/workflows/BuildandTest.yml, .github/workflows/DetectCDKBootstrapVersionChanges.yml, .github/workflows/DetectDocGeneratorChanges.yml, .github/workflows/DetectRestAPIClientChanges.yml, .github/workflows/doc-builder.yml, .github/workflows/prepare-release.yml, .github/workflows/stale_issues.yml
Update the version of the github actions used to fix the warnings around Node.JS 12
=> chore: update the version of the github actions used

buildtools/ci.buildspec.yml, src/AWS.Deploy.Orchestration/CDK/CDKBootstrapTemplate.yaml
* chore: update cdk bootstrap template
* ci: upgrade node on AWS CodeBuilding CI workflow
=> chore: update cdk bootstrap template and node on GH workflow

src/AWS.Deploy.Orchestration/CDK/CDKBootstrapTemplate.yaml
chore: update CDK bootstrap template to version 18.
___
=> chore: update CDK bootstrap template

.github/workflows/handle-stale-discussions.yml, buildtools/ci.template.yml, version.json
Merge commits in `dev` to `main` branch.
___
=> Merge commits in dev to main branch.

mkdocs.yml, site/content/assets/js/beacon_scode.js
None
Add beacon functionality to the docs website.
=> enable beacon functionality for docs website

src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs, src/AWS.Deploy.CLI/ServerMode/Services/SessionAWSResourceQuery.cs, src/AWS.Deploy.CLI/ServerMode/SessionState.cs, src/AWS.Deploy.Common/Recipes/Validation/OptionSettingItemValidators/SecurityGroupsInVpcValidator.cs, test/AWS.Deploy.CLI.UnitTests/SessionAWSResourceQueryTests.cs
This PR is a copy of the previous https://github.com/aws/aws-dotnet-deploy/pull/830 with a commits squashed and a cleaned up commit message.
=> Cleaned up commit message

THIRD_PARTY_LICENSES, src/AWS.Deploy.Recipes.CDK.Common/AWS.Deploy.Recipes.CDK.Common.csproj, src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppAppRunner/AspNetAppAppRunner.csproj, src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppEcsFargate/AspNetAppEcsFargate.csproj, src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/AspNetAppElasticBeanstalkLinux.csproj, src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkWindows/AspNetAppElasticBeanstalkWindows.csproj, src/AWS.Deploy.Recipes/CdkTemplates/BlazorWasm/BlazorWasm.csproj, src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateScheduleTask/ConsoleAppECSFargateScheduleTask.csproj, src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateService/ConsoleAppEcsFargateService.csproj
A ticket was auto-cut internally to update the cdk versions.
Updating CDK version used by recipe cdk projects
=> Chore: update version of amazon.cdk.lib used by recipe cdk projects

.github/ISSUE_TEMPLATE/bug_report.yml, .github/workflows/issue-regression-labeler.yml
- Modified bug issue template to add checkbox to report potential regression.
- Added GitHub action to add/remove label `potential-regression` when issue is created/edited.
___
=> chore: Modified bug issue template to add checkbox to report potential regression.

.autover/changes/9911ed8d-0530-46a8-bb79-c83f3bb05920.json, src/AWS.Deploy.Orchestration/CDK/CDKBootstrapTemplate.yaml
Update the CDK Bootstrap template to the latest version in order to fix the CI failures.
=> chore: update the CDK Bootstrap template to the latest version

.autover/changes/a341e9ce-1356-465d-b1b4-77743905d586.json, src/AWS.Deploy.CLI/AWS.Deploy.CLI.csproj, src/AWS.Deploy.DockerEngine/AWS.Deploy.DockerEngine.csproj, src/AWS.Deploy.Orchestration/CDK/CDKBootstrapTemplate.yaml, src/AWS.Deploy.Recipes.CDK.Common/AWS.Deploy.Recipes.CDK.Common.csproj, src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppAppRunner/AspNetAppAppRunner.csproj, src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppEcsFargate/AspNetAppEcsFargate.csproj, src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/AspNetAppElasticBeanstalkLinux.csproj, src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkWindows/AspNetAppElasticBeanstalkWindows.csproj, src/AWS.Deploy.Recipes/CdkTemplates/BlazorWasm/BlazorWasm.csproj, src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateScheduleTask/ConsoleAppECSFargateScheduleTask.csproj, src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateService/ConsoleAppEcsFargateService.csproj
* Update System.Text.Json to 8.0.5 to address a high severity vulnerability
* Revert CDK bootstrap template to version 22 following CDK rollback
=> chore: address System.Text.Json vulnerabilities

.github/workflows/DetectRestAPIClientChanges.yml
Fix security issue caused by the version of the GItHub action `tj-actions/verify-changed-files`
=> ci: pin DetectRestAPIClientChanges workflow to specific GitHub action

.github/workflows/change-file-in-pr.yml, CONTRIBUTING.md, test/AWS.Deploy.CLI.IntegrationTests/Helpers/IAMHelper.cs
Sync `dev` and `main` branches
=> Sync dev and main

.github/workflows/BuildandTest.yml, .github/workflows/DetectCDKBootstrapVersionChanges.yml, .github/workflows/DetectDocGeneratorChanges.yml, .github/workflows/DetectRestAPIClientChanges.yml, .github/workflows/UploadDockerImage.yml, .github/workflows/aws-ci.yml, .github/workflows/change-file-in-pr.yml, .github/workflows/closed-issue-message.yml, .github/workflows/create-release-pr.yml, .github/workflows/doc-builder.yml, .github/workflows/handle-stale-discussions.yml, .github/workflows/issue-regression-labeler.yml, .github/workflows/semgrep-analysis.yml, .github/workflows/stale_issues.yml, .github/workflows/sync-main-dev.yml
*Issue #, if available:* DOTNET-8045
Update workflows to be pinned to sha. This is following the best practices https://www.stepsecurity.io/blog/pinning-github-actions-for-enhanced-security-a-complete-guide#:~:text=Action%20pinning%20with%20specific%20commit,point%20to%20different%20code%20versions
Created 2 scripts to update everything
```
function Convert-TagToCommit {
param (
[string]$owner,
[string]$repo,
[string]$tag
)
try {
$result = gh api "repos/$owner/$repo/git/refs/tags/$tag" | ConvertFrom-Json
return $result.object.sha
}
catch {
Write-Warning "Could not resolve tag $tag for $owner/$repo"
return $null
}
}
$workflowFiles = Get-ChildItem -Path ".github/workflows" -Filter "*.yml" -Recurse
foreach ($file in $workflowFiles) {
$content = Get-Content …
```
=> Update workflows to be pinned to sha

.autover/changes/c2231f60-987f-4787-9f86-b3cb068e2e95.json
DOTNET-8095
Add change file for major upgrade
=> chore: add change file for major upgrade

.github/workflows/AutoUpdateBootstrap.yml
=> merge dev into main
