aws/aws-dotnet-deploy

src/AWS.Deploy.CLI/CloudFormation/StackEventMonitor.cs
src/AWS.Deploy.CLI/Commands/DeleteDeploymentCommand.cs
src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.CLI/Commands/ListDeploymentsCommand.cs
src/AWS.Deploy.CLI/Commands/TypeHints/BeanstalkApplicationCommand.cs
src/AWS.Deploy.CLI/Commands/TypeHints/BeanstalkEnvironmentCommand.cs
src/AWS.Deploy.CLI/Commands/TypeHints/DotnetBeanstalkPlatformArnCommand.cs
src/AWS.Deploy.CLI/Commands/TypeHints/EC2KeyPairCommand.cs
src/AWS.Deploy.CLI/Commands/TypeHints/ECSClusterCommand.cs
src/AWS.Deploy.CLI/Commands/TypeHints/IAMRoleCommand.cs
src/AWS.Deploy.CLI/Commands/TypeHints/TypeHintCommandFactory.cs
src/AWS.Deploy.CLI/Commands/TypeHints/VpcCommand.cs
src/AWS.Deploy.CLI/Program.cs
src/AWS.Deploy.CLI/Utilities/CommandLineWrapper.cs
src/AWS.Deploy.Common/DefaultAWSClientFactory.cs
src/AWS.Deploy.Common/IAWSClientFactory.cs
src/AWS.Deploy.Orchestration/Data/AWSResourceQueryer.cs
src/AWS.Deploy.Orchestration/DeploymentBundleHandler.cs
src/AWS.Deploy.Orchestration/Orchestrator.cs
src/AWS.Deploy.Orchestration/RecommendationEngine/RecommendationEngine.cs
src/AWS.Deploy.Orchestration/Utilities/DeployedApplicationQueryer.cs
src/AWS.Deploy.Orchestration/Utilities/TemplateMetadataReader.cs
test/AWS.Deploy.CLI.UnitTests/DeploymentBundleHandlerTests.cs
test/AWS.Deploy.CLI.UnitTests/TemplateMetadataReaderTests.cs
test/AWS.Deploy.CLI.UnitTests/TestAWSClientFactory.cs
test/AWS.Deploy.CLI.UnitTests/Utilities/TestToolAWSResourceQueryer.cs

**Non Functional Change**
This refactor helps reduce overuse/misuse of `OrchestratorSession` as a CredetialStore that needed to be passed around in areas not really using "Orchestration"
Also refactors out reading cloud application metadata so less commands rely on Orchestrator.
Meat of change:
Which allowed:
And also: 
Which cleans up List and Delete commands.

chore: Reduce use of OrchestratorSession

---

src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.CLI/Program.cs

https://github.com/aws/aws-dotnet-deploy/issues/164
This change allows customers to pass stack-name  as part of deploy command. When specified, CLI doesn't ask for stack-name and directly jumps to the option setting configuration step.

feat: allow passing stack-name as a param to deploy command

---

src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.CLI/Program.cs
src/AWS.Deploy.Orchestration/Orchestrator.cs
src/AWS.Deploy.Orchestration/OrchestratorSession.cs

**Non Functional Change**
`CDKManager` is a dependency used by `Orchestrator`.  Moved it out of `OrchestratorSession`, which is meant to model session state, and constructor injected through `DeployCommand` and into `Orchestrator`

chore: move CDKManager dependency out of OrchestratorSession

---

src/AWS.Deploy.CLI/AWSUtilities.cs
src/AWS.Deploy.CLI/ConsoleInteractiveServiceImpl.cs
src/AWS.Deploy.CLI/ConsoleUtilities.cs
src/AWS.Deploy.CLI/IToolInteractiveService.cs
src/AWS.Deploy.CLI/Utilities/AssumeRoleMfaTokenCodeCallback.cs
test/AWS.Deploy.CLI.UnitTests/ConsoleUtilitiesTests.cs
test/AWS.Deploy.CLI.UnitTests/TestToolInteractiveServiceImpl.cs

Hook up a callback to the AssumeRoleAWSCredentials object for the user to enter an MFA token. This is a port for the MFA support in Amazon.Lambda.Tools.
Closes #141

Add support for profiles that are configured for MFA

---

src/Directory.Build.props

This PR adds the TreatWarningsAsErrors property to all projects located at `..\aws-dotnet-deploy\src` by adding a `Directory.Build.props` file inside the `src` folder
https://sim.amazon.com/issues/DOTNET-5004

chore: Enable TreatWarningsAsErrors by adding this property to src/Directory.Build.props file

---

src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.CLI/ConsoleUtilities.cs
src/AWS.Deploy.Common/Recipes/OptionSettingItem.ValueOverride.cs
src/AWS.Deploy.Common/Recommendation.cs

* Child option settings IDs are displayed instead of names
* DependsOn property not respected in Child option settings
* Child option settings of type Bool are not being displayed
**Before**
**After**

fix: Child option settings IDs are displayed instead of names and DependsOn property not respected

---

src/AWS.Deploy.Recipes.CDK.Common/AWS.Deploy.Recipes.CDK.Common.csproj

chore: Local NuGet cache is now created for all configurations

chore: Local NuGet cache is now created for all configurations

---

src/AWS.Deploy.CLI/CommandReturnCodes.cs
src/AWS.Deploy.CLI/Commands/CommandFactory.cs
src/AWS.Deploy.CLI/Commands/ServerModeCommand.cs
src/AWS.Deploy.CLI/Exceptions.cs
test/AWS.Deploy.CLI.UnitTests/ServerModeTests.cs

DOTNET-5084
feat: server mode exits with code -100 if port is in use

feat: server mode exits with code -100 if port is in use

---

src/AWS.Deploy.ServerMode.Client/DeploymentCommunicationClient.cs
src/AWS.Deploy.ServerMode.Client/RestAPI.cs
src/AWS.Deploy.ServerMode.ClientGenerator/Program.cs

Create interfaces for server mode clients to allow VS to be able to mock the clients.
The RestAPI interface is generated but setting the `GenerateClientInterfaces` property to true in the generator.
The SignalR DeploymentCommunicationClient interface is created by hand extracting the public methods from DeploymentCommunicationClient.

feat: Generate interfaces for server mode clients

---

AWS.Deploy.sln
src/AWS.Deploy.ServerMode.Client/CommandLineWrapper.cs
src/AWS.Deploy.ServerMode.Client/Exceptions.cs
src/AWS.Deploy.ServerMode.Client/ServerModeSession.cs
src/AWS.Deploy.ServerMode.Client/WaitUntilHelper.cs
test/AWS.Deploy.ServerMode.Client.UnitTests/AWS.Deploy.ServerMode.Client.UnitTests.csproj
test/AWS.Deploy.ServerMode.Client.UnitTests/ServerModeSessionTests.cs

ServerModeSession exposes Start method which starts the deployment tools server on a random registered port number for the given process id.
It also offers resiliency for port unavailable error by allow a configurable number of retries.
https://user-images.githubusercontent.com/8882380/120391508-f47b0600-c2e3-11eb-82eb-2e01507927bc.mp4

feat: implement `ServerModeSession` utility class

---

src/AWS.Deploy.CLI/Commands/DeployCommand.cs

Update error message when Node.js is missing or outdated to encourage users to update to the latest LTS version of Node.js.

Update error message for missing or outdated Node.js install

---

src/AWS.Deploy.CLI/AWS.Deploy.CLI.csproj
src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.CLI/ConsoleInteractiveServiceImpl.cs
src/AWS.Deploy.CLI/ConsoleOrchestratorLogger.cs
src/AWS.Deploy.CLI/ConsoleUtilities.cs
src/AWS.Deploy.CLI/Exceptions.cs
src/AWS.Deploy.CLI/IToolInteractiveService.cs
src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
src/AWS.Deploy.CLI/ServerMode/Hubs/DeploymentCommunicationHub.cs
src/AWS.Deploy.CLI/ServerMode/Services/SessionOrchestratorInteractiveService.cs
src/AWS.Deploy.Common/Exceptions.cs
src/AWS.Deploy.Common/ProjectDefinition.cs
src/AWS.Deploy.Common/ProjectDefinitionParser.cs
src/AWS.Deploy.DockerEngine/DockerEngine.cs
src/AWS.Deploy.DockerEngine/DockerFile.cs
src/AWS.Deploy.DockerEngine/Exceptions.cs
src/AWS.Deploy.Orchestration/CdkAppSettingsSerializer.cs
src/AWS.Deploy.Orchestration/DeploymentBundleHandler.cs
src/AWS.Deploy.Orchestration/Exceptions.cs
src/AWS.Deploy.Orchestration/IOrchestratorInteractiveService.cs
src/AWS.Deploy.Orchestration/RecommendationEngine/FileExistsTest.cs
src/AWS.Deploy.Orchestration/TemplateEngine.cs
src/AWS.Deploy.Recipes/DeploymentBundleDefinitionLocator.cs
src/AWS.Deploy.Recipes/RecipeLocator.cs
src/AWS.Deploy.ServerMode.Client/AWS.Deploy.ServerMode.Client.csproj
src/AWS.Deploy.ServerMode.ClientGenerator/Program.cs

Closes #224 
Add NET5 as a target framework
Fix nullability issues caused as a result of adding NET5 as a TF

build: add ability to roll forward to run versions higher than netcoreapp3.1

---

src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppECSFargate.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateScheduleTask.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateService.recipe

Previously the ECS service model did not allow underscores to be a part of the cluster name - [link](https://github.com/aws/aws-sdk-net/blob/51023cdd2a7ee03ac3cc80aa01da56a1fe8296d0/generator/ServiceModels/ecs/ecs-2014-11-13.normal.json#L1810)
However, the current model allows underscore characters - [link](https://github.com/aws/aws-sdk-net/blob/master/generator/ServiceModels/ecs/ecs-2014-11-13.normal.json#L1815)
This PR modifies the regex validation on ECS cluster name to accommodate underscore characters

fix: Modified ECS cluster name regex validation

---

src/AWS.Deploy.CLI/Utilities/CommandLineWrapper.cs
src/AWS.Deploy.Orchestration/CdkProjectHandler.cs
src/AWS.Deploy.Orchestration/Utilities/ICommandLineWrapper.cs
test/AWS.Deploy.CLI.UnitTests/Utilities/TestToolCommandLineWrapper.cs
test/AWS.Deploy.Orchestration.UnitTests/TestCommandLineWrapper.cs

DOTNET-5136
Currently we are setting the AWS credentials as environment variables for every command line process. This PR aims to mitigate that by only setting the credentials for processes that require it.
The following processes need AWS credentials:
1. Docker Login Command - This command needs the credentials to generate authorization tokens which are passed as `--username` and `--password` arguments. These tokens are generate by calling the appropriate API using the ECR service client - [proof](https://github.com/aws/aws-dotnet-deploy/blob/main/src/AWS.Deploy.Orchestration/Data/AWSResourceQueryer.cs#L206)
2. CDK Bootstrap command - The credentials need to be passed as environment variables.
3. CDK deploy command - The credentials need …

fix: Only set AWS credentials for processes that require it

---

src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalk.recipe
test/AWS.Deploy.CLI.Common.UnitTests/Recipes/Validation/ElasticBeanStalkOptionSettingItemValidationTests.cs

* Fixed regex validation to make the account ID as optional in Elastic Beanstalk platformArn.
* Included valid regions in the test-cases.
The above image shows all the default settings when performing a deployment with an Elastic Beanstalk recipe. As seen, the platform ARN does not contain the account-ID
The regex has been inferred from this [doc](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/AWSHowTo.iam.policies.arn.html)

fix: Update EBS platformArn regex validation to make the account ID as optional

---

src/AWS.Deploy.ServerMode.Client/ServerModeHttpClient.cs

IDE-5162
Fix for the error:
"'DateTimeInvalidLocalFormat' : 'A UTC DateTime is being converted to text in a format that is only correct for local times. This can happen when calling DateTime.ToString using the 'z' format specifier, which will include a local time zone offset in the output. In that case, either use the 'Z' format specifier, which designates a UTC time, or use the 'o' format string, which is the recommended way to persist a DateTime in text. This can also occur when passing a DateTime to be serialized by XmlConvert or DataSet. If using XmlConvert.ToString, pass in XmlDateTimeSerializationMode.RoundtripKind to serialize correctly. If using DataSet, set the DateTimeMode on the DataColumn object to DataSetDateTime.Utc. '"
By …

fix: fix invalid date format exception thrown from VS Toolkit

---

src/AWS.Deploy.Orchestration/CdkAppSettingsSerializer.cs
src/AWS.Deploy.Orchestration/CdkProjectHandler.cs
src/AWS.Deploy.Recipes.CDK.Common/RecipeConfiguration.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppEcsFargate/.template.config/template.json
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppEcsFargate/Program.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/.template.config/template.json
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Program.cs
src/AWS.Deploy.Recipes/CdkTemplates/BlazorWasm/.template.config/template.json
src/AWS.Deploy.Recipes/CdkTemplates/BlazorWasm/Program.cs
src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateScheduleTask/.template.config/template.json
src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateScheduleTask/Program.cs
src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateService/.template.config/template.json
src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateService/Program.cs

`5137`
This PR injects the account ID and region values in the generated CDK project using the RecipeConfiguration

fix: Use RecipeConfiguration to inject values for account ID and region in the generated CDK project.

---

src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
src/AWS.Deploy.CLI/ServerMode/Models/GetOptionSettingsOutput.cs
src/AWS.Deploy.CLI/ServerMode/Models/OptionSettingItemSummary.cs
src/AWS.Deploy.ServerMode.Client/RestAPI.cs
src/AWS.Deploy.ServerMode.ClientGenerator/AWS.Deploy.ServerMode.ClientGenerator.csproj

IDE-5165
feat: add GetConfigSettings API to retrieve Option Setting Items in Server Mode

feat: add GetConfigSettings API to retrieve Option Setting Items in Server Mode

---

src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
src/AWS.Deploy.CLI/ServerMode/Models/ApplyConfigSettingsInput.cs
src/AWS.Deploy.CLI/ServerMode/Models/ApplyConfigSettingsOutput.cs
src/AWS.Deploy.ServerMode.Client/RestAPI.cs

Added SetConfigSettings that takes a list of updated settings and applies them. If there is an error setting any of them, a list of errors is returned.

feat: add SetConfigSettings API to set configuration settings

---

src/AWS.Deploy.CLI/Commands/CommandFactory.cs
src/AWS.Deploy.CLI/Commands/CommandHandlerInput/DeployCommandHandlerInput.cs
src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.Orchestration/Orchestrator.cs
src/AWS.Deploy.Orchestration/OrchestratorSession.cs

DOTNET-5244
This PR refactors the `deploy` command to make it more modular so that there is a better separation of responsibilities. 
The `deploy` command is divided into 5 components:
1. `InitializeDeployment` - Initiates a deployment or a re-deployment by selected the desired deployment recipe.
2. `EvaluateSystemCapabilities` - Checks if the system meets all the necessary requirements for deployment.
3. `ConfigureDeployment` - Provides the ability to configure option settings using the CLI or a user provided configurations file.
4. `CreateDeploymentBundle` - Creates the deployment bundle and sets the appropriate metadata in the deployment bundle definition.
5. `DeployRecommendation` - Creates the CDK project and executes the CDK command …

chore: Refactor the Deploy command 

---

src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.CLI/Commands/TypeHints/DockerBuildArgsCommand.cs
src/AWS.Deploy.CLI/Commands/TypeHints/DockerExecutionDirectoryCommand.cs
src/AWS.Deploy.CLI/Commands/TypeHints/DotnetPublishArgsCommand.cs
src/AWS.Deploy.CLI/ConsoleUtilities.cs
src/AWS.Deploy.Constants/CLI.cs

DOTNET-5193
This PR fixes the misleading language in user input prompt to deploy to a new or an existing Cloudformation stack.

fix: Fix misleading language in user input prompt to deploy to a new or an existing Cloudformation stack

---

src/AWS.Deploy.Orchestration/DeploymentBundleHandler.cs

While recently setting up a CodeBuild jobs I was running into a lot of Docker build issues. It would have greatly helped my debugging effort if I knew for sure what exactly was the Docker execution directory was in CodeBuild. Added logging messages to better help debugging efforts in the future.

feat: Add logging messages to show what docker build command and from what directory the build will happen

---

src/AWS.Deploy.CLI/Commands/CommandFactory.cs
src/AWS.Deploy.CLI/Commands/CommandHandlerInput/GenerateDeploymentProjectCommandHandlerInput.cs
src/AWS.Deploy.CLI/Commands/GenerateDeploymentProjectCommand.cs
src/AWS.Deploy.CLI/Exceptions.cs
src/AWS.Deploy.Common/IO/DirectoryManager.cs
src/AWS.Deploy.Common/Recipes/RecipeDefinition.cs
src/AWS.Deploy.Common/Recipes/Validation/IDeployToolValidationContext.cs
src/AWS.Deploy.Orchestration/CdkProjectHandler.cs
src/AWS.Deploy.Orchestration/Exceptions.cs
src/AWS.Deploy.Orchestration/Orchestrator.cs
src/AWS.Deploy.Orchestration/OrchestratorSession.cs
src/AWS.Deploy.Orchestration/TemplateEngine.cs
src/AWS.Deploy.Recipes.CDK.Common/RecipeConfiguration.cs
test/AWS.Deploy.CLI.Common.UnitTests/IO/TestDirectoryManager.cs
test/AWS.Deploy.CLI.IntegrationTests/SaveCdkDeploymentProject/SaveCdkDeploymentProjectTests.cs

1. `DOTNET-5245`
2. `DOTNET-5246`
1. Add a new command that generate the CDK deployment project and saves it at a user-specified directory. 
2. Generate a deployment recipe snapshot that is taken at the time of the CDK deployment project generation.

feat: Create command to save the CDK deployment project

---

src/AWS.Deploy.Common/ProjectDefinitionParser.cs
test/AWS.Deploy.CLI.UnitTests/ProjectDefinitionParserTest.cs

Currently, in the deploy tool, if a **relative path** to the target application project directory is provided it results in a `ProjectFileNotFoundException`.
Example scenario:
* Current working directory - `C:\codebase\aws-dotnet-deploy`
* CLI command - `dotnet aws deploy --project-path ".\testapps\WebAppWithDockerFile"`
* Result - `ProjectFileNotFoundException`
This PR attempts to correct this behavior.

fix: Correctly resolve target project path

---

src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
src/AWS.Deploy.Common/Exceptions.cs
src/AWS.Deploy.Common/Recommendation.cs
src/AWS.Deploy.Orchestration/Exceptions.cs
src/AWS.Deploy.Orchestration/Orchestrator.cs
src/AWS.Deploy.Orchestration/RecommendationEngine/RecommendationEngine.cs
test/AWS.Deploy.CLI.UnitTests/DeploymentBundleHandlerTests.cs

IDE-5368
Reworked Recommendation to treat Deployment Bundle similar to OptionItemSettings and centralize access to them.

fix: deployment bundle settings are not handled in server mode

---

src/AWS.Deploy.CLI/CloudFormation/StackEventMonitor.cs
test/AWS.Deploy.CLI.IntegrationTests/BlazorWasmTests.cs
test/AWS.Deploy.CLI.IntegrationTests/ConfigFileDeployment/ECSFargateDeploymentTest.cs
test/AWS.Deploy.CLI.IntegrationTests/ConfigFileDeployment/ElasticBeanStalkDeploymentTest.cs
test/AWS.Deploy.CLI.IntegrationTests/ConsoleAppTests.cs
test/AWS.Deploy.CLI.IntegrationTests/ServerModeTests.cs
test/AWS.Deploy.CLI.IntegrationTests/WebAppNoDockerFileTests.cs
test/AWS.Deploy.CLI.IntegrationTests/WebAppWithDockerFileTests.cs

- Enabled parallel tests
- Changed the polling frequency to 2 seconds, 1 second easily throttles GetStack operation call.

test: enable parallel integ tests

---

src/AWS.Deploy.Orchestration/CdkProjectHandler.cs
src/AWS.Deploy.Orchestration/Exceptions.cs

IDE-5426
fix: cdk deploy failure does not throw an exception

fix: cdk deploy failure does not throw an exception

---

test/AWS.Deploy.CLI.IntegrationTests/ServerModeTests.cs

DOTNET-5299
Currently, the server mode tests have a 10 minute execution timeout, within which it is expected that the Cloudformation stack creation will be complete. However, depending on Cloudformation throttling, this process may be delayed and the tests can fail. 
This PR mitigates this problem by change the execution timeout to 15 minutes.

fix: Change execution timeout for server mode tests

---

test/AWS.Deploy.CLI.Common.UnitTests/ConfigFileDeployment/TestFiles/IntegrationTestFiles/ECSFargateConfigFile.json
test/AWS.Deploy.CLI.Common.UnitTests/ConfigFileDeployment/TestFiles/IntegrationTestFiles/ElasticBeanStalkConfigFile.json
test/AWS.Deploy.CLI.IntegrationTests/BlazorWasmTests.cs
test/AWS.Deploy.CLI.IntegrationTests/ConfigFileDeployment/ECSFargateDeploymentTest.cs
test/AWS.Deploy.CLI.IntegrationTests/ConfigFileDeployment/ElasticBeanStalkDeploymentTest.cs
test/AWS.Deploy.CLI.IntegrationTests/ConsoleAppTests.cs
test/AWS.Deploy.CLI.IntegrationTests/Helpers/ConfigFileHelper.cs
test/AWS.Deploy.CLI.IntegrationTests/ServerModeTests.cs
test/AWS.Deploy.CLI.IntegrationTests/WebAppNoDockerFileTests.cs
test/AWS.Deploy.CLI.IntegrationTests/WebAppWithDockerFileTests.cs

- Option setting values which are stdin are now unique by nature.
- 3 integ test runs passed that ensures there are no transient failures when tests are running in parallel
- Serial execute test cases which depends on same testapp otherwise dotnet cli used for packaging will trigger race condition.

fix: use unique identifiers for stdin values

---

.github/workflows/prepare-release.yml

Prepare Release workflow allows to create release PRs from the target branch. Typically target branch will be `dev`.
Final state of workflow: https://github.com/ganeshnj/aws-dotnet-deploy/actions/workflows/prepare-release.yml
Release PR samples
- https://github.com/ganeshnj/aws-dotnet-deploy/pull/35
- https://github.com/ganeshnj/aws-dotnet-deploy/pull/34

ci: add manual workflow to prepare release PRs

---

src/AWS.Deploy.Common/ProjectDefinitionParser.cs
src/AWS.Deploy.Orchestration/DeploymentBundleHandler.cs
test/AWS.Deploy.CLI.UnitTests/ProjectDefinitionParserTest.cs
test/AWS.Deploy.CLI.UnitTests/Utilities/System.IO.Utilties.cs

This PR correctly resolves the Solution path while parsing the project definition on non-Windows targets.

fix: Correctly resolve the Solution path on non-Windows targets

---

src/AWS.Deploy.CLI/CloudFormation/StackEventMonitor.cs
src/AWS.Deploy.CLI/Commands/DeleteDeploymentCommand.cs
test/AWS.Deploy.CLI.Common.UnitTests/Services/InMemoryInteractiveService.cs
test/AWS.Deploy.CLI.IntegrationTests/Services/InMemoryInteractiveServiceTests.cs

This change also change polling period to 5 seconds for both DeleteDeploymentCommand and StackEventMonitor

fix: replace ErrorCode with Throttling

---

src/AWS.Deploy.CLI/Commands/CommandFactory.cs
src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.CLI/Commands/GenerateDeploymentProjectCommand.cs
src/AWS.Deploy.CLI/Extensions/CustomServiceCollectionExtension.cs
src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
src/AWS.Deploy.Common/IO/DirectoryManager.cs
src/AWS.Deploy.Constants/CDK.cs
src/AWS.Deploy.Orchestration/CDK/CDKVersionDetector.cs
src/AWS.Deploy.Orchestration/CdkProjectHandler.cs
src/AWS.Deploy.Orchestration/Orchestrator.cs
test/AWS.Deploy.CLI.Common.UnitTests/IO/TestDirectoryManager.cs
test/AWS.Deploy.CLI.IntegrationTests/SaveCdkDeploymentProject/RecommendationTests.cs
test/AWS.Deploy.Orchestration.UnitTests/AWS.Deploy.Orchestration.UnitTests.csproj
test/AWS.Deploy.Orchestration.UnitTests/CDK/CDKVersionDetectorTests.cs
test/AWS.Deploy.Orchestration.UnitTests/CDK/CSProjFiles/MixedReferences.csproj
test/AWS.Deploy.Orchestration.UnitTests/CDK/CSProjFiles/NoReferences.csproj
test/AWS.Deploy.Orchestration.UnitTests/CDK/CSProjFiles/SameReferences.csproj
test/AWS.Deploy.Orchestration.UnitTests/TestDirectoryManager.cs

Currently, Deployment Tool uses static CDK version which needs to be changed as Amazon.CDK.* package references are updated. This change allows Deployment Tool to detect the minimum compatible version of Amazon.CDK.* dependency which must be installed or will be installed by the tool.

feat: detect CDK version by parsing deployment project csproj file

---

src/AWS.Deploy.Common/SerializeModelContractResolver.cs
test/AWS.Deploy.CLI.IntegrationTests/SaveCdkDeploymentProject/SaveCdkDeploymentProjectTests.cs

Fix issue with TypeHintData not being serialized correctly when saving CDK project
Also reformatted the `SerializeModelContractResolver` to make it easier to debug. The issue was TypeHintData is an IDictionary so you can't simply cast it to IEnumerable<object>.

Fix issue with TypeHintData not being serialized correctly when saving CDK project

---

src/AWS.Deploy.CLI/Commands/ServerModeCommand.cs
src/AWS.Deploy.CLI/ServerMode/AwsCredentialsAuthenticationHandler.cs
src/AWS.Deploy.CLI/ServerMode/Services/AesEncryptionProvider.cs
src/AWS.Deploy.CLI/ServerMode/Services/IEncryptionProvider.cs
src/AWS.Deploy.CLI/ServerMode/Services/NoEncryptionProvider.cs
src/AWS.Deploy.ServerMode.Client/ServerModeHttpClient.cs
src/AWS.Deploy.ServerMode.Client/ServerModeSession.cs

IDE-5677
Pentest recommendations:
* Remove the IV from being specified when the server is first created.
* Generate a new IV for each request, every time a new encryption operation is being performed.
* This value does not need to be secret, but it does need to be unpredictable and unique.
* Include the IV alongside the ciphertext in each request, so it can be used to decrypt the message when used with the correct key.

fix: reusing AES IV could cause potential security risks

---

src/AWS.Deploy.CLI/AWSUtilities.cs
src/AWS.Deploy.CLI/Commands/CommandFactory.cs
src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.CLI/Commands/TypeHints/DockerExecutionDirectoryCommand.cs
src/AWS.Deploy.CLI/Commands/TypeHints/TypeHintCommandFactory.cs
src/AWS.Deploy.CLI/ConsoleUtilities.cs
src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
src/AWS.Deploy.CLI/Utilities/AssumeRoleMfaTokenCodeCallback.cs
src/AWS.Deploy.Common/IO/DirectoryManager.cs
src/AWS.Deploy.Common/IO/FileManager.cs
src/AWS.Deploy.Common/Utilities/PathUtilities.cs
src/AWS.Deploy.DockerEngine/DockerEngine.cs
src/AWS.Deploy.Orchestration/Orchestrator.cs
src/AWS.Deploy.Orchestration/Utilities/ZipFileManager.cs
test/AWS.Deploy.CLI.UnitTests/ConsoleUtilitiesTests.cs
test/AWS.Deploy.CLI.UnitTests/DockerTests.cs
test/AWS.Deploy.CLI.UnitTests/RecommendationTests.cs

IDE-5678
Pentest recommendation:
Disallow SMB shares from being considered valid file paths by default.
If SMB shares are required, consider allowing specific servers to be explicitly allowed in a configuration file, and deny all other file paths.

fix: disallow SMB shares from file paths

---

src/AWS.Deploy.CLI/Utilities/CommandLineWrapper.cs
src/AWS.Deploy.Orchestration/CustomRecipeLocator.cs

During startup the tool looks to see if current directory is inside a git repo. It does this by shelling out the command `git status`. Because we just care about the exit code we redirect the IO to hide the console window but ignore the stdout. If the the `git status` command returns a lot of data it can fill up the std out buffer used by the process freezing the program.
The fix was to make sure we always read stdout and stderror so we don't fill up the buffer but only write back to the console if the `streamOutputToInteractiveService` flag was set.
Also calling `git status` is heavy weight for just checking if in a git repo because it forces git to check the status of the repo which could be slow for large repos. I changed the command to `git worktree list`. It …

fix: Startup freezing when started from a project that has a large "git status" response.

---

src/AWS.Deploy.CLI/ServerMode/Controllers/RecipeController.cs
src/AWS.Deploy.Orchestration/RecipeHandler.cs
test/AWS.Deploy.CLI.UnitTests/ServerModeTests.cs

Fix issue with the GetRecipe REST API from server mode that was not using custom recipe location paths to search for recipes.

fix: Server-mode GetRecipe API supports finding recipes for custom deployment project recipe ids.

---

src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
src/AWS.Deploy.Common/Recommendation.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppAppRunner.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppECSFargate.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalk.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateScheduleTask.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateService.recipe
test/AWS.Deploy.CLI.UnitTests/RecommendationTests.cs

Currently in the deploy tool we are prefixing the default values for certain parameter (ECS Service name, Elastic Beanstalk Environment etc..) with the `ProjectName`. However, the `ProjectName` is not unique because we use the same project for multiple integration tests. This is causing an issue while deletion of stacks because the Cloudformation resources are shared between multiple stacks. 
In order to avoid this issue, we are replacing the `ProjectName` prefix is replaced with the `StackName`, which is unique per test. As a result, all Cloudformation resources created by a test are exclusive to the stack that it created
The same is also extended to the server mode.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

fix: Replace default values for option setting items with stack name as prefix

---

src/AWS.Deploy.ServerMode.Client/RestAPI.cs

Last release 0.22.8 was missing regeneration of the `AWS.Deploy.ServerMode.Client`. This PR is just regenerating for the changes.

fix: Regen server mode client for missing changes in last release

---

src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
src/AWS.Deploy.CLI/ServerMode/Models/ExistingDeploymentSummary.cs
src/AWS.Deploy.CLI/ServerMode/Models/RecommendationSummary.cs
src/AWS.Deploy.ServerMode.Client/RestAPI.cs
test/AWS.Deploy.CLI.IntegrationTests/ServerModeTests.cs

Currently VS is making `GetRecipe` API calls for each item returned in the `GetRecommendations` and `GetExistingDeployments` APIs. This PR adds the missing metadata VS needs from GetRecipe to the list operations so everything can be retrieved in one API call.

feat: Add more metadata to the ServerMode APIs

---

src/AWS.Deploy.DockerEngine/Templates/Dockerfile.template

The Docker template used when containerizing applications was installing Node 10 but 10 is deprecated. This updates to the latest Node LTS which is 14.

feat: Update Docker template to use Node.js 14 instead of 10 which is deprecated

---

src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppAppRunner/AspNetAppAppRunner.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppEcsFargate/AspNetAppEcsFargate.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/AspNetAppElasticBeanstalkLinux.csproj
src/AWS.Deploy.Recipes/CdkTemplates/BlazorWasm/BlazorWasm.csproj
src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateScheduleTask/ConsoleAppECSFargateScheduleTask.csproj
src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateService/ConsoleAppECSFargateService.csproj

Update all CDK references to the current version of the CDK 128.
Besides getting latest features I also suspect some of the reason for integ test failures is we had a mix of CDK versions being referenced and when those tests were being run in parallel it caused CDK to complain about downgrading.

feat: Update all CDK references to version 128

---

src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Configurations/Configuration.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Recipe.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalk.recipe

DOTNET-4806
Add AWS X-Ray Tracing support to beanstalk deployments

feat: Add AWS X-Ray Tracing support to beanstalk deployments

---

src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Configurations/Configuration.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Recipe.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalk.recipe

DOTNET-4805
Added Reverse Proxy configuration for Beanstalk deployments.

feat: Add ability to set Reverse Proxy in Beanstalk deployment

---

src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Configurations/Configuration.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Recipe.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalk.recipe

DOTNET-4807
add enhanced health reporting setting to beanstalk deployments
add recipe validator because disabling enhanced health reporting is not compatible with enabled managed platform updates

feat: add enhanced health reporting setting to beanstalk deployments

---

src/AWS.Deploy.Common/Recipes/OptionSettingTypeHint.cs
src/AWS.Deploy.Common/Recipes/Validation/OptionSettingItemValidators/RangeValidator.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Configurations/Configuration.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Configurations/ElasticBeanstalkRollingUpdatesConfiguration.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Recipe.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalk.recipe
test/AWS.Deploy.CLI.Common.UnitTests/Recipes/Validation/ElasticBeanStalkOptionSettingItemValidationTests.cs

DOTNET-4810
add rolling updates configuration to beanstalk deployments
add new validator that allows null and empty values for int types. We need this because "MaxBatchSize" and "MinInstancesInService" have default values that are calculated dynamically in beanstalk and cannot be specified in the recipe.

feat: add rolling updates configuration to beanstalk deployments

---

src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Configurations/Configuration.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Recipe.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalk.recipe

DOTNET-5559
Add CName Prefix setting to beanstalk deployments
Note: Validation for CName PRefix availability needs to be added when this issue is done DOTNET-5572

feat: Add CName Prefix setting to beanstalk deployments

---

src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.CLI/ConsoleUtilities.cs
src/AWS.Deploy.Common/Recipes/OptionSettingItem.ValueOverride.cs
src/AWS.Deploy.Common/Recipes/OptionSettingValueType.cs
src/AWS.Deploy.Common/Recommendation.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Configurations/Configuration.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Recipe.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalk.recipe
test/AWS.Deploy.CLI.Common.UnitTests/ConfigFileDeployment/ElasticBeanStalkKeyValueDeploymentTest.cs
test/AWS.Deploy.CLI.Common.UnitTests/ConfigFileDeployment/TestFiles/UnitTestFiles/ElasticBeanStalkKeyPairConfigFile.json

DOTNET-4809
add environment variables config to beanstalk deployments
Introduce new KeyValue type that supports a Dictionary.
The KeyValue type is Dictionary that serializes the same way as Object types are defined in config files that users can deploy from. This makes it harder to distinguish between an Object and a Dictionary.
In the image above, one is an Object and the other is a Dictionary. For this reason, I have updated the GetOptionSetting method to check if the OptionSettingItem is a KeyValue type to return it.
Updated UX to ask user for key value pairs with ability to Add, Update and Delete
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …

feat: add environment variables config to beanstalk deployments

---

src/AWS.Deploy.CLI/Commands/TypeHints/DynamoDBTableCommand.cs
src/AWS.Deploy.CLI/Commands/TypeHints/InstanceTypeCommand.cs
src/AWS.Deploy.CLI/Commands/TypeHints/S3BucketNameCommand.cs
src/AWS.Deploy.CLI/Commands/TypeHints/SNSTopicArnsCommand.cs
src/AWS.Deploy.CLI/Commands/TypeHints/SQSQueueUrlCommand.cs
src/AWS.Deploy.CLI/Commands/TypeHints/TypeHintCommandFactory.cs
src/AWS.Deploy.Common/Recipes/OptionSettingTypeHint.cs
src/AWS.Deploy.Common/TypeHintData/DynamoDBTableTypeHintData.cs
src/AWS.Deploy.Common/TypeHintData/S3BucketNameTypeHintData.cs
src/AWS.Deploy.Common/TypeHintData/SNSTopicArnsTypeHintData.cs
src/AWS.Deploy.Common/TypeHintData/SQSQueueUrlTypeHintData.cs
src/AWS.Deploy.Orchestration/Data/AWSResourceQueryer.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppAppRunner.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppECSFargate.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalk.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/BlazorWasm.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateScheduleTask.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateService.recipe
test/AWS.Deploy.CLI.IntegrationTests/Utilities/TestToolAWSResourceQueryer.cs
test/AWS.Deploy.CLI.UnitTests/Utilities/TestToolAWSResourceQueryer.cs

DOTNET-5570
* Add type hints on child settings to enable visual studio toolkit to query the child typehint and return the resources that can be selected. The CLI will still use the parent type hint to display the Object type. The toolkit can decide to use either.
* Added Typehint data for S3BucketName, DynamoDbTable, SNSTopicArns and SQSQueueUrl to choose whether the typehint list allows empty values or not.
* Added a filtering mechanism to retrieve instance types

feat: Add type hints on child settings

---

src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.Common/Recipes/Validation/IRecipeValidator.cs
src/AWS.Deploy.Common/Recipes/Validation/RecipeValidatorList.cs
src/AWS.Deploy.Common/Recipes/Validation/RecipeValidators/FargateTaskCpuMemorySizeValidator.cs
src/AWS.Deploy.Common/Recipes/Validation/RecipeValidators/MinMaxConstraintValidator.cs
src/AWS.Deploy.Common/Recipes/Validation/ValidatorFactory.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppECSFargate.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateService.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/aws-deploy-recipe-schema.json
test/AWS.Deploy.CLI.Common.UnitTests/Recipes/Validation/ECSFargateOptionSettingItemValidationTests.cs

DOTNET-5572
This PR adds input validation to option setting items in ECS Fargate based recipes.
This PR also adds a new recipe level validator called `MinMaxConstraintValidator`. It enforces a constraint that the value for one option setting item is less than another option setting item.

feat: Add input validation to option settings in ECS Fargate based recipes

---

src/AWS.Deploy.ServerMode.Client/ServerModeSession.cs

https://sim.amazon.com/issues/DOTNET-5571
Currently, the `server-mode` command fails if the deploy-tool installation location contains an empty space.
This PR solves this problem by surrounding the installation location with quotes (`"`)

fix: Allow spaces in the deploy tool installation location in server-mode command.

---

src/AWS.Deploy.CLI/Commands/TypeHints/BeanstalkEnvironmentCommand.cs
src/AWS.Deploy.CLI/TypeHintResponses/BeanstalkEnvironmentTypeHintResponse.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Configurations/BeanstalkEnvironmentConfiguration.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Configurations/Configuration.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Recipe.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalk.recipe
test/AWS.Deploy.CLI.Common.UnitTests/ConfigFileDeployment/ElasticBeanStalkDeploymentTest.cs
test/AWS.Deploy.CLI.Common.UnitTests/ConfigFileDeployment/ElasticBeanStalkKeyValueDeploymentTest.cs
test/AWS.Deploy.CLI.Common.UnitTests/ConfigFileDeployment/TestFiles/UnitTestFiles/ElasticBeanStalkConfigFile.json
test/AWS.Deploy.CLI.Common.UnitTests/ConfigFileDeployment/TestFiles/UnitTestFiles/ElasticBeanStalkKeyPairConfigFile.json
test/AWS.Deploy.CLI.UnitTests/RecommendationTests.cs
testapps/WebAppNoDockerFile/ElasticBeanStalkConfigFile.json

**Description of changes:**
The PR does the following:
* Change Elastic Beanstalk environment to be a complex object. This adds a `CreateNew` child option setting which can be used in the CDK application to determine if a new environment needs to be provisioned.
* Adds a clear error message when a user tries to perform a deployment to an existing Beanstalk environment via a new CloudFormation stack.
**Steps to reproduce the error**
* Perform the first deployment with the following configuration
```
{
Recipe: ASP.NET Core App to AWS Elastic Beanstalk on Linux,
StackName: MyAppStack1
ApplicationName: MyAppStack1-app
EnvironmentName: MyAppStack1-dev
}
```
* Perform the second deployment with the following configuration
```
{
Recipe: ASP.NET Core App to AWS Elastic Beanstalk on Linux, …
```

fix: Improve error message when deploying to an existing Beanstalk environment via a new CF stack

---

src/AWS.Deploy.Common/Recommendation.cs

DOTNET-5619
The Deployment Bundle settings are stored as a private property on the Recommendation class. This property is set when a Recommendation is instantiated. When we are doing a redeployment, we apply previous settings which involve doing a deep copy of the Recommendation object. The way we do the deep copy is via serialization/deserialization which is only including public properties. I changed the deployment bundle settings property to public to include it in the deep copy.

fix: deployment bundle settings not appearing for redeployment

---

src/AWS.Deploy.CLI/Commands/TypeHints/InstanceTypeCommand.cs
src/AWS.Deploy.ServerMode.Client/ServerModeSession.cs

DOTNET-5622
Added ability to attach to running server mode to simplify debugging
Fixed bug with InstanceType type hint that was returning a 500 error in server mode due to sorting a list incorrectly.
Previously, using linq, we were converting the Instance types into a TypeHintResource and then doing an OrderBy. This was failing because we dont have a comparator for TypeHintResource. To fix this, I simply did the OrderBy before creating the TypeHintResource.

fix: InstanceType hint returns 500 in server mode

---

src/AWS.Deploy.Common/Recipes/OptionSettingItem.ValueOverride.cs
src/AWS.Deploy.Common/Recommendation.cs
test/AWS.Deploy.CLI.UnitTests/RecommendationTests.cs
test/AWS.Deploy.CLI.UnitTests/SetOptionSettingTests.cs

IDE-6536
Trying to set ElasticBeanstalkEnvironmentVariables which is of type KeyValue via server mode fails. The way we are we are handling the KeyValue type set via config files is not working with server mode. removing the code specific to config files works for both features.
In addition, when setting the KeyValue type, the values are not sticking because they are being handle as string instead of Dictionary. Additional handling was added to cover this case.

fix: KeyValue types not working with server mode

---

src/AWS.Deploy.CLI/AWS.Deploy.CLI.csproj
src/AWS.Deploy.Common/Exceptions.cs
src/AWS.Deploy.Orchestration/AWS.Deploy.Orchestration.csproj
src/AWS.Deploy.Orchestration/CdkProjectHandler.cs
src/AWS.Deploy.Orchestration/Data/AWSResourceQueryer.cs
src/AWS.Deploy.Orchestration/Orchestrator.cs
test/AWS.Deploy.CLI.IntegrationTests/Utilities/TestToolAWSResourceQueryer.cs
test/AWS.Deploy.CLI.UnitTests/Utilities/TestToolAWSResourceQueryer.cs

DOTNET-5575
Based on the metrics gathered around the deploy tool usage, customers are experiencing deployment failures when they get to the `cdk deploy` stage. This part aims to break down the CDK deploy failures to have a better understanding of the customer's issues with the deploy tool.
This PR adds the ability to query CloudFormation to get the events of the deployment for a given stack. After we finish deploying to cdk (whether success or failure), we check the CloudFormation events for `CREATE_FAILED` or `UPDATE_FAILED` events. If they exist, we throw an exception with the error message of those events.
There is another part to this story where `cdk deploy` fails before creating a stack where we have to scrape the output text to …

feat: Improve telemetry by capturing CDK deployment failure message

---

src/AWS.Deploy.CLI/Commands/CommandFactory.cs
src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.CLI/Extensions/CustomServiceCollectionExtension.cs
src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
src/AWS.Deploy.Common/CloudApplication.cs
src/AWS.Deploy.Common/Exceptions.cs
src/AWS.Deploy.Common/IO/FileManager.cs
src/AWS.Deploy.Constants/AWS.Deploy.Constants.projitems
src/AWS.Deploy.Constants/ElasticBeanstalk.cs
src/AWS.Deploy.Orchestration/Data/AWSResourceQueryer.cs
src/AWS.Deploy.Orchestration/DeploymentCommands/BeanstalkEnvironmentDeploymentCommand.cs
src/AWS.Deploy.Orchestration/DeploymentCommands/DeploymentCommandFactory.cs
src/AWS.Deploy.Orchestration/Exceptions.cs
src/AWS.Deploy.Orchestration/Orchestrator.cs
src/AWS.Deploy.Orchestration/ServiceHandlers/AWSElasticBeanstalkHandler.cs
src/AWS.Deploy.Orchestration/ServiceHandlers/AWSS3Handler.cs
src/AWS.Deploy.Orchestration/ServiceHandlers/AWSServiceHandler.cs
src/AWS.Deploy.Orchestration/Utilities/DeployedApplicationQueryer.cs
test/AWS.Deploy.CLI.Common.UnitTests/IO/TestFileManager.cs
test/AWS.Deploy.CLI.IntegrationTests/SaveCdkDeploymentProject/RecommendationTests.cs
test/AWS.Deploy.CLI.IntegrationTests/Utilities/TestToolAWSResourceQueryer.cs
test/AWS.Deploy.CLI.UnitTests/Utilities/TestToolAWSResourceQueryer.cs
test/AWS.Deploy.Orchestration.UnitTests/DeployedApplicationQueryerTests.cs
test/AWS.Deploy.Orchestration.UnitTests/ElasticBeanstalkHandlerTests.cs
test/AWS.Deploy.Orchestration.UnitTests/TestFileManager.cs

**Note** - The CI pipeline is not automatically run when trying to merge a PR into a staging branch. I manually triggered the aws-dotnet-deploy-ci CodeBuild job and it ran successfully (build 223 and 227).
DOTNET-5510
This PR supports the CLI workflow to deploy to an existing Elastic Beanstalk environment. **It does not update server mode**

feat: Support Elastic Beanstalk backwards compatibility via the CLI

---

src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
src/AWS.Deploy.CLI/ServerMode/ExtensionMethods.cs
src/AWS.Deploy.CLI/ServerMode/Startup.cs
src/AWS.Deploy.Common/Exceptions.cs
src/AWS.Deploy.Common/Recommendation.cs
src/AWS.Deploy.Constants/CLI.cs
src/AWS.Deploy.Orchestration/Data/AWSResourceQueryer.cs
src/AWS.Deploy.Orchestration/Exceptions.cs
src/AWS.Deploy.Orchestration/Orchestrator.cs

DOTNET-5654
* When recommendations are instantiated, all the recipe default values are check to create an inventory of the replacements needed.
* After a user selects the recommendation, a call is made to the orchestrator to do the token replacements if the recommendation has the replacement token in its inventory.
* When a user selects a beanstalk recommendation, if they are in a region that does not support beanstalk, the .net stack platform call will return empty which will throw an expected deploy tool exception instead of a generic one. The error message has been improved.
* In server mode, exceptions thrown in APIs now correctly return the error messages and error codes to the caller instead of having an empty body.
By submitting …

fix: beanstalk error at startup when in non-default regions

---

src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
src/AWS.Deploy.CLI/ServerMode/Exceptions.cs
src/AWS.Deploy.CLI/ServerMode/Models/DeploymentTypes.cs
src/AWS.Deploy.CLI/ServerMode/Models/ExistingDeploymentSummary.cs
src/AWS.Deploy.CLI/ServerMode/Models/RecommendationSummary.cs
src/AWS.Deploy.CLI/ServerMode/Models/SetDeploymentTargetInput.cs
src/AWS.Deploy.ServerMode.Client/RestAPI.cs
test/AWS.Deploy.CLI.IntegrationTests/ServerModeTests.cs
test/AWS.Deploy.CLI.UnitTests/ServerModeTests.cs

DOTNET-5510
This PR supports the server-mode workflow to deploy to an existing Elastic Beanstalk environment.
Verified that this PR works as intended by deployment to an existing Beanstalk Environment via server-mode.

feat: Support Elastic Beanstalk backwards compatibility via server-mode

---

src/AWS.Deploy.CLI/Commands/CommandFactory.cs
src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
src/AWS.Deploy.Common/DefaultAWSClientFactory.cs
src/AWS.Deploy.Common/Exceptions.cs
src/AWS.Deploy.Common/IAWSClientFactory.cs
src/AWS.Deploy.Constants/CLI.cs
src/AWS.Deploy.Orchestration/Data/AWSResourceQueryer.cs
src/AWS.Deploy.Orchestration/Exceptions.cs
test/AWS.Deploy.CLI.IntegrationTests/Utilities/TestToolAWSResourceQueryer.cs
test/AWS.Deploy.CLI.UnitTests/TestAWSClientFactory.cs
test/AWS.Deploy.CLI.UnitTests/TypeHintTests.cs
test/AWS.Deploy.CLI.UnitTests/Utilities/TestToolAWSResourceQueryer.cs
test/AWS.Deploy.Orchestration.UnitTests/AWSResourceQueryerTests.cs

DOTNET-5640
Update existing GetCallerIdentity call at Command startup which checks if a region is reachable. If it is not, we retrieve the region partition. If it is in the commercial partition, we do another GetCallerIdentity call to us-east-1(default region). If that succeeds, we conclude that the user is in an opt-in region and needs to enable it.

feat: add check for opt-in regions

---

src/AWS.Deploy.ServerMode.Client/CommandLineWrapper.cs
src/AWS.Deploy.ServerMode.Client/ServerModeSession.cs
src/AWS.Deploy.ServerMode.Client/Utilities/CappedStringBuilder.cs
test/AWS.Deploy.ServerMode.Client.UnitTests/CappedStringBuilderTests.cs
test/AWS.Deploy.ServerMode.Client.UnitTests/ServerModeSessionTests.cs

DOTNET-5204
Redirected standard error in server mode session to capture any error thrown in startup.
In the case where the deploy tool is not installed, server mode session throws an error but does not return the message indicating that the deploy tool is not installed. This change makes it so that errors are returned.

feat: capture standard error in server mode session

---

src/AWS.Deploy.CLI/Commands/CommandFactory.cs
src/AWS.Deploy.CLI/Commands/CommandHandlerInput/DeleteCommandHandlerInput.cs
src/AWS.Deploy.CLI/Commands/DeleteDeploymentCommand.cs
test/AWS.Deploy.CLI.IntegrationTests/WebAppNoDockerFileTests.cs

* https://github.com/aws/aws-dotnet-deploy/issues/404
* DOTNET-5646
This PR adds the support `--silent` flag to the `delete-deployment` command to enable deletions without any user prompts.
**Command Syntax** : `dotnet aws delete-deployment <CloudApplicationName> --silent`
Updated `WebAppNoDockerFileTests` to use the `--silent` flag during stack deletion.

feat: Add support for --silent flag in the delete-deployment command

---

src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
test/AWS.Deploy.CLI.IntegrationTests/BeanstalkBackwardsCompatibilityTests/CLITests.cs
test/AWS.Deploy.CLI.IntegrationTests/BeanstalkBackwardsCompatibilityTests/ServerModeTests.cs
test/AWS.Deploy.CLI.IntegrationTests/BeanstalkBackwardsCompatibilityTests/TestContextFixture.cs
test/AWS.Deploy.CLI.IntegrationTests/BeanstalkBackwardsCompatibilityTests/TestContextFixtureCollection.cs
test/AWS.Deploy.CLI.IntegrationTests/Helpers/ElasticBeanstalkHelper.cs
test/AWS.Deploy.CLI.IntegrationTests/Helpers/IAMHelper.cs
test/AWS.Deploy.CLI.IntegrationTests/ServerModeTests.cs

This PR addresses a bug fix where `ResourceType` was being set to `null` during re-deployments via server mode.
This PR also includes integration tests for Elastic Beanstalk backwards compatibility via CLI and the server mode.

fix: Correctly set deployment ResourceType during re-deployments via server mode

---

src/AWS.Deploy.CLI/Commands/TypeHints/ECRRepositoryCommand.cs
src/AWS.Deploy.CLI/Commands/TypeHints/TypeHintCommandFactory.cs
src/AWS.Deploy.Common/Exceptions.cs
src/AWS.Deploy.Common/Recipes/OptionSettingTypeHint.cs
src/AWS.Deploy.Common/Recommendation.cs
src/AWS.Deploy.Constants/CLI.cs
src/AWS.Deploy.Constants/RecipeIdentifier.cs
src/AWS.Deploy.Orchestration/Data/AWSResourceQueryer.cs
src/AWS.Deploy.Orchestration/DeploymentBundleHandler.cs
src/AWS.Deploy.Orchestration/Orchestrator.cs
src/AWS.Deploy.Recipes/DeploymentBundleDefinitions/Container.deploymentbundle
test/AWS.Deploy.CLI.Common.UnitTests/Recipes/Validation/ECSFargateOptionSettingItemValidationTests.cs
test/AWS.Deploy.CLI.UnitTests/DeploymentBundleHandlerTests.cs

This PR makes the ECR repository name configurable in container based deployment recipes. It does so by making the ECR repository name a part of the deployment bundle settings. This option setting is backed by the `ECRRepositoryCommand` type hint that gives users the ability to create a new repository or select  an existing one.

feat: Make ECR repository name configurable in container based deployments

---

src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppAppRunner.recipe

The visual studio toolkit is running into an issue while specifying the `create new` option for `ApplicationIAMRole`, `ServiceAccessIAMRole` and while **not** specifying a value for `EncryptionKmsKey`.
This PR mitigates this issue by setting `AllowEmptyString: true` in the `regex` validators for these option setting items.

fix: Allow empty strings for IAM roles and KMS keys in the AppRunner recipe

---

src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateService/Generated/Configurations/AutoScalingConfiguration.cs
test/AWS.Deploy.CLI.IntegrationTests/ConsoleAppTests.cs

The deploy tool fails to perform a redeployment using the `ConsoleAppEcsFargateService` recipe. This is because the child option settings inside the `AutoScalingConfiguration` do not have a default value in the CDK Templates. As a result, these option settings are set to `0` while apply the previous deployment settings ultimately causing the `range` validators to fail.
This PR fixes the above issue.

fix: Fix redeployment failure while using ConsoleAppEcsFargateService recipe

---

src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.Constants/CLI.cs

DOTNET-5711
This PR improves the CLI UX to support multiple deployment targets. It adds the ability to generate the input prompts for `CloudApplication` name by inspecting the deployment type of the recipe at run time.
**This PR establishes the following UX** _(Switch to a non-dark mode on the browser to view the flowchart clearly)_

feat: Improve the CLI UX to support multiple deployment targets

---

.github/workflows/BuildandTest.yml
AWS.Deploy.sln
src/AWS.Deploy.DockerEngine/DockerEngine.cs
src/AWS.Deploy.Orchestration/RecommendationEngine/MSProjectSdkAttributeTest.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateService.recipe
test/AWS.Deploy.CLI.UnitTests/DockerTests.cs
test/AWS.Deploy.CLI.UnitTests/RecommendationTests.cs
testapps/WorkerServiceExample/Program.cs
testapps/WorkerServiceExample/Worker.cs
testapps/WorkerServiceExample/WorkerServiceExample.csproj
testapps/WorkerServiceExample/WorkerServiceExample.sln
testapps/WorkerServiceExample/appsettings.Development.json
testapps/WorkerServiceExample/appsettings.json
testapps/docker/WorkerServiceExample/Program.cs
testapps/docker/WorkerServiceExample/ReferenceDockerfile
testapps/docker/WorkerServiceExample/Worker.cs
testapps/docker/WorkerServiceExample/WorkerServiceExample.csproj
testapps/docker/WorkerServiceExample/WorkerServiceExample.sln
testapps/docker/WorkerServiceExample/appsettings.Development.json
testapps/docker/WorkerServiceExample/appsettings.json

Add support for Worker project types being deploy as a ECS Fargate service. To distinguish a worker project type the csproj `Sdk` attribute is set to `Microsoft.NET.Sdk.Worker`. 
The new sdk typed caused a challenge with our existing rules for the recipe because we look for `Microsoft.NET.Sdk` and if the `OutputType` property is set to `Exe`. With `Microsoft.NET.Sdk.Worker` there is no `OutputType` property because it is inherited from the SDK. The rules got rewritten to have the initial priority be negative meaning exclude and then only include the recipe if either the rule for `Microsoft.NET.Sdk` and `Exe` was true or if `Microsoft.NET.Sdk.Worker` was true by setting the priority to a positive number.
By submitting this pull request, I confirm that you can use, …

feat: Add support for worker project types

---

src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.CLI/Commands/TypeHints/ExistingVpcConnectorCommand.cs
src/AWS.Deploy.CLI/Commands/TypeHints/TypeHintCommandFactory.cs
src/AWS.Deploy.CLI/ConsoleUtilities.cs
src/AWS.Deploy.Common/Extensions/GenericExtensions.cs
src/AWS.Deploy.Common/Recipes/OptionSettingItem.ValueOverride.cs
src/AWS.Deploy.Common/Recipes/OptionSettingTypeHint.cs
src/AWS.Deploy.Common/Recipes/OptionSettingValueType.cs
src/AWS.Deploy.Common/Recipes/Validation/OptionSettingItemValidators/RegexValidator.cs
src/AWS.Deploy.Common/UserDeploymentSettings.cs
src/AWS.Deploy.Orchestration/AWS.Deploy.Orchestration.csproj
src/AWS.Deploy.Orchestration/Data/AWSResourceQueryer.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppAppRunner/Generated/Configurations/Configuration.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppAppRunner/Generated/Configurations/VPCConnectorConfiguration.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppAppRunner/Generated/Recipe.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppAppRunner.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/aws-deploy-recipe-schema.json
test/AWS.Deploy.CLI.Common.UnitTests/ConfigFileDeployment/AppRunnerDeploymentTest.cs
test/AWS.Deploy.CLI.Common.UnitTests/ConfigFileDeployment/TestFiles/UnitTestFiles/AppRunnerConfigFile.json
test/AWS.Deploy.CLI.IntegrationTests/Utilities/TestToolAWSResourceQueryer.cs
test/AWS.Deploy.CLI.UnitTests/Constants.cs
test/AWS.Deploy.CLI.UnitTests/GetOptionSettingTests.cs
test/AWS.Deploy.CLI.UnitTests/Utilities/TestToolAWSResourceQueryer.cs

DOTNET-5710
* Add a List type as a supported option for Option Setting Items
* Added VPC Configuration Option Setting Item to App runner recipe, which allows you to specify a list of subnets and security groups that will allow App Runner to determine the proper VPC to use.
https://user-images.githubusercontent.com/53088140/158249532-0d9aa166-540b-463b-aad8-7aa39b36a392.mov

feat: Add List type and VPC Connector setting to App Runner

---

src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.Orchestration/SystemCapabilities.cs
src/AWS.Deploy.Orchestration/SystemCapabilityEvaluator.cs

DOTNET-5623
Removes the download URL from system capability messages. The URL is provided separately in the `InstallationUrl` property, which the CLI or Visual Studio can choose how to display separately.
Before, from the CLI when missing both Node.js and Docker:
```
Name the Cloud Application to deploy your project to
--------------------------------------------------------------------------------
Enter the name of the new CloudFormationStack stack (default ASPNetWebApp1):
The selected deployment uses the AWS CDK, which requires Node.js. The latest LTS version of Node.js is recommended and can be installed from https://nodejs.org/en/download/. Specifically, AWS CDK requires 10.13.0+ to work properly.
The selected deployment option …
```

fix: Remove duplicate URLs from system capability messages.

---

src/AWS.Deploy.Constants/CDK.cs
src/AWS.Deploy.Orchestration/CdkProjectHandler.cs
test/AWS.Deploy.Orchestration.UnitTests/CDK/CDKVersionDetectorTests.cs
test/AWS.Deploy.Orchestration.UnitTests/CDK/CSProjFiles/MixedReferences
test/AWS.Deploy.Orchestration.UnitTests/CDK/CSProjFiles/SameReferences

CDK bootstrap is using the globally installed version of CDK. This is problematic when there is a version mismatch between the global one and the minimum version needed for the deploy tool.

fix: cdk bootstrap using globally installed version of cdk

---

AWS.Deploy.sln
src/AWS.Deploy.Orchestration/CdkProjectHandler.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalk.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppExistingBeanstalkEnvironment.recipe
test/AWS.Deploy.CLI.UnitTests/RecommendationTests.cs
testapps/WebApiNET6/Program.cs
testapps/WebApiNET6/WebApiNET6.csproj
testapps/WebApiNET6/appsettings.Development.json
testapps/WebApiNET6/appsettings.json

Update Elastic Beanstalk recipe to support deploying .NET 6 applications now that Beanstalk has added support for .NET 6.

Add .NET 6 support for Elastic Beanstalk

---

src/AWS.Deploy.Orchestration/Utilities/CloudApplicationNameGenerator.cs
test/AWS.Deploy.Orchestration.UnitTests/Utilities/CloudApplicationNameGeneratorTests.cs

Currently, if we have a project "WebApp1" and that project is already deployed, when we try to create a new stack based on that same project, the suggested name will be "WebApp11" instead of "WebApp2". 
This PR fixes this behavior by extracting the number from the end of the project name and increments that instead of just tacking a new number to the end of the project name.

fix: stack name generator incorrectly increments projects

---

THIRD_PARTY_LICENSES

DOTNET-5765
Updating THIRD_PARTY_LICENSES to match our current dependency graph. This was reviewed internally also.
The rough categories of changes:
1. New AWSSDK dependencies (and upgrading others to 3.7)
2. Swapping out CDK dependencies with V1 to V2 upgrade
3. Adding Swashbuckle and OpenApi for server mode

chore: Update third party licenses with current dependencies

---

src/AWS.Deploy.CLI/ServerMode/Controllers/ServerController.cs
src/AWS.Deploy.ServerMode.Client/RestAPI.cs
test/AWS.Deploy.CLI.IntegrationTests/ServerModeTests.cs

DOTNET-5665
Adds an `/api/v1/Health/Shutdown` endpoint to server mode to allow consumers to stop the server. This uses [IHostApplicationLifetime.StopApplication Method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostapplicationlifetime.stopapplication).
This can be called from:
1. The `RestAPIClient`'s new `Shutdown`/`ShutdownAsync` methods
2. `ServerModeSession.Shutdown` method
Added integration tests for ~~both~~ routes.
* _Update: removed the test via `ServerModeSession`, I hadn't realized that this relies on already having the CLI installed locally._

feat: Add shutdown endpoint to server mode to stop the server

---

src/AWS.Deploy.Common/Exceptions.cs
src/AWS.Deploy.Orchestration/CdkProjectHandler.cs

DOTNET-5794
This change makes it so that the deploy tool fails if `cdk bootstrap` fails. Currently, even if `cdk bootstrap` fails, the deployment continues and the subsequent stack fails.

fix: deployment doesn't fail even if cdk bootstrap fails

---

src/AWS.Deploy.CLI/Commands/DeployCommand.cs

DOTNET-5810
Currently, users can choose to create a new stack but choose an existing stack name for the new deployment. This behavior allows users to overwrite an existing stack with another completely different application. This PR fixes this behavior by not allowing the use of an existing stack name.
This error message is presented:

fix: users can create a new stack with existing stack name

---

src/AWS.Deploy.CLI/Commands/CommandFactory.cs
src/AWS.Deploy.CLI/Commands/CommandHandlerInput/ListCommandHandlerInput.cs

This PR removes the redundant `--project-path` CLI option from the `list-deployments` command.

fix: remove --project-path argument from list-deployments command

---

src/AWS.Deploy.CLI/AWSUtilities.cs
src/AWS.Deploy.CLI/Exceptions.cs
src/AWS.Deploy.Common/Exceptions.cs

DOTNET-5802
Currently, all CLI commands (deploy, list, delete) accept the `--profile` option. However, when a non-existent profile is passed, the tool falls back to using the default credentials for the user. This behavior can introduce unintentional destructive changes in the user's account.
This PR changes this behavior by throwing an error when a non-existent profile is passed. 
**Note - This a breaking change**

fix: Throw an error when using non-existent profile names with commands

---

.github/workflows/semgrep-analysis.yml
.semgrepignore

DOTNET-5807
This PR enables code scanning using Semgrep CI
Read more: https://semgrep.dev/docs/semgrep-ci/overview/
While scanning the entire repo with the current rule set, 63 JQuery vulnerabilities were discovered across 12 test web-apps.
Fixing them periodically, will increase toil and therefore `testapps/` have been excluded from code scanning.

chore: enable semgrep

---

src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
src/AWS.Deploy.CLI/ServerMode/Exceptions.cs
src/AWS.Deploy.CLI/ServerMode/Models/GenerateCloudFormationTemplateOutput.cs
src/AWS.Deploy.CLI/ServerMode/Tasks/DeployRecommendationTask.cs
src/AWS.Deploy.Common/Exceptions.cs
src/AWS.Deploy.Orchestration/CdkProjectHandler.cs
src/AWS.Deploy.Orchestration/DeploymentCommands/CdkDeploymentCommand.cs
src/AWS.Deploy.Orchestration/Exceptions.cs
src/AWS.Deploy.ServerMode.Client/RestAPI.cs
test/AWS.Deploy.CLI.IntegrationTests/ServerMode/GetApplyOptionSettings.cs

* Add a StartDryRunDeployment operation in server mode that basically generates the CDK project and runs CDK Diff on that project
* In the integ test, we now check the generated CF template if it contains the correct settings.

feat: Use CDK Diff to perform server mode integ tests

---

src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
src/AWS.Deploy.CLI/ServerMode/Models/OptionSettingItemSummary.cs
src/AWS.Deploy.ServerMode.Client/RestAPI.cs
test/AWS.Deploy.CLI.IntegrationTests/ServerMode/GetApplyOptionSettings.cs

On behalf of @awschristou and #499 
This change updates the GetConfigSettingsAsync response to include TypeHintData information. This will allow the Toolkit to show a filtered list of Roles for settings that have a ServicePrincipal associated with them. Users will be less likely to configure deployments involving IAM Roles that do not have appropriate permissions.
I added an integration test to confirm that TypeHintData properties are being returned. I extracted code from an existing test into methods so that I could re-use it. No logic changes were made to the extracted code.

feat: Add TypeHintData to GetConfigSettings response in Server Mode

---

src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppAppRunner/Generated/Recipe.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Configurations/Configuration.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Recipe.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalk.recipe

DOTNET-5561
This PR makes the following changes to the Elastic Beanstalk deployment configuration.
* Fixes a bug where the service principal for Application IAM Role is incorrectly set to _**"elasticbeanstalk.amazonaws.com"**_. It should be set to _**"ec2.amazonaws.com"**_
* Introduces a Service IAM Role option setting as part of the recipe and the corresponding CDK template.

Amend IAM Roles Associated with Elastic Beanstalk Deployments

---

src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppAppRunner.recipe

VPCConnector child setting VpcId is missing the Type attribute. The current behavior does not cause any issues since VPCConnector uses a typehint and does not need to access the Type of the child settings.

fix: add missing Type attribute to option setting in AppRunner recipe

---

src/AWS.Deploy.CLI/ConsoleUtilities.cs
test/AWS.Deploy.CLI.UnitTests/ConsoleUtilitiesTests.cs

N/A
`AskUserToChooseOrCreateNew` allows users to select an existing option or create new one. When there are no options to select, **Create New** is not shown and CLI returns to previous screen with default selection **Create New** which is correct in theory because that's the only action user can take. However, this is not a good UX.
The check to display selection is moved to (Options + **Empty** + **Create New**) combination, i.e. if any of the options are present, user will be asked to pick one. If none of the exists, the there is modeling error and should be handled at recipe level.
In cases like selecting ECS application role and there doesn't exist any compatible role in AWS account, customer is still asked to picked Create New. …

fix: ask for "Create New" even if options to select is empty

---

src/AWS.Deploy.CLI/App.cs

DOTNET-5803
Added a banner that informs users that the NuGet package name will change to 'AWS.Deploy.Tools'.

chore: add banner to notify of NuGet package name change

---

src/AWS.Deploy.Orchestration/Orchestrator.cs
test/AWS.Deploy.CLI.IntegrationTests/SaveCdkDeploymentProject/RecommendationTests.cs

When computing recommendations for creating a deployment projects filter out non CDK recommendations because we can't generate a project from that.

fix: Prevent non CDK projects from being displayed for deployment projects

---

README.md
src/AWS.Deploy.CLI/AWS.Deploy.CLI.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppAppRunner/README.md
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppEcsFargate/README.md
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/README.md
src/AWS.Deploy.Recipes/CdkTemplates/BlazorWasm/README.md
src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateScheduleTask/README.md
src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateService/README.md
test/ManualLinuxTesting/Dockerfile

DOTNET-5803
change NuGet package name from AWS.Deploy.CLI to AWS.Deploy.Tools and update all doc references.

chore: change NuGet package name from AWS.Deploy.CLI to AWS.Deploy.Tools

---

src/AWS.Deploy.Orchestration/CustomRecipeLocator.cs
test/AWS.Deploy.CLI.IntegrationTests/SaveCdkDeploymentProject/CustomRecipeLocatorTests.cs
test/AWS.Deploy.CLI.IntegrationTests/SaveCdkDeploymentProject/RecommendationTests.cs
test/AWS.Deploy.CLI.UnitTests/ServerModeTests.cs

Currently, we are performing 2 passes of the file-system to determine the source control root of the customer's target application.
Furthermore, incase of nested `git` directories, we are traversing till the very top of the source control chain.
This PR amend this behavior in the following ways: 
* Only performing a single pass of the file-system to determine the source control root.
* Stop the search on the first ancestor that contains a `.git` folder.
* If the source control root is equal to the file-system root, then don't use it to locate custom recipe paths (default to solution directory path)

fix: Amend strategy to find the source control root directory

---

src/AWS.Deploy.Recipes/DeploymentBundleDefinitions/Container.deploymentbundle

*Description of changes:* 
The name of this option references ECS even though we're technically pushing the image to an ECR repository (especially now that we have an ECR-only recipe). It appears this may have been a typo.
Before:
```
18. ECS Repository Name: aspnetwebapp
Or press 'Enter' to deploy:
18
ECS Repository Name:
Specifies the ECR repository where the docker images will be stored
Select ECR Repository:
----------------------
1 : aspnetwebapp
```
After:
```
18. ECR Repository Name: aspwebapi
Or press 'Enter' to deploy:
18
ECR Repository Name:
Specifies the ECR repository where the Docker images will be stored
Select ECR Repository:
----------------------
1 : aspnetwebapp
```
By submitting this pull request, I confirm that you can use, modify, copy, …

fix: Rename the "ECR Repository Name" advanced option to reference "ECR" instead of "ECS" for Docker-based recipes

---

src/AWS.Deploy.ServerMode.Client/CommandLineWrapper.cs

DOTNET-5792
Added a try catch block to catch the exception thrown when trying to write to the StandardInput which caused an issue in the toolkit.

fix: server mode startup code not very resilient

---

src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
src/AWS.Deploy.CLI/ServerMode/Models/ExistingDeploymentSummary.cs
src/AWS.Deploy.CLI/ServerMode/Models/RecommendationSummary.cs
src/AWS.Deploy.ServerMode.Client/AnnotatedModels.cs
src/AWS.Deploy.ServerMode.Client/RestAPI.cs
test/AWS.Deploy.CLI.IntegrationTests/BeanstalkBackwardsCompatibilityTests/ServerModeTests.cs
test/AWS.Deploy.CLI.IntegrationTests/ServerModeTests.cs
test/AWS.Deploy.CLI.UnitTests/ServerModeTests.cs

Based on Chris's PR https://github.com/aws/aws-dotnet-deploy/pull/520
This change adds a recipe's BaseRecipeId, and whether or not the project is a Persisted Project (generated through the deploy tool) to the Rest API. This allows clients like the Toolkit to identify the source recipe that is used with persisted projects.
This change also introduces some DebuggerDisplay attributes, to help Toolkit development when working with models exposed through the Rest API.
DebuggerDisplay example

feat: Add persisted project details to API; Add debugger display hints for servermode clients

---

src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.CLI/ConsoleOrchestratorLogger.cs
src/AWS.Deploy.CLI/ServerMode/Hubs/DeploymentCommunicationHub.cs
src/AWS.Deploy.CLI/ServerMode/Services/SessionOrchestratorInteractiveService.cs
src/AWS.Deploy.CLI/Utilities/CommandLineWrapper.cs
src/AWS.Deploy.Orchestration/CDK/CDKManager.cs
src/AWS.Deploy.Orchestration/CDK/NPMPackageInitializer.cs
src/AWS.Deploy.Orchestration/CdkProjectHandler.cs
src/AWS.Deploy.Orchestration/CustomRecipeLocator.cs
src/AWS.Deploy.Orchestration/DeploymentBundleHandler.cs
src/AWS.Deploy.Orchestration/DeploymentCommands/BeanstalkEnvironmentDeploymentCommand.cs
src/AWS.Deploy.Orchestration/DeploymentCommands/CdkDeploymentCommand.cs
src/AWS.Deploy.Orchestration/IOrchestratorInteractiveService.cs
src/AWS.Deploy.Orchestration/Orchestrator.cs
src/AWS.Deploy.Orchestration/ServiceHandlers/AWSElasticBeanstalkHandler.cs
src/AWS.Deploy.Orchestration/ServiceHandlers/AWSS3Handler.cs
src/AWS.Deploy.Orchestration/Utilities/DeployedApplicationQueryer.cs
src/AWS.Deploy.ServerMode.Client/DeploymentCommunicationClient.cs
test/AWS.Deploy.CLI.Common.UnitTests/Services/InMemoryInteractiveService.cs
test/AWS.Deploy.CLI.IntegrationTests/BeanstalkBackwardsCompatibilityTests/ServerModeTests.cs
test/AWS.Deploy.CLI.IntegrationTests/BeanstalkBackwardsCompatibilityTests/TestContextFixture.cs
test/AWS.Deploy.CLI.IntegrationTests/Helpers/ElasticBeanstalkHelper.cs
test/AWS.Deploy.CLI.IntegrationTests/ServerMode/GetApplyOptionSettings.cs
test/AWS.Deploy.CLI.IntegrationTests/ServerModeTests.cs
test/AWS.Deploy.CLI.UnitTests/Utilities/TestToolOrchestratorInteractiveService.cs

For the log output during a deployment write section headers along with descriptions that explain what is happening at this stage of deployment.
Here is what the headers look like using the CLI.
For the VS toolkit there is a new message sent through the SignalR hub that the toolkit can use to get notified when new sections are started. The toolkit can either add the section headers in the output window or create category based UI control.
Notes for PR
* Renamed the logging methods on `IOrchestratorInteractiveService` and the SignalR client `IDeploymentCommunicationHub` to make the names consisted. I have discussed this with the IDE team so and they are fine adapting to the change when the adopt the new version.
* On SignalR client removed the …

feat: Rework deployment logging to have section headers

---

src/AWS.Deploy.CLI/Utilities/ProjectParserUtility.cs
src/AWS.Deploy.Common/ProjectDefinitionParser.cs
test/AWS.Deploy.CLI.UnitTests/ProjectParserUtilityTests.cs

https://github.com/aws/aws-dotnet-deploy/issues/515
Currently, when an invalid/non-existent project path is provided, the deploy tool crashes with an unhandled exception.
This PR ensures that the appropriate exception with an actionable error message is thrown incase of an invalid/non-existent project path

fix: Handle invalid project paths with appropriate exception

---

src/AWS.Deploy.Common/Exceptions.cs
src/AWS.Deploy.Orchestration/Data/AWSResourceQueryer.cs

When deploy tool makes call to AWS services and a service call fails, this is shown as bug to customer which in most cases are configuration issues such as not having correct permissions for the operation call made. This gives a false impression to customer that there a bug in the deploy tool.
Similar to other places, this change wraps the AWS service calls to a try-catch block and if the exception is `AmazonServiceException` which is base exception for all operations, it is wrapped in a  `ResourceQueryException` i.e. a `DeployToolException` to make it an expected exception. Expected exceptions don't emit stacktrace unless `--diagnostics` is provided.
Case such as not having permission to make a operation call now, shows a ErrorCode and …

fix: catch AmazonServiceException on making calls to AWS services and wrap into DeployToolException

---

src/AWS.Deploy.ServerMode.Client/DeploymentCommunicationClient.cs
test/AWS.Deploy.CLI.IntegrationTests/ServerModeTests.cs

In the previous **0.42.10** release we added a new Action callback called `ReceiveLogSectionStart` on the SignalR client but we forgot to add `ReceiveLogSectionStart` to the interface of the client. This PR adds the missing `ReceiveLogSectionStart` callback to the interface.

fix: Add the new ReceiveLogSectionStart callback to the IDeploymentCommunicationClient

---

src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
src/AWS.Deploy.CLI/ServerMode/Tasks/DeployRecommendationTask.cs
src/AWS.Deploy.Common/Exceptions.cs

This PR adds a new error code to distinguish `FailedToCreateDeploymentBundleException` when using a generated Docker file.

fix: Add new error code to indicate deployment bundle creation failure from a generate docker file

---

src/AWS.Deploy.CLI/Commands/TypeHints/BeanstalkApplicationCommand.cs
src/AWS.Deploy.CLI/TypeHintResponses/BeanstalkApplicationTypeHintResponse.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Configurations/BeanstalkApplicationConfiguration.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Configurations/BeanstalkEnvironmentConfiguration.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Recipe.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalk.recipe
testapps/WebAppNoDockerFile/ElasticBeanStalkConfigFile.json

The Beanstalk recipe had 2 issues with the settings.
* **Application Name** - This is a object setting with a **CreateNew** child setting. In the original version the **ApplicationName** setting was incorrectly being used for either new application names or existing application names. This has been fixed to have a separate **ExistingApplicationName** for existing application names. The **ExistingApplicationName** has the type hint telling and the **ApplicationName** is just a pure text entry. 
* **Environment Name** - This object setting incorrectly had a **CreateNew** setting that would allow selecting an existing Beanstalk environment name. The CDK project doesn't support using a Beanstalk environment that doesn't belong to the stack.
By submitting this pull …

fix: Fixed issue with Beanstalk Application and Environment name

---

src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
src/AWS.Deploy.CLI/ServerMode/Tasks/DeployRecommendationTask.cs
src/AWS.Deploy.Orchestration/Orchestrator.cs
test/AWS.Deploy.CLI.IntegrationTests/BeanstalkBackwardsCompatibilityTests/CLITests.cs
test/AWS.Deploy.CLI.IntegrationTests/BeanstalkBackwardsCompatibilityTests/ServerModeTests.cs
test/AWS.Deploy.CLI.IntegrationTests/ServerMode/GetApplyOptionSettings.cs
test/AWS.Deploy.CLI.IntegrationTests/ServerModeTests.cs

The CLI and ServerMode had separate `CreateDeploymentBundle` method implementations. This caused issues with the recent new change to add new logging section headers because only the CLI version had the section header.
This PR pushes the `CreateDeploymentBundle` into the Orchestrator so both the CLI and ServerMode can use the same implementation. The CLI implementation did have the interactive part to ask the user if they want to change the Docker execution directory if the build failed. I kept that logic in the CLI but it only prompts if `CreateDeploymentBundle` in the Orchestrator throws an exception with the container build error code.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …

fix: Consolidate implementations of CreateDeploymentBundle

---

THIRD_PARTY_LICENSES
src/AWS.Deploy.Constants/CDK.cs
src/AWS.Deploy.Orchestration/AWS.Deploy.Orchestration.csproj
src/AWS.Deploy.Orchestration/CdkProjectHandler.cs
src/AWS.Deploy.Orchestration/Data/AWSResourceQueryer.cs
test/AWS.Deploy.CLI.IntegrationTests/Utilities/TestToolAWSResourceQueryer.cs
test/AWS.Deploy.CLI.UnitTests/Utilities/TestToolAWSResourceQueryer.cs
test/AWS.Deploy.Orchestration.UnitTests/CDK/CDKProjectHandlerTests.cs

Before executing "cdk bootstrap" command to make create the CDK bootstrap CloudFormation stack check to see if the stack already exists. If it does exist and its version checked in parameter store is at least the version that the deploy uses then skip calling out to the CDK.

feat: Skip executing "cdk deploy" if CDKToolkit stack already exists

---

src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppAppRunner.recipe

Security Group option setting in App Runner recipe has an invalid name

fix: Security Group option setting in App Runner recipe has an invalid name

---

src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
src/AWS.Deploy.Orchestration/Utilities/CloudApplicationNameGenerator.cs
test/AWS.Deploy.CLI.IntegrationTests/ServerModeTests.cs

DOTNET-5895
This PR adds the stack name validation logic to server mode.

fix: Add stack name validation in server mode

---

src/AWS.Deploy.Common/Exceptions.cs
src/AWS.Deploy.Orchestration/CdkProjectHandler.cs
src/AWS.Deploy.Orchestration/Data/AWSResourceQueryer.cs
src/AWS.Deploy.Orchestration/Utilities/WaitUntilHelper.cs
test/AWS.Deploy.CLI.IntegrationTests/BeanstalkBackwardsCompatibilityTests/ServerModeTests.cs
test/AWS.Deploy.CLI.IntegrationTests/Helpers/HttpHelper.cs
test/AWS.Deploy.CLI.IntegrationTests/ServerModeTests.cs
test/AWS.Deploy.CLI.IntegrationTests/Utilities/TestToolAWSResourceQueryer.cs
test/AWS.Deploy.CLI.UnitTests/Utilities/TestToolAWSResourceQueryer.cs

DOTNET-5899
DOTNET-5896
* Added missing CloudFormation event statuses to capture all failed events
* Added ability to retrieve unique stack id to retrieve stack events even after deployment finishes (whether the stack is deleted or not)
* Added metric to check deployment time which will help in analysis of errors in telemetry

chore: improve error handling for failed first time deployments

---

src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
src/AWS.Deploy.CLI/ServerMode/Controllers/RecipeController.cs
src/AWS.Deploy.ServerMode.Client/RestAPI.cs
test/AWS.Deploy.CLI.IntegrationTests/ServerModeTests.cs

Add the `ProducesResponseType` attribute to all of the REST APIs in server mode. This allows the client code generator to generate a `ProblemDetails` type that the toolkit can use to get the error message for the bad error code.

fix: Add ProducesResponseType for the possible error codes in ServerMode API

---

src/AWS.Deploy.CLI/Utilities/AssumeRoleMfaTokenCodeCallback.cs

This PR fixes the reason behind the release failure.

fix: cannot use ActivatorUtilities.CreateInstance with internal class

---

src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.Common/Exceptions.cs
src/AWS.Deploy.Orchestration/DeploymentBundleHandler.cs
src/AWS.Deploy.Orchestration/Orchestrator.cs
src/AWS.Deploy.Orchestration/Utilities/ZipFileManager.cs

DOTNET-5923
Currently, we may encounter numerous exceptions while creating the deployment bundle. However, these exceptions are being swallowed and a generic `FailedToCreateDeploymentBundleException` is thrown.
This PR mitigates the above issue by bubbling up all the `DeployToolException` encountered while creating the deployment bundle. The error codes and error messages from these exceptions are captured and encapsulated inside `FailedToCreateDeploymentBundleException`

chore: Improve error handling when creation of deployment bundle fails

---

docs/OptionSettingsItems-input-validation.md
src/AWS.Deploy.CLI/Commands/CommandFactory.cs
src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.CLI/Extensions/CustomServiceCollectionExtension.cs
src/AWS.Deploy.Common/Recipes/OptionSettingItem.ValueOverride.cs
src/AWS.Deploy.Common/Recipes/OptionSettingItem.cs
src/AWS.Deploy.Common/Recipes/Validation/IRecipeValidator.cs
src/AWS.Deploy.Common/Recipes/Validation/RecipeValidators/FargateTaskCpuMemorySizeValidator.cs
src/AWS.Deploy.Common/Recipes/Validation/RecipeValidators/MinMaxConstraintValidator.cs
src/AWS.Deploy.Common/Recipes/Validation/ValidatorFactory.cs
src/AWS.Deploy.Orchestration/OptionSettingHandler.cs
test/AWS.Deploy.CLI.Common.UnitTests/Recipes/Validation/AppRunnerOptionSettingItemValidationTests.cs
test/AWS.Deploy.CLI.Common.UnitTests/Recipes/Validation/ECSFargateOptionSettingItemValidationTests.cs
test/AWS.Deploy.CLI.Common.UnitTests/Recipes/Validation/ElasticBeanStalkOptionSettingItemValidationTests.cs
test/AWS.Deploy.CLI.Common.UnitTests/Recipes/Validation/OptionSettingsItemValidationTests.cs
test/AWS.Deploy.CLI.Common.UnitTests/Recipes/Validation/ValidatorFactoryTests.cs
test/AWS.Deploy.CLI.IntegrationTests/SaveCdkDeploymentProject/RecommendationTests.cs
test/AWS.Deploy.CLI.UnitTests/ApplyPreviousSettingsTests.cs
test/AWS.Deploy.CLI.UnitTests/ConsoleUtilitiesTests.cs
test/AWS.Deploy.CLI.UnitTests/GetOptionSettingTests.cs
test/AWS.Deploy.CLI.UnitTests/RecommendationTests.cs
test/AWS.Deploy.CLI.UnitTests/SetOptionSettingTests.cs
test/AWS.Deploy.CLI.UnitTests/TypeHintCommands/ExistingSecurityGroubsCommandTest.cs
test/AWS.Deploy.CLI.UnitTests/TypeHintCommands/ExistingSubnetsCommandTest.cs
test/AWS.Deploy.CLI.UnitTests/TypeHintCommands/ExistingVpcCommandTest.cs
test/AWS.Deploy.CLI.UnitTests/TypeHintCommands/VPCConnectorCommandTest.cs
test/AWS.Deploy.CLI.UnitTests/TypeHintTests.cs
test/AWS.Deploy.Orchestration.UnitTests/CDK/CDKProjectHandlerTests.cs
test/AWS.Deploy.Orchestration.UnitTests/ElasticBeanstalkHandlerTests.cs

*Issue #, if available:* N/A, this is to support upcoming work to improve validation on deployment bundle settings. https://github.com/aws/aws-dotnet-deploy/pull/509 will also make use of this.
Previously, `IOptionSettingItemValidator` and `IRecipeValidator` were always initialized through parameterless constructors. The current set of validators are self contained (required, ranges, regexes) that did not need any dependencies.
However upcoming validators around the Docker file and execution directory require an instance of `IDirectoryManager` and `IFileManager`.
This reworks `ValidatorFactory` to be able to inject services into validators when initializing them. 
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

chore: Add constructor injection support to option and recipe validators

---

src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.CLI/Exceptions.cs
src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
src/AWS.Deploy.Common/CloudApplication.cs
src/AWS.Deploy.Common/Exceptions.cs
src/AWS.Deploy.Orchestration/Utilities/CloudApplicationNameGenerator.cs
test/AWS.Deploy.CLI.IntegrationTests/ServerModeTests.cs
test/AWS.Deploy.Orchestration.UnitTests/Utilities/CloudApplicationNameGeneratorTests.cs

DOTNET-5924
https://github.com/aws/aws-dotnet-deploy/pull/505 prevented the user from providing an existing cloud application name, while performing a new deployment.
This PR extends this functionality to server mode and ensures that the cloud application name is only unique within the current deployment type.

fix: Check for duplicate cloud application names

---

src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalk.recipe

DOTNET-5882
This PR changes the top-level `BeanstalkApplication` option setting name to `Elastic Beanstalk Application`. This is done because the original option setting name (`Application Name`) was also being used to set the name of the CloudFormation stack. Using the same name to represent the different constructs can be confusing to users.

chore: Alter option setting names in Elastic Beanstalk recipe

---

src/AWS.Deploy.Common/Recipes/IOptionSettingHandler.cs
src/AWS.Deploy.Common/Recipes/OptionSettingItem.cs
src/AWS.Deploy.Orchestration/OptionSettingHandler.cs
src/AWS.Deploy.Orchestration/RecipeHandler.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/aws-deploy-recipe-schema.json
test/AWS.Deploy.CLI.Common.UnitTests/IO/TestDirectoryManager.cs
test/AWS.Deploy.CLI.Common.UnitTests/Recipes/Validation/AppRunnerOptionSettingItemValidationTests.cs
test/AWS.Deploy.CLI.Common.UnitTests/Recipes/Validation/ECSFargateOptionSettingItemValidationTests.cs
test/AWS.Deploy.CLI.Common.UnitTests/Recipes/Validation/ElasticBeanStalkOptionSettingItemValidationTests.cs
test/AWS.Deploy.CLI.Common.UnitTests/Recipes/Validation/OptionSettingsItemValidationTests.cs
test/AWS.Deploy.CLI.Common.UnitTests/Recipes/Validation/ValidatorFactoryTests.cs
test/AWS.Deploy.CLI.IntegrationTests/SaveCdkDeploymentProject/CustomRecipeLocatorTests.cs
test/AWS.Deploy.CLI.IntegrationTests/SaveCdkDeploymentProject/RecommendationTests.cs
test/AWS.Deploy.CLI.UnitTests/ApplyPreviousSettingsTests.cs
test/AWS.Deploy.CLI.UnitTests/DeploymentBundleHandlerTests.cs
test/AWS.Deploy.CLI.UnitTests/GetOptionSettingTests.cs
test/AWS.Deploy.CLI.UnitTests/RecommendationTests.cs
test/AWS.Deploy.CLI.UnitTests/ServerModeTests.cs
test/AWS.Deploy.CLI.UnitTests/SetOptionSettingTests.cs
test/AWS.Deploy.CLI.UnitTests/Utilities/HelperFunctions.cs
test/AWS.Deploy.Orchestration.UnitTests/AWS.Deploy.Orchestration.UnitTests.csproj
test/AWS.Deploy.Orchestration.UnitTests/DisplayedResourcesHandlerTests.cs
test/AWS.Deploy.Orchestration.UnitTests/ElasticBeanstalkHandlerTests.cs
test/AWS.Deploy.Orchestration.UnitTests/RecipeHandlerTests.cs
test/AWS.Deploy.Orchestration.UnitTests/Recipes/OptionSettingCyclicDependency.recipe
test/AWS.Deploy.Orchestration.UnitTests/TestDirectoryManager.cs
test/AWS.Deploy.Orchestration.UnitTests/Utilities/TestToolOrchestratorInteractiveService.cs

DOTNET-5920
* Build an option setting dependency tree that allows us to easily determine which option settings need to be validated when a value update happens.
* Added Leaf ID and Parent fields to option settings to allow easy navigation of option settings

chore: create an option setting dependency tree

---

src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
src/AWS.Deploy.CLI/ServerMode/Models/OptionSettingItemSummary.cs
src/AWS.Deploy.Common/Recipes/OptionSettingItem.ValueOverride.cs
src/AWS.Deploy.Common/Recipes/OptionSettingItem.cs
src/AWS.Deploy.Common/Recipes/OptionSettingValidation.cs
src/AWS.Deploy.Orchestration/OptionSettingHandler.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalk.recipe
src/AWS.Deploy.ServerMode.Client/RestAPI.cs
test/AWS.Deploy.CLI.IntegrationTests/ServerMode/DependencyValidationOptionSettings.cs
test/AWS.Deploy.CLI.IntegrationTests/ServerMode/GetApplyOptionSettings.cs
test/AWS.Deploy.CLI.IntegrationTests/Utilities/ServerModeUtilities.cs

DOTNET-5920
* Added a validation status and validation message to option setting items
* The validators of dependent settings are now run when that setting is set
* Updated server mode to return the validation object

feat: run dependent settings validators when an option setting value is set

---

src/AWS.Deploy.CLI/Commands/CommandFactory.cs
src/AWS.Deploy.CLI/Commands/GenerateDeploymentProjectCommand.cs
src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
src/AWS.Deploy.CLI/ServerMode/Controllers/RecipeController.cs
src/AWS.Deploy.CLI/ServerMode/Models/OptionSettingItemSummary.cs
src/AWS.Deploy.Common/Recipes/IRecipeHandler.cs
src/AWS.Deploy.Common/Recipes/OptionSettingItem.ValueOverride.cs
src/AWS.Deploy.Common/Recipes/OptionSettingItem.cs
src/AWS.Deploy.Common/Recipes/OptionSettingValidation.cs
src/AWS.Deploy.Orchestration/OptionSettingHandler.cs
src/AWS.Deploy.Orchestration/Orchestrator.cs
src/AWS.Deploy.Orchestration/RecipeHandler.cs
src/AWS.Deploy.Orchestration/RecommendationEngine/RecommendationEngine.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppAppRunner.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppECSFargate.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalk.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateScheduleTask.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateService.recipe
src/AWS.Deploy.ServerMode.Client/RestAPI.cs
test/AWS.Deploy.CLI.IntegrationTests/ServerMode/DependencyValidationOptionSettings.cs
test/AWS.Deploy.CLI.IntegrationTests/ServerMode/GetApplyOptionSettings.cs
test/AWS.Deploy.CLI.IntegrationTests/Utilities/ServerModeUtilities.cs
test/AWS.Deploy.CLI.UnitTests/ServerModeTests.cs

DOTNET-5920
RegEx validators for existing resources have AllowEmptyString set to true which causes failed deployments if not set. I have removed that so that the validators can run when a dependent setting is set.

fix: remove AllowEmptyString from Regex validators as they allow failed deployments

---

.github/workflows/codebuild-ci.yml
buildtools/README.md
buildtools/ci.buildspec.yml
buildtools/ci.template.yml

1. Changes GitHub Action for PRs [codebuild-ci.yml](https://github.com/aws/aws-dotnet-deploy/blob/main/.github/workflows/codebuild-ci.yml) to pass credentials via a (pre-configured) OpenID Connector.  GitHub repository will be pre-authorized to access credentials.  This replaces current strategy of storing access key id and secret as a GitHub Repository Secret.
1. Adds Cloud Formation template (infrastructure as code) to define the Backing CodeBuild job for [codebuild-ci.yml](https://github.com/aws/aws-dotnet-deploy/blob/main/.github/workflows/codebuild-ci.yml).
As part of accepting this PR:
1.  create a new Cloud Formation template using _/buildtools/ci.template.yml_
2. Store the outputs of the Cloud Formation as GitHub Repository Secrets:
> Create …

ci: update PR build to use AWS CodeBuild & GitHub OpenID Connector

---

buildtools/ci.template.yml

PR checks are failing because of CF throttling since we are running multiple checks at once. This change will add a concurrency limit of 1 for the codebuild project.

ci: add integration test PR check codebuild project concurrency limit

---

src/AWS.Deploy.Orchestration/OptionSettingHandler.cs
test/AWS.Deploy.CLI.UnitTests/GetOptionSettingTests.cs

When setting an option setting value, all validators are run for that setting and its children. This change changes this behavior to only run the validators for the displayable children as they are the only ones applicable.

feat: only run validators if setting is displayable

---

src/AWS.Deploy.Common/Recipes/OptionSettingItem.ValueOverride.cs
src/AWS.Deploy.Common/Recipes/OptionSettingValidation.cs
src/AWS.Deploy.Orchestration/OptionSettingHandler.cs
src/AWS.Deploy.ServerMode.Client/RestAPI.cs
test/AWS.Deploy.CLI.IntegrationTests/ServerMode/DependencyValidationOptionSettings.cs

Persist invalid value set by the user in the validation object of the option setting item. This is used mainly in the toolkit from server mode where invalid values can remain on the UI until users replace them with valid settings.

feat: persist invalid value in validation object of option setting item

---

src/AWS.Deploy.Common/Recipes/Validation/OptionSettingItemValidatorList.cs
src/AWS.Deploy.Common/Recipes/Validation/OptionSettingItemValidators/StringLengthValidator.cs
src/AWS.Deploy.Common/Recipes/Validation/ValidatorFactory.cs
src/AWS.Deploy.Recipes/DeploymentBundleDefinitions/Container.deploymentbundle
src/AWS.Deploy.Recipes/RecipeDefinitions/aws-deploy-recipe-schema.json
test/AWS.Deploy.CLI.Common.UnitTests/Recipes/Validation/ECSFargateOptionSettingItemValidationTests.cs

DOTNET-5919
This PR adds a new validator type `StringLengthValidator` and imposes it on ECR repository names.

feat: Add string length validator to ECR repository name

---

src/AWS.Deploy.CLI/AWS.Deploy.CLI.csproj
src/AWS.Deploy.Orchestration/AWS.Deploy.Orchestration.csproj
src/AWS.Deploy.Orchestration/CdkProjectHandler.cs
src/AWS.Deploy.Orchestration/TemplateEngine.cs
src/AWS.Deploy.Orchestration/Utilities/DeployedApplicationQueryer.cs
src/AWS.Deploy.Orchestration/Utilities/TemplateMetadataReader.cs

When we updated to CDK V2 the NuGet package size for the CLI tool increased from about **5 megs** to **63 megs**. This was due to `AWS.Deploy.Recipes.CDK.Common` package having a dependency on `Amazon.CDK.Lib` and for V2 the `Amazon.CDK.Lib.dll` file is 71 megs.
The only think the CLI needs from `AWS.Deploy.Recipes.CDK.Common` is the POCO `RecipeProps` used for appsetings.json serialization. It has no reference to the CDK. I removed the references in the CLI to `AWS.Deploy.Recipes.CDK.Common` project and then did a source link to `RecipeProps.cs` file. Now file size is back down to 5 megs.

feat: Reduce AWS.Deploy.Tools NuGet packaged down to 5 megs from 63 megs

---

src/AWS.Deploy.Common/Recipes/Validation/OptionSettingItemValidatorList.cs
src/AWS.Deploy.Common/Recipes/Validation/OptionSettingItemValidators/SecurityGroupsInVpcValidator.cs
src/AWS.Deploy.Common/Recipes/Validation/OptionSettingItemValidators/SubnetsInVpcValidator.cs
src/AWS.Deploy.Common/Recipes/Validation/ValidatorFactory.cs
src/AWS.Deploy.Orchestration/OptionSettingHandler.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppAppRunner.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/aws-deploy-recipe-schema.json
test/AWS.Deploy.CLI.UnitTests/GetOptionSettingTests.cs

This change is to fix a behavior in the toolkit where a user selects subnets and security groups and then changes the selected VPC which invalidates the already selected subnets and security groups. This adds a validator that checks if the selected subnets and security groups are part of the selected vpc.

feat: add validators to check if Subnets and Security Groups are part of the same VPC

---

.github/workflows/DetectRestAPIClientChanges.yml

This PR adds a GitHub workflow to check for changes in RestAPI client and make sure that future PRs don't miss updating the RestAPI client.

ci: add PR check to make sure RestApi client is updated

---

src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.Common/Recipes/Validation/OptionSettingItemValidatorList.cs
src/AWS.Deploy.Common/Recipes/Validation/OptionSettingItemValidators/UriValidator.cs
src/AWS.Deploy.Common/Recipes/Validation/ValidatorFactory.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/BlazorWasm.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/aws-deploy-recipe-schema.json
test/AWS.Deploy.CLI.Common.UnitTests/Recipes/Validation/BlazorWasmOptionSettingItemValidationTest.cs

* DOTNET-5805
* DOTNET-5806
* Add new `UriValidator` class
* Enforces the `UriValidator` and `RegexValidator` on `BackendApi.Uri`.
* Set default value for `BackendApi.ResourcePathPattern` and impose the `RegexValidator` on it.

 feat: Add URI validator and set default value for resource path pattern in the Blazor recipe

---

src/AWS.Deploy.Recipes/RecipeDefinitions/PushContainerImageECR.recipe
test/AWS.Deploy.CLI.Common.UnitTests/Recipes/Validation/PushToECROptionSettingItemValidationTests.cs

The image tag option setting can contain hyphens(-) in it. However, the current regex did not escape the hyphen character.
This PR fixes the issue.

fix: Escape hyphen(-) in the image tag regex validator

---

src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
src/AWS.Deploy.ServerMode.Client/RestAPI.cs
test/AWS.Deploy.CLI.IntegrationTests/Helpers/CloudFormationHelper.cs
test/AWS.Deploy.CLI.IntegrationTests/ServerModeTests.cs

DOTNET-5993
ApplyConfigSettings API now rejects updating readonly settings

feat: ApplyConfigSettings API now rejects updating readonly settings

---

src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
test/AWS.Deploy.CLI.IntegrationTests/ServerMode/GetApplyOptionSettings.cs

DOTNET-5926
This change runs the recipe validators in the StartDeployment API.

fix: recipe validators are not run in server mode

---

src/AWS.Deploy.Common/Recipes/RecipeDefinition.cs
src/AWS.Deploy.Common/Recommendation.cs
src/AWS.Deploy.Orchestration/RecipeHandler.cs
src/AWS.Deploy.Orchestration/RecommendationEngine/RecommendationEngine.cs
test/AWS.Deploy.CLI.Common.UnitTests/Recipes/Validation/DockerfilePathValidationTests.cs
test/AWS.Deploy.CLI.UnitTests/DeploymentBundleHandlerTests.cs
test/AWS.Deploy.Orchestration.UnitTests/DeployedApplicationQueryerTests.cs

The deployment bundle settings are not handled by the RecipeHandler and as a result, they don't have a fully qualified ID or the dependency tree. At the moment they don't have dependencies, but they could in the future. This PR moves the creation of the deployment bundle settings to the RecipeHandler and makes them part of the Recipe and not the Recommendation.

fix: deployment bundle settings don't have a fully qualified id

---

src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Configurations/Configuration.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Configurations/VPCConfiguration.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Recipe.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppECSFargate.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalk.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateScheduleTask.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateService.recipe
test/AWS.Deploy.CLI.UnitTests/RecommendationTests.cs
test/AWS.Deploy.CLI.UnitTests/TypeHintCommands/ExistingVpcCommandTest.cs

We recently updated the VPC Connector setting in App Runner which involved adding a default VPC for VPC ID, updating validators and adding dependencies. These updates have now been applied to the rest of the recipes where applicable.
For beanstalk recipe, this will cause a breaking change as the VPC setting has now been turned into an Object type which included the "UseVPC" setting which is set to false by default. So deployments already using a VPC will need to delete and recreate their stacks as the VPC setting is not updatable in beanstalk.
Additionally, child option settings "Updatable" value was being ignored if parent setting's "Updatable" is true. This change fixes the behavior.
By submitting this pull request, I confirm that you can use, modify, copy, and …

feat: update VPCs in all recipes to match app runner recipe

---

src/AWS.Deploy.CLI/AWS.Deploy.CLI.csproj
src/AWS.Deploy.CLI/Commands/GenerateDeploymentProjectCommand.cs
src/AWS.Deploy.CLI/Commands/TypeHints/SNSTopicArnsCommand.cs
src/AWS.Deploy.CLI/Commands/TypeHints/SQSQueueUrlCommand.cs
src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs

To support M1 macs that only have .NET 6 ARM installed the CLI is updated to compile for both .NET Core 3.1 and .NET 6.
Adding .NET 6 triggered a few more possible null reference errors that made fixes for.
I have confirmed pointing the VS toolkit to the .NET 6 compiled version of the CLI works as expected.

feat: Add .NET 6 as a target framework for CLI to support M1 Macs

---

src/AWS.Deploy.DockerEngine/Properties/DockerFileConfig.json
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppAppRunner.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppECSFargate.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalk.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppExistingBeanstalkEnvironment.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateScheduleTask.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateService.recipe
test/AWS.Deploy.CLI.UnitTests/DockerTests.cs
testapps/docker/WebAppDifferentTargetFramework/WebAppDifferentTargetFramework.csproj
testapps/docker/WebAppNet7/Program.cs
testapps/docker/WebAppNet7/WebAppNet7.csproj
testapps/docker/WebAppNet7/appsettings.Development.json
testapps/docker/WebAppNet7/appsettings.json
testapps/docker/WorkerServiceExample/Dockerfile

For all container based recipes add .NET 7 to the list of supported target frameworks and include the .NET 7 base images to the framework to image mapping.
Also removed .NET Core 2.1 from the list since the version is well out of support and no reason to GA with that support in the tool.

feat: Update supported target frameworks for recipes

---

src/AWS.Deploy.Orchestration/DeploymentCommands/CdkDeploymentCommand.cs

The integration test `AWS.Deploy.CLI.IntegrationTests.SaveCdkDeploymentProject.RedeploymentTests.AttemptWorkFlow` has been failing due to a `cdk` issue with the following error:
```
Configuring AWS Cloud Development Kit (CDK)
CDK version 2.13.0 found in global node_modules.
Confirmed CDK Bootstrap CloudFormation stack already exists.
Deploying AWS CDK project
npx: installed 2 in 1.876s
Unexpected token '?'
We had an issue deploying your application to AWS. Check the deployment output for more details. Deployment took 3.19s.
at AWS.Deploy.Orchestration.CdkProjectHandler.DeployCdkProject(OrchestratorSession session, CloudApplication cloudApplication, String cdkProjectPath, Recommendation recommendation) in …
```

fix: proper cdk version is not installed in the local deployment project directory

---

src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
test/AWS.Deploy.CLI.IntegrationTests/ServerMode/GetApplyOptionSettings.cs

A failed setting update using server mode's `ApplyConfigSettings` API was returning the setting value and the error message instead of the setting ID and error message. This caused the toolkit to not show a validation message for the setting.

fix: failed setting updates in server mode return setting value instead of ID

---

src/AWS.Deploy.Common/Recipes/Validation/OptionSettingItemValidators/ExistingResourceValidator.cs

`_awsResourceQueryer.ListOfElasticBeanstalkEnvironments(...)` can return environments that were freshly terminated. 
If a user tries to deploy with an environment name that was used by a previously terminated environment, then the `ExistingResourceValidator` fails.
This PR prevents validating against terminated Beanstalk environments.

fix: Do not validate against terminated Beanstalk environments

---

src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppAppRunner/Generated/Recipe.cs
test/AWS.Deploy.CLI.IntegrationTests/WebAppWithDockerFileTests.cs
testapps/WebAppWithDockerFile/AppRunnerConfigFile.json
testapps/WebAppWithDockerFile/Controllers/EnvVarController.cs
testapps/WebAppWithDockerFile/Startup.cs
testapps/WebAppWithDockerFile/WebAppWithDockerFile.csproj

The App Runner recipe allows users to configure environment variables but the environment variables were not being correctly being set on the App Runner CDK construct causing them to be ignored. The CDK project was passing the environment variables as a `List` but it needed to be an array.

fix: Fixed environment variables not being set correctly in AWS App Runner deployments

---

buildtools/ci.buildspec.yml
buildtools/ci.template.yml

Since CDK has dropped support for Node 12, we need to update our PR check infra to the minimum supported Node version which is 14.
I needed to switch to an Ubuntu image instead of AL2 since AL2 only supports Node 12.
I also removed installing NET 5 since it is already installed on the Ubuntu image.
https://docs.aws.amazon.com/codebuild/latest/userguide/available-runtimes.html

build: update the PR check infra to support node 14

---

src/AWS.Deploy.Common/Recipes/Validation/OptionSettingItemValidatorList.cs
src/AWS.Deploy.Common/Recipes/Validation/OptionSettingItemValidators/VPCSubnetsInDifferentAZsValidator.cs
src/AWS.Deploy.Common/Recipes/Validation/ValidatorFactory.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppECSFargate.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/aws-deploy-recipe-schema.json
test/AWS.Deploy.CLI.Common.UnitTests/Recipes/Validation/ECSFargateOptionSettingItemValidationTests.cs

DOTNET-5893
This PR tackles the deployment failure with the error: `At least two subnets in two different Availability Zones must be specified.`.
Added a validator for VPC ID in the fargate recipe to check if that VPC has more than 1 subnet and at least 2 subnets in different availability zones.

feat: add validator to check if VPC has subnets in different AZs

---

src/AWS.Deploy.CLI/Commands/TypeHints/DotnetWindowsBeanstalkPlatformArnCommand.cs
test/AWS.Deploy.CLI.UnitTests/TypeHintCommands/InstanceTypeCommandTest.cs

The interface for type hints changes during the creation of the recent WIndows Beanstalk PR. This PR gets the new type hints compliant.

fix: Instance type and windows platform arn type hints to accommodate recent API changes.

---

mkdocs.yml
site/content/docs/support.md

Currently, the supported application types in the _Support Matrix_  section are denoted by a _"X"_. This can be confusing to customers as they may think that these application types are **not supported**
This PR adds emoji support to the documentation and replaces the _"X"_ with a check-mark emoji

docs: Add emoji support to the docs website

---

site/content/docs/docker/docker-generation.md
site/content/docs/support.md
site/content/troubleshooting-guide/docker-issues.md

*Issue #, if available:*  DOTNET-6011
*Description of changes:* Documentation changes for https://github.com/aws/aws-dotnet-deploy/pull/636

Docs for PR #636 - new exception when generating a Dockerfile with project references located outside of the solution directory

---

site/content/troubleshooting-guide/docker-issues.md

*Issue #, if available:* DOTNET-6060
*Description of changes:* Adding additional entries for the troubleshooting guide for issues related to `docker build`.

Add additional troubleshooting guide entries for docker build issues

---

test/AWS.Deploy.CLI.IntegrationTests/Helpers/TestEnvironmentVariableManager.cs
test/AWS.Deploy.CLI.IntegrationTests/Helpers/Utilities.cs
test/AWS.Deploy.CLI.IntegrationTests/WebAppNoDockerFileTests.cs

The `WebAppNoDockerFileTests` integ tests sets up a custom workspace to use the deploy tool. However, the custom workspace cannot reference the private nuget cache created at - `<USERPROFILE>/.aws-dotnet-deploy/Projects/nuget-cache`.
As a result, the integ tests cannot find the latest (in-development/unreleased) version of `AWS.Deploy.Recipes.CDK.Common.nupkg`
This PR creates a `nuget.config` file inside the custom workspace and adds a reference to the above mentioned nuget-cache

fix: Fix integration tests failure from setting a custom workspace

---

src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalkLinux.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalkWindows.recipe
test/AWS.Deploy.CLI.Common.UnitTests/Recipes/Validation/ElasticBeanStalkOptionSettingItemValidationTests.cs

DOTNET-6095
added regex validation for Preferred Start Time with the pattern "Mon:00:00" in Beanstalk recipe

feat: added validation for Preferred Start Time in Beanstalk recipe

---

src/AWS.Deploy.Common/Recipes/OptionSettingItem.cs

When saving a deployment project all of the settings in the recipe get added `Validation` property which makes no sense in a recipe context because there is no value in the context of a recipe. The fix was to just add the `JsonIgnore` attribute in `OptionSettingItem`. This won't affect serialization in ServerMode because we don't directly pass `OptionSettingItem` through the API. 
```
{
"Id": "ECSServiceName",
"ParentSettingId": "ClusterName",
"Name": "ECS Service Name",
"Category": "General",
"Description": "The name of the ECS service running in the cluster.",
"Type": "String",
...
],
"Validation": {
"ValidationStatus": 0,
"ValidationMessage": ""
}
},
```
By submitting this pull request, I confirm that you can use, modify, copy, and …

fix: Make validation state for the recommendation is not written in deployment project recipe.

---

.github/workflows/doc-builder.yml

*Description of changes:* Currently we republish the GitHub Pages site upon changes to either `main` (what's actually been released) or `dev` (staging branch for next release). 
1. For example, I recently merged https://github.com/aws/aws-dotnet-deploy/pull/671 to `dev`
2. Then https://github.com/aws/aws-dotnet-deploy/actions/runs/2678029950 ran
3. Then https://github.com/aws/aws-dotnet-deploy/commit/0f5ddeb7876b0f0f93a5ab490fe728848829144b was committed to `gh-pages`
This may lead to us accidentally publishing documentation ahead of the corresponding feature being released.
Now we'll only republish the GitHub pages site upon merging to `main`
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under …

ci: No longer republish GitHub Pages documentation upon merge to dev

---

buildtools/ci.template.yml

*Description of changes:* Enables server-side encryption with Amazon S3-managed keys (SSE-S3) for `CodeBuildArtifactsBucket`.

ci: Remove unused CodeBuild bucket

---

src/AWS.Deploy.Common/Exceptions.cs
src/AWS.Deploy.Common/Recipes/OptionSettingItem.ValueOverride.cs
src/AWS.Deploy.Orchestration/Orchestrator.cs
test/AWS.Deploy.CLI.UnitTests/ApplyPreviousSettingsTests.cs
test/AWS.Deploy.CLI.UnitTests/SetOptionSettingTests.cs

DOTNET-6124
The issue was caused by a breaking change we introduced when we changed the Type of the Security group settings in the fargate recipe. The type changed from `string` to `List` which broke the workflow when the tool tried to apply previous settings on redeployments. This change skips broken settings when applying previous settings and it gives users a message that we were unable to set that setting. I also added a validation error when this happens so that the VS Toolkit tells the user that there is an issue with one of the settings, giving the user the option to either fix the issue before deployment.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …

fix: deployments created in preview version don't work in GA version

---

site/content/troubleshooting-guide/index.md
src/AWS.Deploy.Recipes/CdkTemplates/BlazorWasm/Generated/Recipe.cs

*Issue #, if available:* #684 and DOTNET-6190
*Description of changes:* The Blazor recipe uses [CDK's "BucketDeployment" construct](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3_deployment.BucketDeployment.html). An option of that construct is [`memoryLimit`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3_deployment.BucketDeployment.html#memorylimit), which controls _"The amount of memory (in MiB) to allocate to the AWS Lambda function which replicates the files from the CDK bucket to the destination bucket."_ We default that to 4096MB [here](https://github.com/aws/aws-dotnet-deploy/blob/b044bd05f3528ee412cec58619c33d077ca84de1/src/AWS.Deploy.Recipes/CdkTemplates/BlazorWasm/Generated/Recipe.cs#L217), without a way to override it.
Per Lambda docs …

Reduce the memory allocation for the Blazor Lambda publishing function

---

THIRD_PARTY_LICENSES
src/AWS.Deploy.CLI/AWS.Deploy.CLI.csproj

*Issue #, if available:* #675 and DOTNET-6153
*Description of changes:* This introduces the SDK's SSO and SSOOIDC packages to support profiles configured to use [SSO](https://docs.aws.amazon.com/sdkref/latest/guide/access-sso.html) credentials.
We were previously swallowing the `Assembly AWSSDK.SSO could not be found or loaded` exception here:
https://github.com/aws/aws-dotnet-deploy/blob/48ef3bc4eef59896c2b17db5b6895fa4c3a575b1/src/AWS.Deploy.CLI/AWSUtilities.cs#L120-L124
I've also updated our internal attribution tool and regenerated the THIRD_PARTY_LICENSES file.
I did not introduce new automated testing, we don't have long-lived SSO setup in our test account and it'd require a fair amount of manipulation to set everything up automatically. **Let me know if you think it'd be worth it …

Support deploying using AWS IAM Identity Center single sign-on (SSO) credentials

---

buildtools/ci.template.yml

DOTNET-6291
Increase CodeBuild job timeout to 120mins instead of the default 60mins

ci: increase CodeBuild job timeout to account for increased integ tests runtime

---

src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.CLI/Extensions/CustomServiceCollectionExtension.cs
src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
src/AWS.Deploy.Common/CloudApplicationMetadata.cs
src/AWS.Deploy.Common/Recipes/IOptionSettingHandler.cs
src/AWS.Deploy.Common/Recipes/OptionSettingsType.cs
src/AWS.Deploy.Constants/CloudFormationIdentifier.cs
src/AWS.Deploy.Orchestration/CdkAppSettingsSerializer.cs
src/AWS.Deploy.Orchestration/CdkProjectHandler.cs
src/AWS.Deploy.Orchestration/DeploymentSettingsHandler.cs
src/AWS.Deploy.Orchestration/OptionSettingHandler.cs
src/AWS.Deploy.Orchestration/Utilities/Helpers.cs
src/AWS.Deploy.Orchestration/Utilities/TemplateMetadataReader.cs
src/AWS.Deploy.Recipes.CDK.Common/CDKRecipeSetup.cs
src/AWS.Deploy.Recipes.CDK.Common/RecipeProps.cs
test/AWS.Deploy.CLI.UnitTests/GetOptionSettingsMapTests.cs
test/AWS.Deploy.CLI.UnitTests/TemplateMetadataReaderTests.cs
test/AWS.Deploy.CLI.UnitTests/TestFiles/ReadJsonTemplateMetadata.json
test/AWS.Deploy.CLI.UnitTests/TestFiles/ReadYamlTemplateMetadata.yml
test/AWS.Deploy.Orchestration.UnitTests/CDK/CDKProjectHandlerTests.cs

* DOTNET-6032
* https://github.com/aws/aws-dotnet-deploy/issues/153
This PR persists deployment bundle option settings across re-deployments.
It achieves this by writing the deployment bundle option settings in the CloudFormation template metadata under the `aws-dotnet-deploy-deployment-bundle-settings` property.
**Note** - All file and directory paths are written relative to the user's .NET project directory path.

fix: Persist deployment bundle settings across deployments

---

.github/workflows/codebuild-ci.yml

The CodeBuild PR check is failing when it hits the 1 hour mark. I have increased the maximum duration of the IAM roles we are assuming to allow for longer builds. This PR increases the duration in seconds for the assume role to allow builds to run longer than the default 60 seconds.

ci: increase codebuild ci role assume duration

---

src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppEcsFargate/Generated/Configurations/LoadBalancerConfiguration.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppEcsFargate/Generated/Recipe.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppECSFargate.recipe
test/AWS.Deploy.CLI.IntegrationTests/ServerMode/GetApplyOptionSettings.cs

*Issue #, if available:* DOTNET-6294 and #679 
*Description of changes:* Adds a new option setting to the ASP.NET ECS Fargate recipe to expose the [internetFacing?](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_elasticloadbalancing.LoadBalancerProps.html#internetfacing) property in the underlying CDK recipe.
* The GitHub issue suggested exposing `Load Balancer Schema: internet-facing`, but this appears to be mapped to a boolean in CDK.
* I was not able to mark this updatable because the redeployment fails due to https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/780
* Added automated tests that examine the generated CloudFormation template. Did manual testing with both settings, verified that my resulting application was accessible from an instance …

 Enable toggling "Internet-Facing" for the ECS Fargate Load Balancer

---

site/content/troubleshooting-guide/index.md

*Issue #, if available:* DOTNET-5898
*Description of changes:* Adds a troubleshooting guide entry for when an App Runner deployment fails with _Resource handler returned message: "null"_.
Discussed with App Runner internally, this can happen for a variety of reasons so we cannot map it to specific advice. But next steps are likely to check the application logs which we do not expose in the deploy tool yet.

docs: Add troubleshooting guide entry for App Runner Failed with Resource handler returned message: "null"

---

src/AWS.Deploy.CLI/Commands/DeployCommand.cs
src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
src/AWS.Deploy.Constants/ElasticBeanstalk.cs
src/AWS.Deploy.Constants/RecipeIdentifier.cs
src/AWS.Deploy.Orchestration/Data/AWSResourceQueryer.cs
src/AWS.Deploy.Orchestration/DeploymentCommands/BeanstalkEnvironmentDeploymentCommand.cs
src/AWS.Deploy.Orchestration/ServiceHandlers/AWSElasticBeanstalkHandler.cs
src/AWS.Deploy.Orchestration/Utilities/DeployedApplicationQueryer.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppExistingBeanstalkWindowsEnvironment.recipe
test/AWS.Deploy.CLI.IntegrationTests/BeanstalkBackwardsCompatibilityTests/ExistingWindowsEnvironment/CLITests.cs
test/AWS.Deploy.CLI.IntegrationTests/BeanstalkBackwardsCompatibilityTests/ExistingWindowsEnvironment/ServerModeTests.cs
test/AWS.Deploy.CLI.IntegrationTests/BeanstalkBackwardsCompatibilityTests/ExistingWindowsEnvironment/WindowsTestContextFixture.cs
test/AWS.Deploy.CLI.IntegrationTests/BeanstalkBackwardsCompatibilityTests/ExistingWindowsEnvironment/WindowsTestContextFixtureCollection.cs
test/AWS.Deploy.CLI.IntegrationTests/BeanstalkBackwardsCompatibilityTests/TestContextFixtureCollection.cs
test/AWS.Deploy.CLI.IntegrationTests/Helpers/ElasticBeanstalkHelper.cs
test/AWS.Deploy.CLI.IntegrationTests/Helpers/IAMHelper.cs
test/AWS.Deploy.CLI.IntegrationTests/SaveCdkDeploymentProject/RecommendationTests.cs
test/AWS.Deploy.CLI.IntegrationTests/ServerMode/DependencyValidationOptionSettings.cs
test/AWS.Deploy.CLI.IntegrationTests/ServerModeTests.cs
test/AWS.Deploy.CLI.IntegrationTests/Utilities/ServerModeUtilities.cs
test/AWS.Deploy.Orchestration.UnitTests/DeployedApplicationQueryerTests.cs
test/AWS.Deploy.Orchestration.UnitTests/ElasticBeanstalkHandlerTests.cs

DOTNET-6274
Currently, we only support redeploying to existing linux beanstalk environments. From a recent statistic that Chris shared, the ratio of windows to linux beanstalk environments is 2:1. We don't support redeploying to windows environments. So the majority of our existing customers cannot deploy to their existing environments on Windows. This PR adds a new recipe that supports existing Windows beanstalk environments.

feat: add support for deploying to existing windows Beanstalk environments

---

THIRD_PARTY_LICENSES
src/AWS.Deploy.Recipes.CDK.Common/AWS.Deploy.Recipes.CDK.Common.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppAppRunner/AspNetAppAppRunner.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppEcsFargate/AspNetAppEcsFargate.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/AspNetAppElasticBeanstalkLinux.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkWindows/AspNetAppElasticBeanstalkWindows.csproj
src/AWS.Deploy.Recipes/CdkTemplates/BlazorWasm/BlazorWasm.csproj
src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateScheduleTask/ConsoleAppECSFargateScheduleTask.csproj
src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateService/ConsoleAppEcsFargateService.csproj
src/AWS.Deploy.Recipes/RecipeDefinitions/BlazorWasm.recipe

CloudFront added support for HTTP 3 [last month](https://aws.amazon.com/blogs/aws/new-http-3-support-for-amazon-cloudfront/). This PR adds the enums to the recipe for selecting HTTP 3.

feat: Add HTTP3 support for BlazorWasm deployments

---

src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
src/AWS.Deploy.Common/Exceptions.cs
test/AWS.Deploy.CLI.UnitTests/ExceptionExtensionsTests.cs

DOTNET-6257
This PR truncates long error messages so that external telemetery systems that are hooked to the deploy tool via server mode are not overloaded.
Currently, the truncation is only performed in the `GetDeploymentStatus` API call. However, I am unsure if this is the only place from where the data is fed into external telemetry systems. The same concern has also been brought up via internal communication.

chore: Truncate long error messages

---

src/AWS.Deploy.Common/Exceptions.cs
src/AWS.Deploy.Orchestration/Exceptions.cs
src/AWS.Deploy.Orchestration/ServiceHandlers/AWSElasticBeanstalkHandler.cs
src/AWS.Deploy.Orchestration/Utilities/DeployedApplicationQueryer.cs
test/AWS.Deploy.Orchestration.UnitTests/DeployedApplicationQueryerTests.cs

DOTNET-6340
* Added JSON Options to the System.Text.Json deserializer to skip reading comments instead of failing serialization.
* Added exception handling over the deseerialization block to provide user friendly error messages if serialization exceptions happen.

fix: json comments in beanstalk windows manifest caused exception

---

src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalkLinux.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalkWindows.recipe

To allow users to migrate to newer Beanstalk platform versions the setting has been changed to be updatable for redeployments. I have confirm CloudFormation supports changing platform version via this change through the tooling for both single and load balanced environments. It will trigger a replacement of the EC2 instances.

feat: Allow changing Elastic Beanstalk's platform version for environments

---

src/AWS.Deploy.Constants/RecipeIdentifier.cs
src/AWS.Deploy.Orchestration/DeploymentBundleHandler.cs
src/AWS.Deploy.Orchestration/DeploymentCommands/BeanstalkEnvironmentDeploymentCommand.cs
src/AWS.Deploy.Orchestration/ServiceHandlers/AWSElasticBeanstalkHandler.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Recipe.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalkLinux.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalkWindows.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppExistingBeanstalkEnvironment.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppExistingBeanstalkWindowsEnvironment.recipe
test/AWS.Deploy.CLI.IntegrationTests/BeanstalkBackwardsCompatibilityTests/CLITests.cs
test/AWS.Deploy.CLI.IntegrationTests/WebAppNoDockerFileTests.cs
testapps/WebAppNoDockerFile/ElasticBeanStalkConfigFile-Linux-SelfContained.json
testapps/WebAppNoDockerFile/ElasticBeanStalkConfigFile-Linux.json
testapps/WebAppNoDockerFile/Existing-ElasticBeanStalkConfigFile-Linux-SelfContained.json
testapps/WebAppNoDockerFile/WebAppNoDockerFile.csproj

Added support for deploying ASP.NET Core applications that target .NET 7 to Elastic Beanstalk. Since Beanstalk doesn't currently have .NET 7 preinstalled the deployment bundle handler checks to see if the target service is beanstalk and if targeting .NET 7. If that is true then override the self contained setting to be true.
While making this change I discovered that self contained publishes were not working to Elastic Beanstalk because we need to generate a [Procfile](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/dotnet-linux-procfile.html) that tells the Beanstalk environment what process to start. The legacy wizard would generate this file. I updated the CDK project for Linux to generate the `Procfile` as well as the deploy to existing environments …

feat: Add support for deploying .NET 7 applications to Elastic Beanstalk

---

src/AWS.Deploy.CLI/Utilities/CommandLineWrapper.cs
src/AWS.Deploy.Orchestration/DeploymentBundleHandler.cs
src/AWS.Deploy.Orchestration/Utilities/ICommandLineWrapper.cs
test/AWS.Deploy.CLI.UnitTests/Utilities/TestToolCommandLineWrapper.cs
test/AWS.Deploy.Orchestration.UnitTests/TestCommandLineWrapper.cs

When the deploy tool shells out to the docker CLI use the `--password-stdin` switch instead of `--password`. This removes the following warning messages when pushing container images to ECR.
```
Pushing the docker image to ECR repository...
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
```

feat: Switch to use the --password-stdin switch when logging into docker

---

src/AWS.Deploy.Orchestration/Data/AWSResourceQueryer.cs
test/AWS.Deploy.Orchestration.UnitTests/AWSResourceQueryerTests.cs

DOTNET-6536
Current calls to AWS return error messages without any context when those calls fail, similar to the following
```
Configuring AWS Credentials using AWS SDK credential search.
Configuring AWS region with specified value us-west-2.
UnauthorizedOperation
You are not authorized to perform this operation.
For more information, please visit our troubleshooting guide https://aws.github.io/aws-dotnet-deploy/troubleshooting-guide/.
If you are still unable to solve this issue and believe this is an issue with the tooling, please cut a ticket https://github.com/aws/aws-dotnet-deploy/issues/new/choose.
```
The user has no context on what the call was or how to fix the issue.
This PR adds top level/user readable error messages for every …

feat: provide better context and messaging when AWS calls fail

---

.semgrepignore
src/AWS.Deploy.DockerEngine/DockerFile.cs
src/AWS.Deploy.Orchestration/Data/AWSResourceQueryer.cs
test/AWS.Deploy.CLI.Common.UnitTests/AWS.Deploy.CLI.Common.UnitTests.csproj
test/AWS.Deploy.CLI.UnitTests/Utilities/MockPaginatedEnumerable.cs

*Issue #, if available:* DOTNET-6361
*Description of changes:* Addresses warnings from both semgrep and the .NET build.
* For the `Path.Combine` - they were either cases where we want to support relative paths, or else after reviewing code appear to be a false-positive.
* Commit message is intentionally not following conventional commits to avoid a changelog entry as there are no user-facing changes.

Address semgrep issues around Path.Combine and build warnings

---

src/AWS.Deploy.Common/Recipes/Validation/OptionSettingItemValidators/SecurityGroupsInVpcValidator.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppECSFargate.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateService.recipe
test/AWS.Deploy.CLI.Common.UnitTests/Recipes/Validation/ECSFargateOptionSettingItemValidationTests.cs

*Issue #, if available:* DOTNET-6329
*Description of changes:* This applies the existing `SecurityGroupsInVpcValidator` validator to the security groups option in the ASP.NET and console service ECS Fargate recipes. 
Previously it was possible to select security groups that don't match the selected VPC, then the CloudFormation deployment would fail.
```
Stack Deployments Failed: Error: The stack named FargateExtraSecurityGroups failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "Invalid request provided: CreateService error: Security group sg-<redacted> does not appear to belong to the same VPC as the input subnets.
```
Caveats:
* We don't have a security groups option in the ECS Fargate scheduled task recipe …

Validate security groups belong to the selected VPC for the ECS Fargate recipes

---

.github/workflows/doc-builder.yml

ci: doc generator step was failing to push if there are no changes
The Doc generator GitHub workflow failed if there are no doc changes in the release. This changes makes it so that the Workflow checks for changes first before proceeding.

ci: doc generator step was failing to push if there are no changes

---

.github/workflows/codebuild-ci.yml
buildtools/AWS.Deploy.Tools.CI/AWS.Deploy.Tools.CI.sln
buildtools/AWS.Deploy.Tools.CI/AWS.Deploy.Tools.CI/AWS.Deploy.Tools.CI.csproj
buildtools/AWS.Deploy.Tools.CI/AWS.Deploy.Tools.CI/CodeBuildFunctions.cs
buildtools/AWS.Deploy.Tools.CI/AWS.Deploy.Tools.CI/Models/GetAvailableTestRunnerInput.cs
buildtools/AWS.Deploy.Tools.CI/AWS.Deploy.Tools.CI/Startup.cs
buildtools/AWS.Deploy.Tools.CI/AWS.Deploy.Tools.CI/aws-lambda-tools-defaults.json
buildtools/AWS.Deploy.Tools.CI/AWS.Deploy.Tools.CI/serverless.template
buildtools/README.md
buildtools/ci.buildspec.yml
buildtools/ci.template.yml

DOTNET-6292
* Created new project `AWS.Deploy.Tools.CI` which will deploy a Lambda function to our main testing account. This Lambda function will ping multiple test runner accounts (which we will define) to check for availability to run the CodeBuild testing project.
* Updated the CloudFormation template `ci.template.yml` to create needed roles without needing anything to be manually defined.
* Added step in GitHub workflow `codebuild-ci.yml` to call the Lambda function to retrieve the appropriate IAM Role to assume before kicking off the CodeBuild project from GitHub.
**Note**: The `AWS CodeBuild CI` PR check is expected to fail for this PR as I am modifying the workflow file to use a different infrastructure which does not yet exist. …

ci: enable CodeBuild PR checks to run on multiple AWS accounts

---

test/AWS.Deploy.CLI.IntegrationTests/BeanstalkBackwardsCompatibilityTests/ExistingWindowsEnvironment/WindowsTestContextFixture.cs
test/AWS.Deploy.CLI.IntegrationTests/BeanstalkBackwardsCompatibilityTests/TestContextFixture.cs
test/AWS.Deploy.CLI.IntegrationTests/Helpers/ElasticBeanstalkHelper.cs

Integration tests fail when run on a new environment. This is because some tests having a dependency on a hard-coded IAM role which must be present in the environment. This PR removes that dependency and uses a new role that is created for every test run.

chore: remove dependency on existing IAM role for integ tests

---

src/AWS.Deploy.Orchestration/Data/AWSResourceQueryer.cs

*Issue #, if available:* V855437126
*Description of changes:* Amends the exception message thrown when `GetLatestElasticBeanstalkPlatformArn` fails to include inadequate IAM permissions.
An internal user encountered this testing Code Catalyst.

docs: Clarify the exception that is thrown when missing permissions for ListPlatformVersions during Elastic Beanstalk deployments

---

src/AWS.Deploy.Common/Exceptions.cs
src/AWS.Deploy.Orchestration/DeploymentSettingsHandler.cs
test/AWS.Deploy.CLI.Common.UnitTests/ConfigFileDeployment/DeploymentSettingsHandlerTests.cs
test/AWS.Deploy.CLI.Common.UnitTests/ConfigFileDeployment/TestFiles/InvalidConfigFile.json

While running some test scenarios in CodeCatalyst using different deployment settings files I kept the error message `An error occured while trying to deserialize the deployment settings file located at ...`. I was sure the file schema was correct, but was not sure what was the error. I cloned the repo and debugged the CLI. I identified that the same error message is shown to the user whether there was an error deserializing the deployment settings file, of if the file cannot be found.
This fix adds a specific error message telling users to check the path they provided exist to avoid this confusion. For scenarios when the file exists but there is a problem deserializing the JSON, the error message now also shows the specifics of what is wrong with the file. 
--- …

fix: incorrect message when deployment settings file doesn't exist

---

buildtools/ci.template.yml

See https://github.blog/changelog/2023-06-27-github-actions-update-on-oidc-integration-with-aws/
This should hopefully fix the CI failures related to the OIDC thumbprint. We made a similar change for the PowerShell repo recently: https://github.com/aws/aws-tools-for-powershell/commit/05fb600f8bfe76e19758525750b654aa8e0c42e9

chore: Update ci.template.yml with new OIDC Thumbprint

---

.github/workflows/codebuild-ci.yml
README.md
buildtools/ci.buildspec.yml
codecov.yml
test/AWS.Deploy.CLI.Common.UnitTests/AWS.Deploy.CLI.Common.UnitTests.csproj
test/AWS.Deploy.CLI.IntegrationTests/AWS.Deploy.CLI.IntegrationTests.csproj
test/AWS.Deploy.CLI.UnitTests/AWS.Deploy.CLI.UnitTests.csproj
test/AWS.Deploy.DocGenerator.UnitTests/AWS.Deploy.DocGenerator.UnitTests.csproj
test/AWS.Deploy.Orchestration.UnitTests/AWS.Deploy.Orchestration.UnitTests.csproj
test/AWS.Deploy.ServerMode.Client.UnitTests/AWS.Deploy.ServerMode.Client.UnitTests.csproj

DOTNET-6101
This PR enables code coverage on the repository by making the following changes:
1. Adds a package reference to _coverlet.collector_ and _coverlet.msbuild_ in all `*Tests.csproj`. These packages are used to generate coverage reports during test execution.
2. Modifes `buildtools/ci.buildspec.yml` to include test coverge directives with `dotnet test` command and also adds a _post_build_ step to upload coverage reports to Codecov.
3. Modifies the _AWS CodeBuild CI_ GitHub action to read the `CODECOV_TOKEN` from the repository secret and pass it on to the CI CodeBuild job as an environment variable. This is required for uploading reports to Codecov.
5. Added `codecov.yml` config file to customize the behavior of Codecov. It …

chore: Enable code coverage on the repository

---

src/AWS.Deploy.DockerEngine/Properties/DockerFileConfig.json
src/AWS.Deploy.Orchestration/DeploymentBundleHandler.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalkLinux.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalkWindows.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppExistingBeanstalkEnvironment.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppExistingBeanstalkWindowsEnvironment.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateScheduleTask.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateService.recipe
test/AWS.Deploy.CLI.UnitTests/DeploymentBundleHandlerTests.cs
test/AWS.Deploy.CLI.UnitTests/DockerTests.cs
testapps/docker/WebAppNet8/Dockerfile
testapps/docker/WebAppNet8/Program.cs
testapps/docker/WebAppNet8/ReferenceDockerfile
testapps/docker/WebAppNet8/WebAppNet8.csproj
testapps/docker/WebAppNet8/appsettings.Development.json
testapps/docker/WebAppNet8/appsettings.json

DOTNET-7160
DOTNET-7159
* Add .NET8 support for all recipes except for Web Apps on Fargate and App Runner
* Web Apps on Fargate and App Runner will be updated as a quick follow up after ironing out the changes Microsoft made to the base .NET8 docker images

feat: add .NET8 support for Beanstalk web apps and ECS Fargate console apps

---

test/AWS.Deploy.DockerImageUploader/App.cs

* Update the console app to work with the changes introduced in https://github.com/aws/aws-dotnet-deploy/pull/793

update image uploader console app to work with latest changes

---

test/AWS.Deploy.DockerImageUploader/App.cs

Merge the fix for the broken image uploader from `dev` to `main`

Merge fix from dev to main

---

site/content/index.md

The space cause the text rendered as plain text in the [page](https://aws.github.io/aws-dotnet-deploy/)

docs: remove space to render bold correctly

---

site/content/index.md

*Description of changes:* I merged #799 directly to `main` (skipping `dev`) since it was a docs-only change.
This is merging `main`->`dev` so that change is present in dev as well.

Merge main -> dev after docs-only "release"

---

.github/workflows/DetectCDKBootstrapVersionChanges.yml
src/AWS.Deploy.Orchestration/CDK/CDKBootstrapTemplate.yaml

* Update the CDK bootstrap template to the latest version in order to unblock the failing PR check

fix: update the CDK bootstrap template to the latest version

---

THIRD_PARTY_LICENSES
src/AWS.Deploy.Common/AWS.Deploy.Common.csproj
src/AWS.Deploy.Orchestration/AWS.Deploy.Orchestration.csproj
src/AWS.Deploy.ServerMode.Client/AWS.Deploy.ServerMode.Client.csproj

Revert Newtonsoft version bump from 13.0.3 to 13.0.1 due to VS Toolkit compatibility upon @awschristou's request.

chore: revert newtonsoft version bump due to VS Toolkit compatibility

---

.github/workflows/DetectDocGeneratorChanges.yml
.github/workflows/codebuild-ci.yml
.github/workflows/doc-builder.yml

1. Fixes a CI failure on #807. We recently adjusted some internal accounts where we run integration tests, so `CI_AWS_ROLE_ARN` is no longer valid. This reuses the `CI_MAIN_TESTING_ACCOUNT_ROLE_ARN` instead.
* The doc generator uses server mode, which requires AWS credentials to pass its health check. I didn't actually see it make any requests when running locally.
3. Also upgraded the credential action while here, there was a warning about old Node versions.

Adjust role used by GitHub action that builds docs.

---

src/AWS.Deploy.Constants/ElasticBeanstalk.cs

*Issue #, if available:* #806 (I had tested this quickly when talking to @shruti0085 internally about this issue)
This widens the string we use to filter Beanstalk Platform options when deploying to Linux, to include the new ".NET 6 on AL2023" platform that was [released in October](https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2023-10-19-al2023.html).
**Considerations**:
* The sort order we're getting back from the service call is what I think we want, so didn't introduce custom sorting like we have for Windows here: https://github.com/aws/aws-dotnet-deploy/blob/03abb117585784ad0fec360e7c5093e37ddf7993/src/AWS.Deploy.Orchestration/Data/AWSResourceQueryer.cs#L627
* Per the [docs](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/ …

fix: Enable selecting the '.NET 6 on AL2023' platform when deploying to Elastic Beanstalk on Linux

---

.github/workflows/DetectCDKBootstrapVersionChanges.yml
.github/workflows/DetectDocGeneratorChanges.yml
.github/workflows/DetectRestAPIClientChanges.yml
.github/workflows/codebuild-ci.yml

*Description of changes:* We noticed while attempting to merge #813 that we were unable to. 
* GitHub checks are failing because the PR is from a fork. Typically a maintainer will review, run tests locally if necessary, then merge despite the failures. 
* However we recently cleaned up our GitHub team structure, which removed the ability to merge despite failing checks for most maintainers.
* This repository is configured to require on the `build` status check, but we had used that name across different actions, so more were required than what we intended.
I think this was unintentional, so I'm renaming these actions so that the only `build` one is the build+unit tests.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …

ci: Disambiguate GitHub job IDs to fix required status checks

---

.github/workflows/codebuild-ci.yml

*Description of changes:* Same as https://github.com/awslabs/aws-dotnet-messaging/pull/94, I'm still not sure what changed that led to this but fixing it up.

Fix escaping for Lambda invocation that selects which account to run integration tests in

---

src/AWS.Deploy.ServerMode.Client/AnnotatedModels.cs

This change adds the `DebuggerDisplay` attribute to more models that get visually inspected when debugging in the Toolkit.

chore: Add debugger display hints for servermode clients

---

src/AWS.Deploy.CLI/Commands/TypeHints/ExistingSecurityGroupsCommand.cs
test/AWS.Deploy.CLI.UnitTests/TypeHintCommands/ExistingSecurityGroubsCommandTest.cs

Security Group IDs don't provide enough context on their own for users to choose the right ones from their account. We received Toolkit feedback that users ended up logging into the web console in order to verify they are selecting the correct security group(s) when deploying their project.
This change updates the display value for security groups, so that it shows the group name and id.
Here is an example using this change:

Adjust Security Group type hints to show the group name and id

---

THIRD_PARTY_LICENSES
src/AWS.Deploy.Recipes.CDK.Common/AWS.Deploy.Recipes.CDK.Common.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppAppRunner/AspNetAppAppRunner.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppEcsFargate/AspNetAppEcsFargate.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/AspNetAppElasticBeanstalkLinux.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Recipe.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkWindows/AspNetAppElasticBeanstalkWindows.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkWindows/Generated/Recipe.cs
src/AWS.Deploy.Recipes/CdkTemplates/BlazorWasm/BlazorWasm.csproj
src/AWS.Deploy.Recipes/CdkTemplates/BlazorWasm/Generated/Recipe.cs
src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateScheduleTask/ConsoleAppECSFargateScheduleTask.csproj
src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateService/ConsoleAppEcsFargateService.csproj

*Description of changes:* 
Our integration tests began failing for the Blazor recipe:
* Example CI failure: https://github.com/aws/aws-dotnet-deploy/actions/runs/8193118953/job/22406129833
> 2024-03-07T18:42:09.0042659Z BlazorWasm60c01024a63d82 |  6/14 | 6:37:45 PM | CREATE_FAILED        | AWS::Lambda::Function                           | Custom::S3AutoDeleteObjectsCustomResourceProvider/Handler (CustomS3AutoDeleteObjectsCustomResourceProviderHandler9D90184F) Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs20.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: …

chore: Update the version of Amazon.CDK.Lib that is referenced by the recipe CDK projects

---

buildtools/canarysettings/AppRunnerCanary.json
buildtools/canarysettings/ECSFargateCanary.json
buildtools/canarysettings/ECSServiceCanary.json
buildtools/canarysettings/PushContainerImageCanary.json
buildtools/smoketests.proj

*Issue #, if available:* DOTNET-7485
*Description of changes:* This is the test project that will be used to power an internal canary that will attempt deployments using the _published version of the tool_ with the test apps we use for integration tests.
* It uses the `/testapps` and their settings files where possible, but I did redefine some settings files to handle the docker execution directory correctly.
* It initially covers the initial deployment for each recipe. We may expand it in the future to cover redeployments and/or more advanced configuration.

test: Add project for executing canary tests using the published tool

---

buildtools/canarysettings/AppRunnerCanary.json
buildtools/canarysettings/ECSFargateCanary.json
buildtools/canarysettings/ECSServiceCanary.json
buildtools/canarysettings/PushContainerImageCanary.json
buildtools/smoketests.proj

*Description of changes:* Merging `dev` -> `main` for #823 

Merging dev -> main for #823 

---

src/AWS.Deploy.CLI/App.cs
src/AWS.Deploy.CLI/Commands/CommandFactory.cs
test/AWS.Deploy.CLI.IntegrationTests/VersionTest.cs

Currently, the output from the `--version` switch is suffixed with the git commit hash which is not desirable.
This PR fixes the output of the `--version` switch so that it reflects the actual assembly version without the commit hash

Fix: Display correct versioning info

---

THIRD_PARTY_LICENSES
src/AWS.Deploy.Recipes.CDK.Common/AWS.Deploy.Recipes.CDK.Common.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppAppRunner/AspNetAppAppRunner.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppEcsFargate/AspNetAppEcsFargate.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/AspNetAppElasticBeanstalkLinux.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkWindows/AspNetAppElasticBeanstalkWindows.csproj
src/AWS.Deploy.Recipes/CdkTemplates/BlazorWasm/BlazorWasm.csproj
src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateScheduleTask/ConsoleAppECSFargateScheduleTask.csproj
src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateService/ConsoleAppEcsFargateService.csproj

DOTNET-7536
* Update CDK version used by Recipes to 2.146.0

chore: update CDK version used by Recipes

---

site/content/docs/cicd/recipes/ASP.NET Core App to AWS Elastic Beanstalk on Linux.md
site/content/docs/cicd/recipes/ASP.NET Core App to AWS Elastic Beanstalk on Windows.md
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Configurations/Configuration.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Recipe.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkWindows/Generated/Configurations/Configuration.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkWindows/Generated/Recipe.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalkLinux.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalkWindows.recipe
test/AWS.Deploy.CLI.Common.UnitTests/ConfigFileDeployment/TestFiles/SettingsSnapshot_NonContainer.json

*Issue #, if available:* DOTNET-7553
*Description of changes:* 
This adds a new option setting for "Load Balancer Scheme" to Linux and Windows Elastic Beanstalk recipes.
This is only visible when:
* Deploying a Load Balanced application (as opposed to single instance)
* Deploying into a VPC (otherwise it's implicitly "public")
This corresponds to the `ELBScheme` option in the `aws:ec2:vpc` namespace: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-ec2vpc
**Note:** I didn't add an integration test for this because it requires valid VPC selections, and I don't believe we're covering every possible option. Let me know if you think we should add one.
By submitting this pull request, I confirm that you can use, modify, copy, and …

feat: Expose Load Balancer Scheme for EB Recipes

---

src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs
src/AWS.Deploy.Common/Recipes/OptionSettingItem.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppAppRunner.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppECSFargate.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalkLinux.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalkWindows.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateScheduleTask.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateService.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/aws-deploy-recipe-schema.json
test/AWS.Deploy.CLI.IntegrationTests/ServerModeTests.cs

DOTNET-6316
* Added a 'VisibileOnRedeployment' boolean on the option settings in the Recipe which determines the visibility of a setting during a redeployment when 'Updatable' is false
* The setting is false by default, meaning any setting with 'Updatable' = false will not be visible during redeployment.
* I have set the fields that have important names as visible during redeployment
* I have tested this behavior with the toolkit and CLI

feat: Remove disabled fields from showing on redeployment in server mode

---

src/AWS.Deploy.CLI/Commands/TypeHints/DotnetBeanstalkPlatformArnCommand.cs
src/AWS.Deploy.CLI/Commands/TypeHints/DotnetWindowsBeanstalkPlatformArnCommand.cs
src/AWS.Deploy.CLI/ServerMode/Services/SessionAWSResourceQuery.cs
src/AWS.Deploy.Common/Data/IAWSResourceQueryer.cs
src/AWS.Deploy.Common/Exceptions.cs
src/AWS.Deploy.Orchestration/CDK/CDKBootstrapTemplate.yaml
src/AWS.Deploy.Orchestration/Data/AWSResourceQueryer.cs
src/AWS.Deploy.Orchestration/DeploymentBundleHandler.cs
src/AWS.Deploy.Orchestration/Exceptions.cs
src/AWS.Deploy.Orchestration/Orchestrator.cs
src/AWS.Deploy.Orchestration/Utilities/DeployedApplicationQueryer.cs
test/AWS.Deploy.CLI.IntegrationTests/BeanstalkBackwardsCompatibilityTests/ExistingWindowsEnvironment/WindowsTestContextFixture.cs
test/AWS.Deploy.CLI.IntegrationTests/BeanstalkBackwardsCompatibilityTests/TestContextFixture.cs
test/AWS.Deploy.CLI.IntegrationTests/Helpers/ElasticBeanstalkHelper.cs
test/AWS.Deploy.CLI.IntegrationTests/Utilities/TestToolAWSResourceQueryer.cs
test/AWS.Deploy.CLI.UnitTests/DeploymentBundleHandlerTests.cs
test/AWS.Deploy.CLI.UnitTests/TypeHintTests.cs
test/AWS.Deploy.CLI.UnitTests/Utilities/TestToolAWSResourceQueryer.cs
test/AWS.Deploy.Orchestration.UnitTests/AWSResourceQueryerTests.cs
test/AWS.Deploy.Orchestration.UnitTests/DeployedApplicationQueryerTests.cs

DOTNET-7212
In order to support deploying .NET8 apps on Beanstalk prior to Beanstalk adding .NET8 support, we had to force .NET8 apps to be self-contained in order to allow for Beanstalk support. Beanstalk has since added .NET8 support, so this PR removes this restriction to allow .NET8 apps to be deployed to Beanstalk not as self-contained apps.
This PR also improves the sorting of Beanstalk platforms to show the latest .NET versions first.

fix: remove auto self-contained build for .NET 8 beanstalk deployments

---

src/AWS.Deploy.Recipes.CDK.Common/AWS.Deploy.Recipes.CDK.Common.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppAppRunner/AspNetAppAppRunner.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppEcsFargate/AspNetAppEcsFargate.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/AspNetAppElasticBeanstalkLinux.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkWindows/AspNetAppElasticBeanstalkWindows.csproj
src/AWS.Deploy.Recipes/CdkTemplates/BlazorWasm/BlazorWasm.csproj
src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateScheduleTask/ConsoleAppECSFargateScheduleTask.csproj
src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateService/ConsoleAppEcsFargateService.csproj

https://github.com/aws/aws-toolkit-visual-studio/issues/462
The generated CDK projects have `TreatWarningsAsErrors` as true which makes deployments start failing immediately when a dependency has a listed vulnerability. In this case System.Text.Json has a listed failure which causes the generated CDK project fail to build preventing deployment.
This PR updates the version of `System.Text.Json` which was actually coming in as a transitive dependency from `Microsoft.Extensions.Configuration.Json`. It also removes the `TreatWarningsAsErrors` property from the generated projects because we have no control when a package might be listed as vulnerable and we don't one deployments to just start failing when that happens. 
By submitting this pull …

fix: Generated CDK projects referencing version of System.Text.Json

---

.github/workflows/create-release-pr-v4sdk.yml
.github/workflows/sync-v4sdk-release-v4sdk-development.yml

Duplicates existing `create-release-pr` and `sync-main-dev` workflows into V4 versions that target the V4 branches `v4sdk-release` and `v4sdk-development`.

ci: add v4 release workflows

---

.autover/autover.json
.github/workflows/create-release-pr.yml
.github/workflows/sync-main-dev.yml

This change updates `AutoVer` to version 0.0.22 to add support for versioning all projects using the same version number. Moving forward, whether a project has changes or not, its version will be updated using the same version as the projects that have changes.
As an example, if we have the following versions:
* Project 1 (1.20.0)
* Project 2 (1.25.0)
* Project 3 (1.30.0)
The version 1.30.0 will be used for future versioning. Depending on what increment type you are using, all projects will have the following version:
* Patch: 1.30.1
* Minor: 1.31.0
* Major: 2.0.0

ci: add ability to version all projects the same

---

.autover/changes/a341e9ce-1356-465d-b1b4-77743905d586.json
src/AWS.Deploy.Orchestration/CDK/CDKBootstrapTemplate.yaml

Update CDK Bootstrap template to version 23 follow CDK v2.162.0

chore: update CDK Bootstrap template to version 23

---

.autover/changes/a341e9ce-1356-465d-b1b4-77743905d586.json
src/AWS.Deploy.Recipes.CDK.Common/AWS.Deploy.Recipes.CDK.Common.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppAppRunner/AspNetAppAppRunner.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppEcsFargate/AspNetAppEcsFargate.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/AspNetAppElasticBeanstalkLinux.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkWindows/AspNetAppElasticBeanstalkWindows.csproj
src/AWS.Deploy.Recipes/CdkTemplates/BlazorWasm/BlazorWasm.csproj
src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateScheduleTask/ConsoleAppECSFargateScheduleTask.csproj
src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateService/ConsoleAppEcsFargateService.csproj

While trying to deploy a web app, the deployment failed due to a conflict between the `System.Text.Json` in the CDK Templates and the one in my web app. In order to avoid these conflicts, we should remove the reference from the CDK templates.

chore: remove System.Text.Json dependency to not conflict user apps

---

.autover/changes/07AEC2AC-0C7B-4C60-9EAF-C92E6A805559.json
site/content/docs/cicd/recipes/ASP.NET Core App to AWS Elastic Beanstalk on Linux.md
site/content/docs/cicd/recipes/ASP.NET Core App to AWS Elastic Beanstalk on Windows.md
src/AWS.Deploy.DockerEngine/Properties/DockerFileConfig.json
src/AWS.Deploy.Orchestration/CdkAppSettingsSerializer.cs
src/AWS.Deploy.Orchestration/DeploymentBundleHandler.cs
src/AWS.Deploy.Recipes.CDK.Common/AWS.Deploy.Recipes.CDK.Common.csproj
src/AWS.Deploy.Recipes.CDK.Common/RecipeProps.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppAppRunner/AspNetAppAppRunner.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppEcsFargate/AspNetAppEcsFargate.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/AspNetAppElasticBeanstalkLinux.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Configurations/Configuration.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/Generated/Recipe.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkWindows/AspNetAppElasticBeanstalkWindows.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkWindows/Generated/Configurations/Configuration.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkWindows/Generated/Recipe.cs
src/AWS.Deploy.Recipes/CdkTemplates/BlazorWasm/BlazorWasm.csproj
src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateScheduleTask/ConsoleAppECSFargateScheduleTask.csproj
src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateService/ConsoleAppEcsFargateService.csproj
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppAppRunner.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppECSFargate.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalkLinux.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalkWindows.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppExistingBeanstalkEnvironment.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppExistingBeanstalkWindowsEnvironment.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateScheduleTask.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateService.recipe
test/AWS.Deploy.CLI.Common.UnitTests/ConfigFileDeployment/DeploymentSettingsHandlerTests.cs
test/AWS.Deploy.CLI.Common.UnitTests/ConfigFileDeployment/TestFiles/SettingsSnapshot_NonContainer.json
test/AWS.Deploy.CLI.Common.UnitTests/ConfigFileDeployment/TestFiles/SettingsSnapshot_NonContainer_ModifiedOnly.json

https://github.com/aws/aws-dotnet-deploy/issues/877
EC2 made a change that new accounts created after Oct 1 2024. This means today if an account created after Oct 1st tries to deploy to Beanstalk using our tooling it will fail because it can't create a LaunchConfiguration.
To force Beanstalk you need to set one of the following 4 settings.
* RootVolumeType
* BlockDeviceMappings
* DisableIMDSv1 -> `true`
* EnableSpot
(For reference the Beantalk Developer Guide: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environments-cfg-autoscaling-launch-templates.html)
None of these setting are currently settable in the tooling. Ideally we should add support for now I added `DisableIMDSv1`. The other settings require more settings to be set …

Add support for .NET 9 and support for disabling IMDS v1

---

.autover/changes/721a3463-3ad9-413d-b2b6-11efb7575fac.json
src/AWS.Deploy.Orchestration/CDK/CDKBootstrapTemplate.yaml
src/AWS.Deploy.Orchestration/Data/AWSResourceQueryer.cs

1. Update platform query logic to support deprecated beanstalk platforms. Why? .net 6 is was just marked as deprecated by beanstalk a couple days ago and now customers cannot deploy .net 6 to beanstalk with deploy tool. This change updates the logic so that .net 6 will work by allowing deprecated versions.

Update platform query logic to support deprecated

---

.autover/changes/ebd7f49a-72cd-4c5b-83f4-2790a2560e94.json
src/AWS.Deploy.CLI/AWSCredentialsFactory.cs
src/AWS.Deploy.CLI/AWSUtilities.cs
src/AWS.Deploy.CLI/Commands/CommandFactory.cs
src/AWS.Deploy.CLI/CredentialProfileStoreChainFactory.cs
src/AWS.Deploy.CLI/Extensions/CustomServiceCollectionExtension.cs
src/AWS.Deploy.CLI/IAWSCredentialsFactory.cs
src/AWS.Deploy.CLI/ICredentialProfileStoreChainFactory.cs
src/AWS.Deploy.CLI/ISharedCredentialsFileFactory.cs
src/AWS.Deploy.CLI/SharedCredentialsFileFactory.cs
test/AWS.Deploy.CLI.UnitTests/AWSCredentialsFactoryTests.cs
test/AWS.Deploy.CLI.UnitTests/AWSUtilitiesTests.cs
test/AWS.Deploy.CLI.UnitTests/Commands/CommandFactoryTest.cs
test/AWS.Deploy.CLI.UnitTests/CredentialProfileStoreChainFactoryTests.cs
test/AWS.Deploy.CLI.UnitTests/SharedCredentialsFileFactoryTests.cs

The problem we are trying to solve is that the dotnet tool does not take into account the AWS region when a non default profile is being used. It will use the region set on the default profile (if available) instead.
Also, this change also updates the cdk bootstrap version
For example consider the following profile setups.
Scenario 1
```
[test]
access-key=xyz
secret-key=abc
region=us-west-2
[default]
access-key=xyz
secret-key=abc
region=us-east-1
```
Running the program with
`AWS.Deploy.CLI.exe deploy --profile test`
will result in region `us-east-1`  being used rather than `us-west-2`
As a workaround, we let the user know to provide the --region parameter when a non default profile is being used
`AWS.Deploy.CLI.exe deploy --profile …

Read region value for non default profiles

---

.autover/changes/27d0ce13-f148-4129-a977-1ae2fa1b36e4.json
src/AWS.Deploy.ServerMode.Client/AWS.Deploy.ServerMode.Client.csproj

When building with .NET 9 we were getting 
```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	NU1903	Warning As Error: Package 'System.Text.Json' 6.0.8 has a known high severity vulnerability, https://github.com/advisories/GHSA-8g4q-xg66-9fp4	AWS.Deploy.ServerMode.Client
```
The System.Text.Json dependency comes from `Microsoft.AspNetCore.SignalR.Client`
This change updates the `Microsoft.AspNetCore.SignalR.Client` version that includes the patched System.Text.Json version `(6.0.11)`

Update Microsoft.AspNetCore.SignalR.Client version to fix System.Text.Json vulnerability

---

test/AWS.Deploy.CLI.IntegrationTests/Helpers/IAMHelper.cs

The beanstalk tests deploying from existing environments are failing because existing environments were being created without permissions to download the deployment bundle from S3. This PR adds the managed beanstalk policy to the role that being created as part of the test.

Fix Beanstalk integ tests

---

.github/workflows/change-file-in-pr.yml
CONTRIBUTING.md

The PR updates the CONTRIBUTION.md file and adds a new Workflow that checks if a PR contains a `change` file. If a change file is not required, PRs should add the label `Release Not Needed`.

chore: add workflow to check if change file is included in a PR

---

.autover/changes/10243e8a-1016-4527-84f2-1ca049109c7c.json
THIRD_PARTY_LICENSES
src/AWS.Deploy.Recipes.CDK.Common/AWS.Deploy.Recipes.CDK.Common.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppAppRunner/AspNetAppAppRunner.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppEcsFargate/AspNetAppEcsFargate.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/AspNetAppElasticBeanstalkLinux.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkWindows/AspNetAppElasticBeanstalkWindows.csproj
src/AWS.Deploy.Recipes/CdkTemplates/BlazorWasm/BlazorWasm.csproj
src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateScheduleTask/ConsoleAppECSFargateScheduleTask.csproj
src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateService/ConsoleAppEcsFargateService.csproj

This PR  updates the version of `Amazon.CDK.Lib` referenced by the recipe projects.

chore: Update the version of Amazon.CDK.Lib referenced by the recipe projects

---

.autover/changes/1292d7ce-01b0-41d2-b0a5-58ae76457ced.json
.github/workflows/DetectCDKBootstrapVersionChanges.yml
buildtools/ci.buildspec.yml
src/AWS.Deploy.DockerEngine/Templates/Dockerfile.Net6.template
src/AWS.Deploy.DockerEngine/Templates/Dockerfile.template
src/AWS.Deploy.Orchestration/CDK/CDKBootstrapTemplate.yaml
testapps/WebAppNet8WithCustomDockerFile/Dockerfile
testapps/docker/ConsoleSdkType/Dockerfile
testapps/docker/ConsoleSdkType/ReferenceDockerfile
testapps/docker/WebAppDifferentAssemblyName/Dockerfile
testapps/docker/WebAppDifferentAssemblyName/ReferenceDockerfile
testapps/docker/WebAppDifferentTargetFramework/Dockerfile
testapps/docker/WebAppDifferentTargetFramework/ReferenceDockerfile
testapps/docker/WebAppNet7/Dockerfile
testapps/docker/WebAppNet7/ReferenceDockerfile
testapps/docker/WebAppNet8/Dockerfile
testapps/docker/WebAppNet8/ReferenceDockerfile
testapps/docker/WebAppNoSolution/Dockerfile
testapps/docker/WebAppNoSolution/ReferenceDockerfile
testapps/docker/WebAppProjectDependencies/WebAppProjectDependencies/Dockerfile
testapps/docker/WebAppProjectDependencies/WebAppProjectDependencies/ReferenceDockerfile
testapps/docker/WebAppWithSolutionParentLevel/WebAppWithSolutionParentLevel/Dockerfile
testapps/docker/WebAppWithSolutionParentLevel/WebAppWithSolutionParentLevel/ReferenceDockerfile
testapps/docker/WebAppWithSolutionSameLevel/Dockerfile
testapps/docker/WebAppWithSolutionSameLevel/ReferenceDockerfile
testapps/docker/WorkerServiceExample/Dockerfile
testapps/docker/WorkerServiceExample/ReferenceDockerfile

*Issue #, if available:* DOTNET-7986
1.  Update node to version 22 since 18 is end of life in april.
2. Add `cdk acknowledge`. This is needed because when doing cdk commands now an extra warning text appears the first time its being ran. This extra text breaks our logic because we pipe the output of the command to a file and parse it. So by adding cdk acknowledge it doesnt show the extra text anymore.

update node to 22

---

.autover/changes/a2dd7cca-b2c5-47e1-8bce-34eb5239a047.json
src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateScheduleTask/Generated/Recipe.cs
src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateService/Generated/Recipe.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateScheduleTask.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/ConsoleAppECSFargateService.recipe
test/AWS.Deploy.CLI.IntegrationTests/ConsoleAppTests.cs

DOTNET-5124
* Updated `ConsoleAppEcsFargateService` and `ConsoleAppEcsFargateScheduleTask` recipes and CDK templates to support ARM deployments.
* Added an integration test to deploy an ARM console app

feat: add support for deploying ARM console apps to ECS Fargate

---

src/AWS.Deploy.CLI/ServerMode/Services/SessionAWSResourceQuery.cs
src/AWS.Deploy.Common/Data/IAWSResourceQueryer.cs
src/AWS.Deploy.Common/Recipes/Validation/RecipeValidatorList.cs
src/AWS.Deploy.Common/Recipes/Validation/RecipeValidators/BeanstalkInstanceTypeValidator.cs
src/AWS.Deploy.Common/Recipes/Validation/ValidatorFactory.cs
src/AWS.Deploy.Orchestration/Data/AWSResourceQueryer.cs
src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalkLinux.recipe
src/AWS.Deploy.Recipes/RecipeDefinitions/aws-deploy-recipe-schema.json
test/AWS.Deploy.CLI.IntegrationTests/BeanstalkBackwardsCompatibilityTests/ExistingWindowsEnvironment/WindowsTestContextFixture.cs
test/AWS.Deploy.CLI.IntegrationTests/BeanstalkBackwardsCompatibilityTests/TestContextFixture.cs
test/AWS.Deploy.CLI.IntegrationTests/Utilities/TestToolAWSResourceQueryer.cs
test/AWS.Deploy.CLI.IntegrationTests/WebAppNoDockerFileTests.cs
test/AWS.Deploy.CLI.UnitTests/Utilities/TestToolAWSResourceQueryer.cs
testapps/WebAppNoDockerFile/WebAppNoDockerFile.csproj

DOTNET-8065
* Add a recipe validator for the Beanstalk recipe which checks if the `Environment Architecture` is compatible with the selected `Instance Type`. If no `Instance Type` is selected and CDK is selecting the instance, I am querying Beanstalk to fetch the Instance Type in order to check the architecture.

feat: add validator for beanstalk when switching architecture on redeployment

---

.autover/changes/1c879063-ec4b-4330-80a2-3f2116812150.json
AWS.Deploy.sln
buildtools/ci.buildspec.yml
src/AWS.Deploy.Orchestration/DeploymentBundleHandler.cs
test/AWS.Deploy.CLI.IntegrationTests/ConsoleAppTests.cs
test/AWS.Deploy.CLI.IntegrationTests/WebAppNoDockerFileTests.cs
test/AWS.Deploy.CLI.UnitTests/DeploymentBundleHandlerTests.cs
testapps/ConsoleAppArmDeployment/ConsoleAppArmDeployment.csproj
testapps/ConsoleAppArmDeployment/Dockerfile
testapps/ConsoleAppArmDeployment/Program.cs
testapps/WebApiNET6/ElasticBeanStalkConfigFile.json
testapps/WebApiNET6/WebApiNET6.csproj

DOTNET-8094
* Instead of tracking the unsupported dotnet versions, we are now tracking the supported ones and everything else will be deployed as self-contained.
* We are also tracking the retired .net versions to provide the user messaging informing them that they are using an out of support version

chore: self-contain unsupported .net versions on beanstalk

---

THIRD_PARTY_LICENSES
src/AWS.Deploy.CLI/AWS.Deploy.CLI.csproj
src/AWS.Deploy.Constants/CDK.cs
src/AWS.Deploy.Orchestration/AWS.Deploy.Orchestration.csproj
src/AWS.Deploy.Recipes.CDK.Common/AWS.Deploy.Recipes.CDK.Common.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppAppRunner/AspNetAppAppRunner.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppEcsFargate/AspNetAppEcsFargate.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/AspNetAppElasticBeanstalkLinux.csproj
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkWindows/AspNetAppElasticBeanstalkWindows.csproj
src/AWS.Deploy.Recipes/CdkTemplates/BlazorWasm/BlazorWasm.csproj
src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateScheduleTask/ConsoleAppECSFargateScheduleTask.csproj
src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateService/ConsoleAppEcsFargateService.csproj
test/AWS.Deploy.Orchestration.UnitTests/CDK/CDKVersionDetectorTests.cs
test/AWS.Deploy.Orchestration.UnitTests/CDK/CSProjFiles/MixedReferences
test/AWS.Deploy.Orchestration.UnitTests/CDK/CSProjFiles/SameReferences

DOTNET-8095
Update CDK to the latest version.
I remove the System.Text.Json reference in certain places because it conflicts with the new one that CDK is referencing which is 9.0.1.

chore: update CDK version

---

src/AWS.Deploy.CLI/Commands/GenerateDeploymentProjectCommand.cs
src/AWS.Deploy.Orchestration/AWS.Deploy.Orchestration.csproj
src/AWS.Deploy.Orchestration/CdkProjectHandler.cs
src/AWS.Deploy.Orchestration/TemplateEngine.cs
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppAppRunner/.template.config/template.json
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppEcsFargate/.template.config/template.json
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkLinux/.template.config/template.json
src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppElasticBeanstalkWindows/.template.config/template.json
src/AWS.Deploy.Recipes/CdkTemplates/BlazorWasm/.template.config/template.json
src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateScheduleTask/.template.config/template.json
src/AWS.Deploy.Recipes/CdkTemplates/ConsoleAppECSFargateService/.template.config/template.json

DOTNET-8095
* Upgrade templating engine from .NET5 to .NET8 since a lot of changes have happened to their public interfaces

chore: upgrade templating engine to net8

---

.github/workflows/AutoUpdateBootstrap.yml
.github/workflows/DetectCDKBootstrapVersionChanges.yml
src/AWS.Deploy.Orchestration/CDK/CDKBootstrapTemplate.yaml

1. Updated github workflow to be automatically ran every monday and will create a PR to update the CDK bootstrap template. It can also be ran manually if needed. 

Automatically update bootstrap template

---

README.md
site/content/docs/getting-started/pre-requisites.md
site/content/troubleshooting-guide/missing-dependencies.md
src/AWS.Deploy.Orchestration/SystemCapabilityEvaluator.cs

DOTNET-8095
Update NodeJS minimum version to 18 since AWS CDK has dropped support for 14 and 16 https://aws.amazon.com/blogs/devops/announcing-the-end-of-support-for-node-js-14-x-and-16-x-in-aws-cdk/

feat: update NodeJS minimum version to 18

---

test/AWS.Deploy.CLI.IntegrationTests/WebAppNoDockerFileTests.cs

DOTNET-8126
1. Use t3.micro instead of t2.micro. See ticket details for more info

Use t3 micro for tests

---

.github/workflows/AutoUpdateBootstrap.yml
.github/workflows/DetectDocGeneratorChanges.yml
.github/workflows/UploadDockerImage.yml
.github/workflows/aws-ci.yml
.github/workflows/create-release-pr.yml
.github/workflows/doc-builder.yml
.github/workflows/semgrep-analysis.yml
.github/workflows/sync-main-dev.yml
src/AWS.Deploy.Orchestration/CDK/CDKBootstrapTemplate.yaml
test/AWS.Deploy.CLI.IntegrationTests/WebAppNoDockerFileTests.cs

Merge dev into main

---

.github/workflows/AutoUpdateBootstrap.yml

Fix handling case where branch already exists. Ran it manually and it successfully made https://github.com/aws/aws-dotnet-deploy/pull/937#pullrequestreview-2845128924

Fix bootstrap script

---

.autover/changes/3a630e1b-18ac-44ce-93fd-5a5954fa645c.json
src/AWS.Deploy.Orchestration/CDK/CDKBootstrapTemplate.yaml
src/AWS.Deploy.Orchestration/Docker/Templates/Dockerfile.Net6.template
src/AWS.Deploy.Orchestration/Docker/Templates/Dockerfile.template
testapps/WebAppArmWithDocker/Dockerfile
testapps/WebAppNet8WithCustomDockerFile/Dockerfile
testapps/docker/ConsoleSdkType/Dockerfile
testapps/docker/ConsoleSdkType/ReferenceDockerfile
testapps/docker/WebAppDifferentAssemblyName/Dockerfile
testapps/docker/WebAppDifferentAssemblyName/ReferenceDockerfile
testapps/docker/WebAppDifferentTargetFramework/Dockerfile
testapps/docker/WebAppDifferentTargetFramework/ReferenceDockerfile
testapps/docker/WebAppNet7/Dockerfile
testapps/docker/WebAppNet7/ReferenceDockerfile
testapps/docker/WebAppNet8/Dockerfile
testapps/docker/WebAppNet8/ReferenceDockerfile
testapps/docker/WebAppNoSolution/Dockerfile
testapps/docker/WebAppNoSolution/ReferenceDockerfile
testapps/docker/WebAppProjectDependencies/WebAppProjectDependencies/Dockerfile
testapps/docker/WebAppProjectDependencies/WebAppProjectDependencies/ReferenceDockerfile
testapps/docker/WebAppWithSolutionParentLevel/WebAppWithSolutionParentLevel/Dockerfile
testapps/docker/WebAppWithSolutionParentLevel/WebAppWithSolutionParentLevel/ReferenceDockerfile
testapps/docker/WebAppWithSolutionSameLevel/Dockerfile
testapps/docker/WebAppWithSolutionSameLevel/ReferenceDockerfile
testapps/docker/WorkerServiceExample/Dockerfile
testapps/docker/WorkerServiceExample/ReferenceDockerfile

Remove NodeJS from docker images since Microsoft no longer ships Angular and React templates for Web Apps. This also fixes an issue caused by a mismatch in architectures in the base images across the docker stages.

fix: fix cross-platform issues with docker files

---

.autover/changes/aeb80c58-0a88-4bcb-9fc4-c23c4045e6ec.json
src/AWS.Deploy.Orchestration/DeploymentBundleHandler.cs
test/AWS.Deploy.CLI.UnitTests/DeploymentBundleHandlerTests.cs

https://github.com/aws/aws-toolkit-visual-studio/issues/521
Add the `--load` flag in `docker buildx build` because, unlike the standard `docker build` command, `buildx` doesn't automatically load the resulting image into the local Docker image store. When using `buildx` with certain docker drivers (like `docker-container`), the build process happens in a container, and the resulting image needs to be explicitly loaded into the local image store using `--load`.

fix: add --load flag to docker buildx build
